### ISSUE TITLE
提示"miuitask.py", line 16, in <module>

### ISSUE THREAD

**Issue by gally16** [0-8-4/miui-auto-tasks#101]
`Traceback (most recent call last):
  File "miuitask.py", line 16, in <module>
    class MIUITask:
  File "miuitask.py", line 390, in MIUITask
    def get_point(self) -> tuple[Any, Any]:
TypeError: 'type' object is not subscriptable`

大佬帮看看是哪里设错了

**Comment by TardisXE** [comment]
能否提供完整日志或者系统环境及Python版本？

**Comment by 0-8-4** [comment]
我也觉得是 Python 版本

**Comment by gally16** [comment]
> 我也觉得是 Python 版本

> 能否提供完整日志或者系统环境及Python版本？


$ whereis python
python: /usr/bin/python3.8 /usr/lib/python3.9 /usr/lib/python2.7 /usr/lib/python3.8 /etc/python3.8 /usr/local/lib/python3.8

**Comment by gally16** [comment]
刚刚升级脚本貌似能跑了
-------set up dot net env-------
sh: syntax error: unexpected "("
/ql/config/config.sh: line 146: ddgyck: command not found
22:02:24 | MIUI-AUTO-TASK v1.6.0.1
22:02:24 | ---------- 系统信息 -------------
22:02:24 | 操作系统平台: Linux-5.9.0-rc7-aml-s812-armv7l-with
22:02:24 | 操作系统版本: #20.12 SMP Sun Dec 13 22:41:27 CST 2020
22:02:24 | 操作系统名称: Linux
22:02:24 | 操作系统位元: ('32bit', '')
22:02:24 | 操作系统类型: armv7l
22:02:24 | 处理器信息: 
22:02:24 | Python 版本: 3.8.10 ('default', 'May  6 2021 06:30:44')
22:02:24 | ---------- 项目信息 -------------
22:02:24 | 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
22:02:24 | 项目地址：https://github.com/0-8-4/miui-auto-tasks
22:02:24 | 欢迎 star，感谢東雲研究所中的大佬

**Comment by TardisXE** [comment]
感谢反馈，目前我们已确认在3.8中存在该问题。我提交的pull requests可以修正这个问题，如果没有其他问题它会在今晚被合并，等待合并后再更新即可

**Comment by TardisXE** [comment]
> 感谢反馈，目前我们已确认在3.8中存在该问题。我提交的pull requests可以修正这个问题，如果没有其他问题它会在今晚被合并，等待合并后再更新即可

已合并并发布Releases，请注意检查更新。再次感谢反馈问题
