### ISSUE TITLE
17:51:17 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> 17:51:17 | 小米账号登录成功，社区获取 Cookie 失败     

### ISSUE THREAD

**Issue by cuuemo** [0-8-4/miui-auto-tasks#103]
17:51:17 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
17:51:17 | 小米账号登录成功，社区获取 Cookie 失败

**Comment by TardisXE** [comment]
刚刚测试未能复现，对于SSL错误建议先检查网络上是否启用了过滤或代理

**Comment by TardisXE** [comment]
> 刚刚测试未能复现，对于SSL错误建议先检查网络上是否启用了过滤或代理

以及，如果是在其他设备部署的，建议检查设备中设置的时间

**Comment by JaHIY** [comment]
I have the same problem, and I have confirmed that the system time is correct.

```
$ python ./miuitask.py
13:10:27 | MIUI-AUTO-TASK v1.6.0.1
13:10:27 | ---------- 系统信息 -------------
13:10:27 | 操作系统平台: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.38
13:10:27 | 操作系统版本: #1 SMP Fri Jan 27 02:56:13 UTC 2023
13:10:27 | 操作系统名称: Linux
13:10:27 | 操作系统位元: ('64bit', 'ELF')
13:10:27 | 操作系统类型: x86_64
13:10:27 | 处理器信息:
13:10:27 | Python 版本: 3.11.5 ('main', 'Sep  2 2023 14:16:33')
13:10:27 | ---------- 项目信息 -------------
13:10:27 | 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
13:10:27 | 项目地址：https://github.com/0-8-4/miui-auto-tasks
13:10:27 | 欢迎 star，感谢東雲研究所中的大佬
13:10:27 | ---------- 配置检测 -------------
13:10:27 | 正在加载 /home/jahiy/github/miui-auto-tasks/config.yaml 配置文件
13:10:27 | 配置文件已成功加载，文件版本 v1.6.0
13:10:27 | ---------- EXECUTING -------------
13:11:28 | Remote end closed connection without response
13:11:28 | 小米账号登录成功，社区获取 Cookie 失败
```

**Comment by koolcandy** [comment]
如果是macOS系统得话,要运行“Install Certificates.command”
![截屏2023-11-10 00 14 11](https://github.com/0-8-4/miui-auto-tasks/assets/133551107/437a1d63-731a-4bf8-b2f1-faf11f1ed370)

**Comment by sbiubgwiurkj** [comment]
> I have the same problem, and I have confirmed that the system time is correct.
> 
> ```
> $ python ./miuitask.py
> 13:10:27 | MIUI-AUTO-TASK v1.6.0.1
> 13:10:27 | ---------- 系统信息 -------------
> 13:10:27 | 操作系统平台: Linux-5.15.90.1-microsoft-standard-WSL2-x86_64-with-glibc2.38
> 13:10:27 | 操作系统版本: #1 SMP Fri Jan 27 02:56:13 UTC 2023
> 13:10:27 | 操作系统名称: Linux
> 13:10:27 | 操作系统位元: ('64bit', 'ELF')
> 13:10:27 | 操作系统类型: x86_64
> 13:10:27 | 处理器信息:
> 13:10:27 | Python 版本: 3.11.5 ('main', 'Sep  2 2023 14:16:33')
> 13:10:27 | ---------- 项目信息 -------------
> 13:10:27 | 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
> 13:10:27 | 项目地址：https://github.com/0-8-4/miui-auto-tasks
> 13:10:27 | 欢迎 star，感谢東雲研究所中的大佬
> 13:10:27 | ---------- 配置检测 -------------
> 13:10:27 | 正在加载 /home/jahiy/github/miui-auto-tasks/config.yaml 配置文件
> 13:10:27 | 配置文件已成功加载，文件版本 v1.6.0
> 13:10:27 | ---------- EXECUTING -------------
> 13:11:28 | Remote end closed connection without response
> 13:11:28 | 小米账号登录成功，社区获取 Cookie 失败
> ```+1

**Comment by udcv** [comment]
+1

没开代理，自动校正时间

**Comment by 0-8-4** [comment]
> 如果是macOS系统得话,要运行“Install Certificates.command” ![截屏2023-11-10 00 14 11](https://user-images.githubusercontent.com/133551107/281796587-437a1d63-731a-4bf8-b2f1-faf11f1ed370.jpg)

我只是不太明白 为什么macOS会有这样的问题？我自己一直都是macOS 我都是直接用的啊

**Comment by TardisXE** [comment]
> > 如果是macOS系统得话,要运行“Install Certificates.command” ![截屏2023-11-10 00 14 11](https://user-images.githubusercontent.com/133551107/281796587-437a1d63-731a-4bf8-b2f1-faf11f1ed370.jpg)
> 
> 
> 
> 我只是不太明白 为什么macOS会有这样的问题？我自己一直都是macOS 我都是直接用的啊

macos确实有这个问题，需要信任证书

**Comment by YiChen2025** [comment]
> > 刚刚测试未能复现，对于SSL错误建议先检查网络上是否启用了过滤或代理
> 
> 以及，如果是在其他设备部署的，建议检查设备中设置的时间

人机验证怎么解决

**Comment by koolcandy** [comment]
> > > 刚刚测试未能复现，对于SSL错误建议先检查网络上是否启用了过滤或代理
> > 
> > 以及，如果是在其他设备部署的，建议检查设备中设置的时间
> 
> 人机验证怎么解决

打码平台

**Comment by YiChen2025** [comment]
> 刚刚测试未能复现，对于SSL错误建议先检查网络上是否启用了过滤或代理

打码平台是有，就是不知道怎么配置接入，有教程吗

**Comment by koolcandy** [comment]
> > 刚刚测试未能复现，对于SSL错误建议先检查网络上是否启用了过滤或代理
> 
> 打码平台是有，就是不知道怎么配置接入，有教程吗

为了该项目的安全，你需要自己找，可以看看 2captcha的python库，改下代码就好了

**Comment by YiChen2025** [comment]
有配置接入教程吗







------------------ 原始邮件 ------------------

发 件 人：koolcandy ***@***.***>

发送时间：2023-12-04 21:47:45

收 件 人：0-8-4/miui-auto-tasks ***@***.***>

抄 送：YiChen2025 ***@***.***>,Comment ***@***.***>

主 题：Re: [0-8-4/miui-auto-tasks] 17:51:17 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> 17:51:17 | 小米账号登录成功，社区获取 Cookie 失败 (Issue #103)







刚刚测试未能复现，对于SSL错误建议先检查网络上是否启用了过滤或代理

以及，如果是在其他设备部署的，建议检查设备中设置的时间

人机验证怎么解决

打码平台

**Comment by koolcandy** [comment]
> 
> 
> 
> 
> 
> 
> 有配置接入教程吗
> 
> 
> 
> 
> 
> 
> 
> ------------------ 原始邮件 ------------------
> 
> 发 件 人：koolcandy ***@***.***>
> 
> 发送时间：2023-12-04 21:47:45
> 
> 收 件 人：0-8-4/miui-auto-tasks ***@***.***>
> 
> 抄 送：YiChen2025 ***@***.***>,Comment ***@***.***>
> 
> 主 题：Re: [0-8-4/miui-auto-tasks] 17:51:17 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> 17:51:17 | 小米账号登录成功，社区获取 Cookie 失败 (Issue #103)
> 
> 
> 
> 
> 
> 
> 
> 刚刚测试未能复现，对于SSL错误建议先检查网络上是否启用了过滤或代理
> 
> 以及，如果是在其他设备部署的，建议检查设备中设置的时间
> 
> 人机验证怎么解决
> 
> 打码平台
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.Message ID: ***@***.***>
> 
> 
> 

不要在开源项目中讨论这些，可以进讨论组

**Comment by Adlyq** [comment]
@YiChen2025 为什么不试试万能的谷歌呢

**Comment by koolcandy** [comment]
@YiChen2025 1

**Comment by YiChen2025** [comment]
有配置接入打码平台的教程么




------------------ 原始邮件 ------------------

发 件 人：koolcandy ***@***.***>

发送时间：2023-12-04 22:33:19

收 件 人：0-8-4/miui-auto-tasks ***@***.***>

抄 送：YiChen2025 ***@***.***>,Mention ***@***.***>

主 题：Re: [0-8-4/miui-auto-tasks] 17:51:17 | <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)> 17:51:17 | 小米账号登录成功，社区获取 Cookie 失败 (Issue #103)







@YiChen2025 1

**Comment by Night-stars-1** [comment]
请遵守社区规则#228
不要讨论token
