### ISSUE TITLE
api过期无法调用

### ISSUE THREAD

**Issue by MarkJaneLX** [0-8-4/miui-auto-tasks#104]
现在使用会提示
20:29:19 | 账号登录完成
20:29:19 | 本脚本支持社区拔萝卜及成长值签到，因该功能存在风险默认禁用
20:29:19 | 如您愿意承担一切可能的后果，可编辑配置文件手动打开该功能
20:29:19 | 登录社区App成功
20:29:19 | 风险功能提示：正在进行成长值签到
20:29:20 | 社区成长值签到出错
20:29:20 | 'status'
20:29:20 | 正在完成浏览帖子10s任务，第一次
20:29:33 | 浏览帖子完成，成长值+1
20:29:33 | 正在完成浏览帖子10s任务，第二次
20:29:45 | 浏览帖子完成，但有错误：加分失败
20:29:45 | 正在完成浏览帖子10s任务，第三次
20:29:56 | 浏览帖子完成，但有错误：加分失败
20:29:56 | 正在完成点赞任务
20:29:56 | 签名原文：postId=36625780&timestamp=1699446596338
20:29:56 | 签名结果：ac4e80da9c62dfd766f89dcf9c4a1459
20:29:56 | 点赞成功
20:30:00 | 取消点赞出错
20:30:00 | Expecting value: line 1 column 1 (char 0)
20:30:02 | 签名原文：postId=36625780&timestamp=1699446602087
20:30:02 | 签名结果：47edd0b5895f4ff1953423fa15c91481
20:30:02 | 点赞成功
20:30:07 | 取消点赞出错
20:30:07 | Expecting value: line 1 column 1 (char 0)
20:30:09 | 签名原文：postId=36625780&timestamp=1699446609129
20:30:09 | 签名结果：a0585af8c2ac3678431d74c045b00e2e
20:30:09 | 点赞成功
20:30:15 | 取消点赞出错
20:30:15 | Expecting value: line 1 column 1 (char 0)
20:30:21 | 退出小米圈子出错
20:30:21 | 'status'
20:30:24 | 加入小米圈子出错
20:30:24 | 'status'
20:30:30 | 浏览个人主页完成，但有错误：加分失败
20:30:36 | 成长值获取失败

**Comment by TardisXE** [comment]
版本过低，请更新脚本

**Comment by MarkJaneLX** [comment]
> 版本过低，请更新脚本

在哪里更新呢？
