### ISSUE TITLE
[Feature] 我是腾讯云轻量云，请问怎么在上边先登录一遍小米社区呢？

### ISSUE THREAD

**Issue by shixiangkuangmo** [0-8-4/miui-auto-tasks#107]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 MIUITask 并不包含该功能特性或者还不完善
- [X] Framework 这是 MIUITask 应包含的特性, 并非实现社区外功能
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

我是腾讯云轻量云，请问怎么在上边先登录一遍小米社区呢？
现在总是提示需要验证码

### Describe the Solution

我是腾讯云轻量云，请问怎么在上边先登录一遍小米社区呢？
现在总是提示需要验证码

**Comment by TardisXE** [comment]
如果是 Windows 直接安装使用浏览器登录一遍小米社区就好，如果机器是其他系统并且不方便重装，你可以连接使用VPN变成服务器的IP来登录。或者有个折衷的办法是开一台按量付费的同地域Windows服务器，花几毛钱来登录一下再看看脚本能不能正常执行，根据风控情况可能需要多登录几次，按量付费服务器用完记得及时销毁。

**Comment by shixiangkuangmo** [comment]
嗯 感谢 我打算再试试搭建个v2试试

**Comment by Pandaver** [comment]
如果装了docker的话可以创建个[jlesage/firefox](https://github.com/jlesage/docker-firefox)容器，访问ip:5800就可以通过网页使用服务器的Firefox，相当于通过浏览器访问服务器上的浏览器访问网页
```
docker run -d \
    --name=xiaomi \
    -p 5800:5800 \
    -v /docker/appdata/firefox/xiaomi:/config:rw \
    -e LANG=zh_CN.UTF-8 \
    -e TZ=Asia/Shanghai \
    -e FF_OPEN_URL=https://account.xiaomi.com \
    -e FF_KIOSK=1 \
    jlesage/firefox
```
![截图_20231110130934](https://github.com/0-8-4/miui-auto-tasks/assets/62326552/33f3f5ef-fb69-4158-bcee-805bf2699e2d)

**Comment by shixiangkuangmo** [comment]
> 如果装了docker的话可以创建个[jlesage/firefox](https://github.com/jlesage/docker-firefox)容器，访问ip:5800就可以通过网页使用服务器的Firefox，相当于通过浏览器访问服务器上的浏览器访问网页
> 
> ```
> docker run -d \
>     --name=xiaomi \
>     -p 5800:5800 \
>     -v /docker/appdata/firefox/xiaomi:/config:rw \
>     -e LANG=zh_CN.UTF-8 \
>     -e TZ=Asia/Shanghai \
>     -e FF_OPEN_URL=https://account.xiaomi.com \
>     -e FF_KIOSK=1 \
>     jlesage/firefox
> ```
> 
> ![截图_20231110130934](https://user-images.githubusercontent.com/62326552/281963809-33f3f5ef-fb69-4158-bcee-805bf2699e2d.png)

非常感谢，成功了！

**Comment by devyangbw** [comment]
> 如果装了docker的话可以创建个[jlesage/firefox](https://github.com/jlesage/docker-firefox)容器，访问ip:5800就可以通过网页使用服务器的Firefox，相当于通过浏览器访问服务器上的浏览器访问网页
> 
> ```
> docker run -d \
>     --name=xiaomi \
>     -p 5800:5800 \
>     -v /docker/appdata/firefox/xiaomi:/config:rw \
>     -e LANG=zh_CN.UTF-8 \
>     -e TZ=Asia/Shanghai \
>     -e FF_OPEN_URL=https://account.xiaomi.com \
>     -e FF_KIOSK=1 \
>     jlesage/firefox
> ```
> 
> ![截图_20231110130934](https://user-images.githubusercontent.com/62326552/281963809-33f3f5ef-fb69-4158-bcee-805bf2699e2d.png)

Error response from daemon: oci runtime error: container_linux.go:290: starting container process caused "process_linux.go:340: running prestart hook 2 caused \"error running hook: exit status 1, stdout: , stderr: \"".
 请问这种报错是什么情况呢
