### ISSUE TITLE
脚本运行每日签到时失败

### ISSUE THREAD

**Issue by wcy436** [0-8-4/miui-auto-tasks#113]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

1.6.0.1

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.1

### Describe the Bug

请升级至新版小米社区参加签到活动!

### MIUITask Log

16:15:43 | 模拟请求「每日签到」
16:15:45 | 每日签到失败：请升级至新版小米社区参加签到活动!

### Screenshots

<img width="389" alt="miui" src="https://github.com/0-8-4/miui-auto-tasks/assets/68768502/eeeeb5d5-6a7a-45da-9a96-d5653a3373cb">

**Comment by bhshuya** [comment]
+1 同样的问题
