### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by koolcandy** [0-8-4/miui-auto-tasks#117]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v16.0.1

### Bug Found in Environment

macOS

### Bug Found in Python Version

3.12

### Describe the Bug

配置文件写了
board-follow: true
carrot-pull: true
但还是
00:10:58 | 自动跳过模拟请求「浏览指定专题页」
00:10:58 | 自动跳过模拟请求「加入小米社区圈子」

### MIUITask Log

00:10:57 | ---------- 项目信息 -------------
00:10:57 | 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
00:10:57 | 项目地址：https://github.com/0-8-4/miui-auto-tasks
00:10:57 | 欢迎 star，感谢東雲研究所中的大佬
00:10:57 | ---------- 配置检测 -------------
00:10:57 | 正在加载 /Users/hitt/Documents/miui-auto-tasks-master/config.yaml 配置文件
00:10:57 | 配置文件已成功加载，文件版本 v1.6.0
00:10:57 | ---------- EXECUTING -------------
00:10:58 | 账号登录完成
00:10:58 | 本脚本用于模拟网络请求测试，仅供测试学习使用，禁止用于其他用途
00:10:58 | 本脚本默认不做任何操作，如您愿意承担一切可能的后果，可编辑配置文件手动打开需要的功能
00:10:58 | 为避免重复模拟请求，脚本将自动获取状态并决定是否继续模拟网络请求
00:10:58 | 登录社区成功
00:10:58 | 获取到信息: 抢先体验小米澎湃OS！, 未完成
00:10:58 | 获取到信息: 每日签到, 完成
00:10:58 | 获取到信息: 浏览帖子超过10秒, 完成
00:10:58 | 获取到信息: 点赞他人帖子, 完成
00:10:58 | 获取到信息: 了解小米澎湃OS新特性, 未完成
00:10:58 | 自动跳过模拟请求「每日签到」
00:10:58 | 自动跳过模拟请求「浏览帖子超过10秒」
00:10:58 | 自动跳过模拟请求「浏览个人/他人主页超过10秒」
00:10:58 | 自动跳过模拟请求「点赞他人帖子」
00:10:58 | 自动跳过模拟请求「浏览指定专题页」
00:10:58 | 自动跳过模拟请求「加入小米社区圈子」
00:10:58 | 请注意，未在配置文件启用或不需要执行的功能请求将被自动跳过，且不会支持“灌水”的功能
00:10:58 | 模拟请求「社区拔萝卜」
00:11:01 | 社区拔萝卜结果：今天已经很累了，明天再来吧~
00:11:01 | 当前金币数：16
00:11:09 | 当前等级：4段, 当前成长值：625

### MIUITask Config

```shell
accounts:
  - uid: 
    # 账户ID 非账户用户名或手机号
    password: 
    # 账户密码或其MD5哈希
    user-agent: 'Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Safari/537.36'
    # 登录社区时所用浏览器的 User-Agent
    # 可在此工具查看：https://tool.chinaz.com/useragent
    
    # 功能开关
    check-in: true
    # 社区成长值签到，启用功能意味着你愿意自行承担相关风险
    browse-user-page: true
    # 社区浏览个人主页10秒，启用功能意味着你愿意自行承担相关风险
    browse-post: true
    # 社区浏览帖子10秒，启用功能意味着你愿意自行承担相关风险
    thumb-up: true
    # 点赞帖子，启用功能意味着你愿意自行承担相关风险
    browse-specialpage: true
    # 社区在活动期间可能会出现限时的“浏览指定专题页”任务，启用功能意味着你愿意自行承担相关风险
    board-follow: true
    # 社区可能会出现限时的“加入圈子”任务，启用功能意味着你愿意自行承担相关风险
    carrot-pull: true
    # 社区拔萝卜，启用功能意味着你愿意自行承担相关风险

ONEPUSH:
  notifier: telegram
  params:
    title:
    markdown: false
    token:
    userid:

logging: true
# 归档日志到本地文件
version: v1.6.0
# config 文件版本号，debug用
```

### Screenshots

![截屏2023-11-10 00 22 17](https://github.com/0-8-4/miui-auto-tasks/assets/133551107/c7841496-5a53-4139-b955-0492e03b85fa)

**Comment by doge1837** [comment]
都没这个任务了当然跳过了
