### ISSUE TITLE
[Bug] 修复签到失败提示更新app版本的情况

### ISSUE THREAD

**Issue by PsalmReimu** [0-8-4/miui-auto-tasks#119]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.1

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.7

### Describe the Bug

将
https://api.vip.miui.com/mtop/planet/vip/user/checkin?pathname=/mio/checkIn&version=dev.1144
替换为
https://api.vip.miui.com/mtop/planet/vip/user/checkinV2?ref=vipAccountShortcut&pathname=/mio/checkIn&version=dev.231026
即可解决

### MIUITask Log

ok。。。。。。。。。。。。。。。。。。。。。

**Comment by 0-8-4** [comment]
这不是在最新的pr 中已经合了么？只是后期还有commit 正在路上，所以还没发布新的release

**Comment by PsalmReimu** [comment]
抱歉没注意，今天中午下载的release版本

**Comment by Amadeusssssss** [comment]
感谢你的issue（我也没注意commit（（非常好issue，爱来自酷安
顺便你的Describe少看了一行，get也换post了

**Comment by 0-8-4** [comment]
> 抱歉没注意，今天中午下载的release版本

不用不好意思，非常感谢你提issues。我今晚一只没空去看pr，一直在收拾行李，明天要溜了。明天起来在机场看😅
