### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by 972513547** [0-8-4/miui-auto-tasks#121]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 MIUITask 并不包含该功能特性或者还不完善
- [X] Framework 这是 MIUITask 应包含的特性, 并非实现社区外功能
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

你好请问如何配置推送信息呢，青龙面板配置成功后并不会有任何的推送

### Describe the Solution

a

**Comment by Dystnine** [comment]
推送好像走telegram

**Comment by TardisXE** [comment]
推送基于onepush

推送名称 / notifier: bark

参数大全 / params: {'required': ['key'], 'optional': ['title', 'sound', 'isarchive', 'icon', 'group', 'url', 'copy', 'autocopy']}

推送名称 / notifier: custom

参数大全 / params: {'required': ['url'], 'optional': ['method', 'datatype', 'data']}

推送名称 / notifier: dingtalk

参数大全 / params: {'required': ['token'], 'optional': ['title', 'secret', 'markdown']}

推送名称 / notifier: discord

参数大全 / params: {'required': ['webhook'], 'optional': ['title', 'username', 'avatar_url', 'color']}

推送名称 / notifier: pushplus

参数大全 / params: {'required': ['token'], 'optional': ['title', 'topic', 'markdown']}

推送名称 / notifier: qmsg

参数大全 / params: {'required': ['key'], 'optional': ['title', 'mode', 'qq']}

推送名称 / notifier: serverchan

参数大全 / params: {'required': ['sckey', 'title'], 'optional': []}

推送名称 / notifier: serverchanturbo

参数大全 / params: {'required': ['sctkey', 'title'], 'optional': ['channel', 'openid']}

推送名称 / notifier: telegram

参数大全 / params: {'required': ['token', 'userid'], 'optional': ['title', 'api_url']}

推送名称 / notifier: wechatworkapp

参数大全 / params: {'required': ['corpid', 'corpsecret', 'agentid'], 'optional': ['title', 'touser', 'markdown']}

推送名称 / notifier: wechatworkbot

参数大全 / params: {'required': ['key'], 'optional': ['title', 'markdown']}

required为必填参数，optional为选填参数
配置参考：

ONEPUSH:
  notifier: telegram
  params:
    title: 
    markdown: false
    token: 123456789:XXXXXXXXXXXXXXXXXXXXXXXX
    userid: 114514
 ONEPUSH:
  notifier: pushplus
  params:
    title: 
    token: XXXXXXXXXXXXXXXXXXXXXXXX
    markdown: false

**Comment by 972513547** [comment]
notifier: pushplus
params:
title:
token: XXXXXXXXXXXXXXXXXXXXXXXX
markdown: false


按照这个配置完毕后他不会有任何输出信息和推送，我使用的是青龙面板 
如果要是telegram的话那就是403

**Comment by TardisXE** [comment]
> notifier: pushplus
> 
> params:
> 
> title:
> 
> token: XXXXXXXXXXXXXXXXXXXXXXXX
> 
> markdown: false
> 
> 
> 
> 
> 
> 按照这个配置完毕后他不会有任何输出信息和推送，我使用的是青龙面板 
> 
> 如果要是telegram的话那就是403

在配置文件中配置正确的onepush，telegram在某些网络环境下无法连接，你可以使用dingtalk或者serverchan

**Comment by 972513547** [comment]
serverchan 已经配置成功了感谢
