### ISSUE TITLE
[Feature] 添加了解小米澎湃OS新特性限时任务

### ISSUE THREAD

**Issue by Dystnine** [0-8-4/miui-auto-tasks#122]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 MIUITask 并不包含该功能特性或者还不完善
- [X] Framework 这是 MIUITask 应包含的特性, 并非实现社区外功能
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

希望添加了解小米澎湃OS新特性的限时任务

### Describe the Solution

希望添加了解小米澎湃OS新特性的限时任务，就是浏览页面10s

**Comment by TardisXE** [comment]
该功能已在v1.6.0.2优化支持，确认后请关闭issue
