### ISSUE TITLE
Docker部署签到出现问题[Bug] 

### ISSUE THREAD

**Issue by Duan-rax** [0-8-4/miui-auto-tasks#126]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.1

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.9

### Describe the Bug

每日签到失败：请升级至新版小米社区参加签到活动!

### MIUITask Log

每日签到失败：请升级至新版小米社区参加签到活动!

### MIUITask Config

```shell
每日签到失败：请升级至新版小米社区参加签到活动!
```

### Screenshots

每日签到失败：请升级至新版小米社区参加签到活动!

**Comment by Duan-rax** [comment]
更新镜像后出现：
每日签到失败：人机校验失败

**Comment by TardisXE** [comment]
参见 #118 ，小米社区已经加强了人机验证，建议在常用ip地使用，在我们解决前如果依然失败请先禁用签到功能

**Comment by shixiangkuangmo** [comment]
> 参见 #118 ，小米社区已经加强了人机验证，建议在常用ip地使用，在我们解决前如果依然失败请先禁用签到功能

人机验证能用dddocr识别吗

**Comment by zhangyupy** [comment]
建议使用Windows server 稳定
