### ISSUE TITLE
[Bug] Server酱微信推送的消息详情不换行

### ISSUE THREAD

**Issue by Amadeusssssss** [0-8-4/miui-auto-tasks#128]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.1

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.11

### Describe the Bug

Server酱微信推送的消息详情不换行，见Screenshots。不太确定是本项目的问题还是Server酱的问题。

尝试修改notity.py的serverJ()方法（293行）：
`data = {"text": title, "desp": content.replace("\n", "\n\n")}    #原版`
`data = {"text": title, "desp": content.replace("\n", " \n\n ")}   #前后加空格`
`data = {"text": title, "desp": content.replace("\n", "%0D%0A%0D%0A")}    #死马当活马医`
均无效。

瞎猜可能是未在content中找到"\n"转义符所致。

查到了相同的问题：
https://www.522ip.com/index.php/archives/28/
https://www.cnblogs.com/1394htw/p/10196470.html

## 开始执行... 2023-11-10 01:57:07

01:57:07 | MIUI-AUTO-TASK v1.6.0.1
01:57:07 | ---------- 系统信息 -------------
01:57:07 | 操作系统平台: Linux-3.10.0-957.el7.x86_64-x86_64-with
01:57:07 | 操作系统版本: #1 SMP Thu Nov 8 23:39:32 UTC 2018
01:57:07 | 操作系统名称: Linux
01:57:07 | 操作系统位元: ('64bit', '')
01:57:07 | 操作系统类型: x86_64
01:57:07 | 处理器信息: 
01:57:07 | Python 版本: 3.10.13 ('main', 'Oct 19 2023 06:08:04')
01:57:07 | 系统代理: {'no': 'localhost,127.0.0.0/8,::1'}
01:57:07 | ---------- 项目信息 -------------
01:57:07 | 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
01:57:07 | 项目地址：https://github.com/0-8-4/miui-auto-tasks
01:57:07 | 欢迎 star，感谢東雲研究所中的大佬
01:57:07 | ---------- 配置检测 -------------
01:57:07 | 正在加载 /ql/data/scripts/0-8-4_miui-auto-tasks_master/config.yaml 配置文件
01:57:07 | 配置文件已成功加载，文件版本 v1.6.0
01:57:07 | ---------- EXECUTING -------------
01:57:07 | 账号登录完成
01:57:07 | 本脚本用于模拟网络请求测试，仅供测试学习使用，禁止用于其他用途
01:57:07 | 本脚本默认不做任何操作，如您愿意承担一切可能的后果，可编辑配置文件手动打开需要的功能
01:57:07 | 为避免重复模拟请求，脚本将自动获取状态并决定是否继续模拟网络请求
01:57:08 | 登录社区成功
01:57:08 | 获取到信息: 抢先体验小米澎湃OS！, 未完成
01:57:08 | 获取到信息: 每日签到, 完成
01:57:08 | 获取到信息: 浏览帖子超过10秒, 未完成
01:57:08 | 获取到信息: 点赞他人帖子, 未完成
01:57:08 | 获取到信息: 了解小米澎湃OS新特性, 未完成
01:57:08 | 自动跳过模拟请求「每日签到」
01:57:08 | 自动跳过模拟请求「浏览帖子超过10秒」
01:57:08 | 自动跳过模拟请求「浏览个人/他人主页超过10秒」
01:57:08 | 自动跳过模拟请求「点赞他人帖子」
01:57:08 | 自动跳过模拟请求「浏览指定专题页」
01:57:08 | 自动跳过模拟请求「加入小米社区圈子」
01:57:08 | 请注意，未在配置文件启用或不需要执行的功能请求将被自动跳过，且不会支持“灌水”的功能
01:57:13 | 当前等级：3段, 当前成长值：431

### MIUITask Config

```shell
ONEPUSH:
  notifier: serverchan
  params:
    sckey: XXXXXXXXXXXXXXXXXXXX
    title: 小米社区自动签到
```

### Screenshots

![图片](https://github.com/0-8-4/miui-auto-tasks/assets/45653884/7a519e7a-a1cb-4db2-8bc2-b484acd68f69)

**Comment by 603185423** [comment]
在utils.notify_me中, 替换使用`"\n\n"`能够正常换行

`push_content = content.replace("\n", "\n\n")`

windows和ubuntu下均测试正常
![Screenshot_2023-11-14-19-14-23-721_com ftqq sct m](https://github.com/0-8-4/miui-auto-tasks/assets/50170900/373579ca-06fe-457c-99d0-c95cc5468711)
![Screenshot_2023-11-14-19-14-28-568_com ftqq sct m](https://github.com/0-8-4/miui-auto-tasks/assets/50170900/805b02be-f495-44f9-96e4-b973f008adef)

**Comment by e8xl** [comment]
最新[Release](https://github.com/0-8-4/miui-auto-tasks/releases/tag/v1.6.0.3)版本
将miuitask.py中的146行
`content = message`
改为
`content = message.replace("\n", "\n\n")`
Windows环境测试可行

**Comment by Amadeusssssss** [comment]
> 在utils.notify_me中, 替换使用`"\n\n"`能够正常换行

没有找到这个方法，是我搞错姿势了吗

**Comment by 603185423** [comment]
> > 在utils.notify_me中, 替换使用`"\n\n"`能够正常换行
> 
> 没有找到这个方法，是我搞错姿势了吗

我发的这个是上个版本的，新版本的你看看我下面的那条

**Comment by Amadeusssssss** [comment]
> 最新[Release](https://github.com/0-8-4/miui-auto-tasks/releases/tag/v1.6.0.3)版本 将miuitask.py中的146行 `content = message` 改为 `content = message.replace("\n", "\n\n")` Windows环境测试可行



> 最新[Release](https://github.com/0-8-4/miui-auto-tasks/releases/tag/v1.6.0.3)版本 将miuitask.py中的146行 `content = message` 改为 `content = message.replace("\n", "\n\n")` Windows环境测试可行

没有在miui-auto-tasks-1.6.0.3/miuitask.py里找到这一句

**Comment by Amadeusssssss** [comment]
> 最新[Release](https://github.com/0-8-4/miui-auto-tasks/releases/tag/v1.6.0.3)版本 将miuitask.py中的146行 `content = message` 改为 `content = message.replace("\n", "\n\n")` Windows环境测试可行

没有在miui-auto-tasks-1.6.0.3/miuitask.py里找到这一句

**Comment by e8xl** [comment]
> > 最新[Release](https://github.com/0-8-4/miui-auto-tasks/releases/tag/v1.6.0.3)版本 将miuitask.py中的146行 `content = message` 改为 `content = message.replace("\n", "\n\n")` Windows环境测试可行
> 
> 没有在miui-auto-tasks-1.6.0.3/miuitask.py里找到这一句

第146行的内容确实如此啊 你的miuitask.py内容是什么样子的

**Comment by Amadeusssssss** [comment]
> > > 最新[Release](https://github.com/0-8-4/miui-auto-tasks/releases/tag/v1.6.0.3)版本 将miuitask.py中的146行 `content = message` 改为 `content = message.replace("\n", "\n\n")` Windows环境测试可行
> > 
> > 
> > 没有在miui-auto-tasks-1.6.0.3/miuitask.py里找到这一句
> 
> 第146行的内容确实如此啊 你的miuitask.py内容是什么样子的

就是[Releases](https://github.com/0-8-4/miui-auto-tasks/releases) v1.6.0.3里解压出来的，挠头。

**Comment by Amadeusssssss** [comment]
> > > 在utils.notify_me中, 替换使用`"\n\n"`能够正常换行
> > 
> > 
> > 没有找到这个方法，是我搞错姿势了吗
> 
> 我发的这个是上个版本的，新版本的你看看我下面的那条

根据你的提示，尝试修改了miui-auto-tasks-1.6.0.3/utils/utils.py的notify_me(content=None)方法。
146行的 `content = message` 修改为`content = message.replace("\n", "\n\n")`。
推送正常换行了。


----------


> > > > 最新[Release](https://github.com/0-8-4/miui-auto-tasks/releases/tag/v1.6.0.3)版本 将miuitask.py中的146行 `content = message` 改为 `content = message.replace("\n", "\n\n")` Windows环境测试可行
> > > 
> > > 
> > > 没有在miui-auto-tasks-1.6.0.3/miuitask.py里找到这一句
> > 
> > 
> > 第146行的内容确实如此啊 你的miuitask.py内容是什么样子的
> 
> 就是[Releases](https://github.com/0-8-4/miui-auto-tasks/releases) v1.6.0.3里解压出来的，挠头。

你说的应该是这个方法吧，我这边不在miuitask.py里。

**Comment by e8xl** [comment]
> > > > 最新[Release](https://github.com/0-8-4/miui-auto-tasks/releases/tag/v1.6.0.3)版本 将miuitask.py中的146行 `content = message` 改为 `content = message.replace("\n", "\n\n")` Windows环境测试可行
> > > 
> > > 
> > > 没有在miui-auto-tasks-1.6.0.3/miuitask.py里找到这一句
> > 
> > 
> > 第146行的内容确实如此啊 你的miuitask.py内容是什么样子的
> 
> 就是[Releases](https://github.com/0-8-4/miui-auto-tasks/releases) v1.6.0.3里解压出来的，挠头。



> > > > 在utils.notify_me中, 替换使用`"\n\n"`能够正常换行
> > > 
> > > 
> > > 没有找到这个方法，是我搞错姿势了吗
> > 
> > 
> > 我发的这个是上个版本的，新版本的你看看我下面的那条
> 
> 根据你的提示，尝试修改了miui-auto-tasks-1.6.0.3/utils/utils.py的notify_me(content=None)方法。 146行的 `content = message` 修改为`content = message.replace("\n", "\n\n")`。 推送正常换行了。
> 
> > > > > 最新[Release](https://github.com/0-8-4/miui-auto-tasks/releases/tag/v1.6.0.3)版本 将miuitask.py中的146行 `content = message` 改为 `content = message.replace("\n", "\n\n")` Windows环境测试可行
> > > > 
> > > > 
> > > > 没有在miui-auto-tasks-1.6.0.3/miuitask.py里找到这一句
> > > 
> > > 
> > > 第146行的内容确实如此啊 你的miuitask.py内容是什么样子的
> > 
> > 
> > 就是[Releases](https://github.com/0-8-4/miui-auto-tasks/releases) v1.6.0.3里解压出来的，挠头。
> 
> 你说的应该是这个方法吧，我这边不在miuitask.py里。

是这样的 我是用全局搜索的content变量 没看清文件名; （
找到了就好 希望作者可以尽快修复

**Comment by 603185423** [comment]
> > > > 在utils.notify_me中, 替换使用`"\n\n"`能够正常换行
> > > 
> > > 
> > > 没有找到这个方法，是我搞错姿势了吗
> > 
> > 我发的这个是上个版本的，新版本的你看看我下面的那条
> 
> 根据你的提示，尝试修改了miui-auto-tasks-1.6.0.3/utils/utils.py的notify_me(content=None)方法。
> 146行的 `content = message` 修改为`content = message.replace("\n", "\n\n")`。
> 推送正常换行了。
> 
> 
> ----------
> 
> 
> > > > > 最新[Release](https://github.com/0-8-4/miui-auto-tasks/releases/tag/v1.6.0.3)版本 将miuitask.py中的146行 `content = message` 改为 `content = message.replace("\n", "\n\n")` Windows环境测试可行
> > > > 
> > > > 
> > > > 没有在miui-auto-tasks-1.6.0.3/miuitask.py里找到这一句
> > > 
> > > 
> > > 第146行的内容确实如此啊 你的miuitask.py内容是什么样子的
> > 
> > 就是[Releases](https://github.com/0-8-4/miui-auto-tasks/releases) v1.6.0.3里解压出来的，挠头。
> 
> 你说的应该是这个方法吧，我这边不在miuitask.py里。

应该跟我说的一样 在utils里（
