### ISSUE TITLE
更新/ql/data/repo/0-8-4_miui-auto-tasks_master失败，请检查网络...[Bug] 

### ISSUE THREAD

**Issue by devyangbw** [0-8-4/miui-auto-tasks#131]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.1

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.7

### Describe the Bug

使用青龙面板添加订阅之后，手动运行一次报错，提示【更新/ql/data/repo/0-8-4_miui-auto-tasks_master失败，请检查网络...[Bug] 】，尝试多次依然如此

## 开始执行... 2023-11-10 16:44:34

开始克隆仓库 https://github.com/0-8-4/miui-auto-tasks.gitql repo https://github.com/0-8-4/miui-auto-tasks.git miuitask utils|init utils|config master py|yaml 到 /ql/data/repo/0-8-4_miui-auto-tasks_master

fatal: Too many arguments.

usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
    --reject-shallow      don't clone shallow repository
    -n, --no-checkout     don't create a checkout
    --bare                create a bare repository
    --mirror              create a mirror repository (implies bare)
    -l, --local           to clone from a local repository
    --no-hardlinks        don't use local hardlinks, always copy
    -s, --shared          setup as shared repository
    --recurse-submodules[=<pathspec>]
                          initialize submodules in the clone
    --recursive ...       alias of --recurse-submodules
    -j, --jobs <n>        number of submodules cloned in parallel
    --template <template-directory>
                          directory from which templates will be used
    --reference <repo>    reference repository
    --reference-if-able <repo>
                          reference repository
    --dissociate          use --reference only while cloning
    -o, --origin <name>   use <name> instead of 'origin' to track upstream
    -b, --branch <branch>
                          checkout <branch> instead of the remote's HEAD
    -u, --upload-pack <path>
                          path to git-upload-pack on the remote
    --depth <depth>       create a shallow clone of that depth
    --shallow-since <time>
                          create a shallow clone since a specific time
    --shallow-exclude <revision>
                          deepen history of shallow clone, excluding rev
    --single-branch       clone only one branch, HEAD or --branch
    --no-tags             don't clone any tags, and make later fetches not to follow them
    --shallow-submodules  any cloned submodules will be shallow
    --separate-git-dir <gitdir>
                          separate git dir from working tree
    -c, --config <key=value>
                          set config inside the new repository
    --server-option <server-specific>
                          option to transmit
    -4, --ipv4            use IPv4 addresses only
    -6, --ipv6            use IPv6 addresses only
    --filter <args>       object filtering
    --also-filter-submodules
                          apply partial clone filters to submodules
    --remote-submodules   any cloned submodules will use their remote-tracking branch
    --sparse              initialize sparse-checkout file to include only files at root
    --bundle-uri <uri>    a URI for downloading bundles before fetching from origin remote

更新/ql/data/repo/0-8-4_miui-auto-tasks_master失败，请检查网络...

**Comment by koolcandy** [comment]
网络问题吧

**Comment by kazsy** [comment]
还能使用吗？不是停止使用了吗
？

**Comment by gradypark86** [comment]
> 开始克隆仓库 https://github.com/0-8-4/miui-auto-tasks.gitql repo https://github.com/0-8-4/miui-auto-tasks.git miuitask utils|init utils|config master py|yaml 到 /ql/data/repo/0-8-4_miui-auto-tasks_master

外加

> fatal: Too many arguments.

检查一下你订阅里填写的链接吧。

`ql repo https://github.com/0-8-4/miui-auto-tasks.git miuitask utils|init utils|config master py|yaml` 是应该填写到订阅的“名称”里的，不是“链接”。

**Comment by renzcu** [comment]
网络错误大概率需要提子，手动下载放上去把

**Comment by devyangbw** [comment]
> > 开始克隆仓库 https://github.com/0-8-4/miui-auto-tasks.gitql repo https://github.com/0-8-4/miui-auto-tasks.git miuitask utils|init utils|config master py|yaml 到 /ql/data/repo/0-8-4_miui-auto-tasks_master
> 
> 外加
> 
> > fatal: Too many arguments.
> 
> 检查一下你订阅里填写的链接吧。
> 
> `ql repo https://github.com/0-8-4/miui-auto-tasks.git miuitask utils|init utils|config master py|yaml` 是应该填写到订阅的“名称”里的，不是“链接”。

确实粘贴错了，我的问题，感谢
