### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Wcoom** [0-8-4/miui-auto-tasks#132]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.2

### Bug Found in Environment

Linux, Docker

### Bug Found in Python Version

3.1

### Describe the Bug

签到人机检验

### MIUITask Log

miuitask.py
## 开始执行... 2023-11-11 01:29:13

01:29:14 | MIUI-AUTO-TASK v1.6.0.2
01:29:14 | ---------- 系统信息 -------------
01:29:14 | 操作系统平台: Linux-5.15.0-87-generic-x86_64-with
01:29:14 | 操作系统版本: #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023
01:29:14 | 操作系统名称: Linux
01:29:14 | 操作系统位元: ('64bit', '')
01:29:14 | 操作系统类型: x86_64
01:29:14 | 处理器信息: 
01:29:14 | Python 版本: 3.10.13 ('main', 'Oct 19 2023 06:08:04')
01:29:14 | ---------- 项目信息 -------------
01:29:14 | 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
01:29:14 | 项目地址：https://github.com/0-8-4/miui-auto-tasks
01:29:14 | 欢迎 star，感谢東雲研究所中的大佬
01:29:14 | ---------- 配置检测 -------------
01:29:14 | 正在加载 /ql/data/scripts/0-8-4_miui-auto-tasks/config.yaml 配置文件
01:29:14 | 配置文件已成功加载，文件版本 v1.6.0
01:29:14 | ---------- EXECUTING -------------
01:29:16 | 账号登录完成
01:29:16 | 本脚本用于模拟网络请求测试，仅供测试学习使用，禁止用于其他用途
01:29:16 | 本脚本默认不做任何操作，如您愿意承担一切可能的后果，可编辑配置文件手动打开需要的功能
01:29:16 | 为避免重复模拟请求，脚本将自动获取状态并决定是否继续模拟网络请求
01:29:17 | 登录社区成功
01:29:18 | 获取到信息: 抢先体验小米澎湃OS！, 未完成, 描述: 火热进行中
01:29:18 | 获取到信息: 每日签到, 未完成, 描述: 签到奖励随机，以实际获得为准
01:29:18 | 获取到信息: 浏览帖子超过10秒, 未完成, 描述: 每次成长值+1，每日上限1分
01:29:18 | 获取到信息: 点赞他人帖子, 未完成, 描述: 每次成长值+1，每日上限1分
01:29:18 | 模拟请求「每日签到」
01:29:29 | 每日签到失败：人机校验失败
01:29:29 | 自动跳过模拟请求「浏览帖子超过10秒」
01:29:29 | 自动跳过模拟请求「浏览个人/他人主页超过10秒」
01:29:29 | 自动跳过模拟请求「点赞他人帖子」
01:29:29 | 自动跳过模拟请求「None」
01:29:29 | 自动跳过模拟请求「加入小米社区圈子」
01:29:29 | 请注意，未在配置文件启用或不需要执行的功能请求将被自动跳过，且不会支持“灌水”的功能
01:29:33 | 当前等级：3段, 当前成长值：296

### MIUITask Config

```shell
accounts:
  - uid: 
    password: 
    user-agent: '
    check-in: true
    browse-user-page: true
    browse-post: false
    thumb-up: false
    browse-specialpage: false
    board-follow: false
    carrot-pull: false
ONEPUSH:
  notifier: telegram
  params:
    title:
    markdown: false
    token:
    userid:
logging: false
version: v1.6.0
```

### Screenshots

![image](https://github.com/0-8-4/miui-auto-tasks/assets/105034279/7cae1ebf-4533-4892-8249-bdbe872f2651)

**Comment by TardisXE** [comment]
已有类似issue

参见 #118 ，小米社区已经加强了人机验证，建议在常用ip地使用，在我们解决前如果依然失败请先禁用签到功能
