### ISSUE TITLE
更新是不是直接替换miuitask这个文件就可以了

### ISSUE THREAD

**Issue by kennylee60** [0-8-4/miui-auto-tasks#14]
更新是不是直接替换miuitask这个文件就可以了

**Comment by TardisXE** [comment]
是的，注意提前复制好之前脚本的登录信息，另外1.2.2后的版本还需要在同一个文件夹下放入system_info.py文件才能正常运行

**Comment by 0-8-4** [comment]
Link to #15

**Comment by 0-8-4** [comment]
@kennylee60 Check this #19
