### ISSUE TITLE
[Feature] 编译二进制文件吧，最新版termux下无法使用，orjson安装失败

### ISSUE THREAD

**Issue by mymine** [0-8-4/miui-auto-tasks#142]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 MIUITask 并不包含该功能特性或者还不完善
- [X] Framework 这是 MIUITask 应包含的特性, 并非实现社区外功能
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

最新版termux下无法使用，orjson安装失败。

### Describe the Solution

编译二进制文件

**Comment by Night-stars-1** [comment]
怎么平台的，可以把orjson换成json

**Comment by zixijian** [comment]
pkg install rust 即可

**Comment by mymine** [comment]
> 怎么平台的，可以把orjson换成json

arm64-v8a手机。

**Comment by mymine** [comment]
> pkg install rust 即可

还是不行
 $ python miuitask.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/miui/miuitask.py", line 8, in <module>
    from utils.api.login import Login
  File "/data/data/com.termux/files/home/miui/utils/api/login.py", line 6, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'

**Comment by Night-stars-1** [comment]
> > 怎么平台的，可以把orjson换成json
> 
> arm64-v8a手机。

行吧，晚点发你一份我编译好的

**Comment by Night-stars-1** [comment]
编译后的文件

https://raw.githubusercontent.com/Night-stars-1/miui-auto-tasks/main/miuitask

**Comment by mymine** [comment]
> 编译后的文件
> 
> https://raw.githubusercontent.com/Night-stars-1/miui-auto-tasks/main/miuitask

写个actions移动编译吧。不然每次更新都要麻烦你。太麻烦了😂

**Comment by Night-stars-1** [comment]
> > 编译后的文件
> > https://raw.githubusercontent.com/Night-stars-1/miui-auto-tasks/main/miuitask
> 
> 写个actions移动编译吧。不然每次更新都要麻烦你。太麻烦了😂

ELF 可执行文件不一样，没办法弄

**Comment by zixijian** [comment]
@mymine 装完rust还还是要继续初始化python环境的，主页有写。

**Comment by mymine** [comment]
> @mymine 装完rust还还是要继续初始化python环境的，主页有写。

这两个命令？没用orjson等依赖termux安装不上。
pip install pdm
pdm install

**Comment by skjXvdidbiw** [comment]
> > @mymine 装完rust还还是要继续初始化python环境的，主页有写。
> 
> 这两个命令？没用orjson等依赖termux安装不上。 pip install pdm pdm install

我给orjson装进termux里了，在执行pip install -r requests.txt之前，先安装这些：
pkg install rust
pkg install binutils
安装完这俩依赖就能给orjson装进去了

**Comment by skjXvdidbiw** [comment]
> > @mymine 装完rust还还是要继续初始化python环境的，主页有写。
> 
> 这两个命令？没用orjson等依赖termux安装不上。 pip install pdm pdm install

我给orjson装进termux里了，在执行pip install -r requests.txt之前，先安装这些：
pkg install rust
pkg install binutils
安装完这俩依赖就能给orjson装进去了

**Comment by mymine** [comment]
> > > @mymine 装完rust还还是要继续初始化python环境的，主页有写。
> > 
> > 
> > 这两个命令？没用orjson等依赖termux安装不上。 pip install pdm pdm install
> 
> 我给orjson装进termux里了，在执行pip install -r requests.txt之前，先安装这些： pkg install rust pkg install binutils 安装完这俩依赖就能给orjson装进去了

[
![Screenshot_2023-11-16-17-06-44-326_com termux](https://github.com/0-8-4/miui-auto-tasks/assets/2943365/a0b63f25-9c53-4888-9337-0e10f7a57a09)
]([](https://pan.tenire.com/view.php/823e51c517fc0069555726262624b3fd.jpg))
安装以卡死了

**Comment by skjXvdidbiw** [comment]
这个安装时间特别长，看起来像是卡死了但其实是在进行的。我装了大概半小时才装好

**Comment by zixijian** [comment]
@skjXvdidbiw 再开个termux页面，使用top即可查看当前活动进程。

**Comment by mymine** [comment]
> 这个安装时间特别长，看起来像是卡死了但其实是在进行的。我装了大概半小时才装好

安装上了，太麻烦了还是二进制文件好用。

**Comment by mymine** [comment]
pkg install rust
pkg install binutils
pkg install python
pip install cryptography 
pip install httpx 
pip install loguru 
pip install onepush 
pip install orjson 
pip install pydantic 
pip install PyYAML 
pip install tenacity 
git clone https://github.com/0-8-4/miui-auto-tasks
cd miui-auto-tasks
python miuitask.sh
