### ISSUE TITLE
[Bug] 高强度日更脚本，支持！

### ISSUE THREAD

**Issue by umena337** [0-8-4/miui-auto-tasks#147]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.2

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.12

### Describe the Bug

高强度日更脚本，支持！

### MIUITask Log

高强度日更脚本，支持！支持！支持！支持！

**Comment by THERentropy** [comment]
你不应该乱添加标签发送无意义的议题
