### ISSUE TITLE
[Feature]  有打算支持Github Action定时执行吗？

### ISSUE THREAD

**Issue by licoba** [0-8-4/miui-auto-tasks#149]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 MIUITask 并不包含该功能特性或者还不完善
- [X] Framework 这是 MIUITask 应包含的特性, 并非实现社区外功能
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

1

### Describe the Solution

1

**Comment by Night-stars-1** [comment]
不打算，github也禁止这类行为

**Comment by AoEiuV020** [comment]
自己开个repo写个配置文件用actions下载这个项目填写配置运行就可以了，

**Comment by AoEiuV020** [comment]
不过外国ip，会不会更容易触发风控了，
