### ISSUE TITLE
人机验证码无法获取token[Bug] 

### ISSUE THREAD

**Issue by Wcoom** [0-8-4/miui-auto-tasks#154]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.0

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.1

### Describe the Bug

社区又加人机验证无法拿token寄了，作者大大实在不行咱直接闭源留个yaml配置吧，社区太🐶了每次都是下午出方案，晚上出对策连24h内立马拉闸

## 开始执行... 2023-11-15 11:19:04

system_info.print_info:7 - MIUI-AUTO-TASK v1.7.0
system_info.print_info:8 - ---------- 系统信息 -------------
system_info.system_info:17 - 操作系统平台: Linux-5.15.0-87-generic-x86_64-with
system_info.system_info:18 - 操作系统版本: #97-Ubuntu SMP Mon Oct 2 21:09:21 UTC 2023
system_info.system_info:19 - 操作系统名称: Linux
system_info.system_info:20 - 操作系统位元: ('64bit', '')
system_info.system_info:21 - 操作系统类型: x86_64
system_info.system_info:22 - 处理器信息: 
system_info.system_info:23 - Python 版本: 3.10.13 ('main', 'Oct 19 2023 06:08:04')
system_info.print_info:10 - ---------- 项目信息 -------------
system_info.print_info:11 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
system_info.print_info:12 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
system_info.print_info:13 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
login.login:74 - 小米账号登录成功
utils.get_token:209 - 遇到人机验证码, 尝试调用解决方案
utils.get_token_by_captcha:110 - 遇到人机验证码，无法获取TOKEN
utils.get_token_by_captcha:110 - 遇到人机验证码，无法获取TOKEN
utils.get_token_by_captcha:110 - 遇到人机验证码，无法获取TOKEN
request.notify_me:75 - 未配置推送或未正确配置推送

**Comment by Night-stars-1** [comment]
```
utils.get_token:209 - 遇到人机验证码, 尝试调用解决方案
```
解决方案需要你自己写

**Comment by Wcoom** [comment]
cookie？

**Comment by Wcoom** [comment]
重写cookie？

**Comment by dalaodaidaiwo123** [comment]
能不能改为抓包获取token？
