### ISSUE TITLE
[Bug] 最新版本因为遇到验证码无法执行

### ISSUE THREAD

**Issue by lengsukq** [0-8-4/miui-auto-tasks#156]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.3

### Bug Found in Environment

Windows

### Bug Found in Python Version

3.12

### Describe the Bug

遇到人机验证码，无法获取TOKEN
可能是小米那边修复了

### MIUITask Log

login.login:66 - Cookie有效，跳过登录
utils.get_token:209 - 遇到人机验证码, 尝试调用解决方案
utils.get_token_by_captcha:110 - 遇到人机验证码，无法获取TOKEN
utils.get_token_by_captcha:110 - 遇到人机验证码，无法获取TOKEN
utils.get_token_by_captcha:110 - 遇到人机验证码，无法获取TOKEN
request.notify_me:75 - 未配置推送或未正确配置推送

### Screenshots

![image](https://github.com/0-8-4/miui-auto-tasks/assets/105091166/32a09a3a-aa36-4c2c-a05a-ccf26ba42315)

**Comment by wxchil** [comment]
一样
