### ISSUE TITLE
v1.7.1 缺少协议头？ Request URL is missing an 'http://' or 'https://' protocol."

### ISSUE THREAD

**Issue by klcb2010** [0-8-4/miui-auto-tasks#159]
![截屏图片](https://github.com/0-8-4/miui-auto-tasks/assets/32628414/381ca62a-d35d-42f5-8f98-3dbd6deca341)

v1.7.1

### Bug Found in Environment

Linux, Docker

### Bug Found in Python Version

Python 3.10.12

### Describe the Bug

system_info.print_info:12 - MIUI-AUTO-TASK v1.7.1
system_info.print_info:13 - ---------- 系统信息 -------------
system_info.system_info:23 - 操作系统平台: Linux-4.4.35_ecoo_83081268-aarch64-with
system_info.system_info:24 - 操作系统版本: #1 SMP Sat Aug 12 13:21:58 CST 2023
system_info.system_info:25 - 操作系统名称: Linux
system_info.system_info:26 - 操作系统位元: ('64bit', '')
system_info.system_info:27 - 操作系统类型: aarch64
system_info.system_info:28 - 处理器信息: 
system_info.system_info:29 - Python 版本: 3.10.12 ('main', 'Jun 15 2023 06:33:42')
system_info.print_info:15 - ---------- 项目信息 -------------
system_info.print_info:16 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
system_info.print_info:17 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
system_info.print_info:18 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
system_info.print_info:19 - ---------- 脚本日志 -------------
login.login:70 - Cookie有效，跳过登录
utils.get_token:209 - 遇到人机验证码, 尝试调用解决方案
captcha.get_validate:37 - 获取人机验证结果异常
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
                 │    │     │                    └ <Request [b'POST']>
                 │    │     └ <function AsyncConnectionPool.handle_async_request at 0x7f8bd96830>
                 │    └ <httpcore.AsyncConnectionPool object at 0x7f8a741cc0>
                 └ <httpx.AsyncHTTPTransport object at 0x7f8a741c90>
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 215, in handle_async_request
    raise UnsupportedProtocol(
          └ <class 'httpcore.UnsupportedProtocol'>

httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 42, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x7f8e19bd90>
    │       └ <function run at 0x7f8de81480>
    └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object main at 0x7f8a9e84a0>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f8d3a5a20>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f8d3a5990>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f8d3a7490>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f8d5b6e60>
    └ <Handle <TaskStepMethWrapper object at 0x7f8a742230>()>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f8a742230>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f8a742230>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f8a742230>()>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 22, in main
    token = await get_token(cookies["cUserId"])
                  │         └ {'cUserId': 'Py6aZuNPaN0k_z_3MpjM2KekY60', 'miui_vip_ph': '7AVA8KsBJ97G2/p8NMCvOA==', 'miui_vip_serviceToken': 'IA2BKMwRB8IbW...
                  └ <function get_token at 0x7f8a9e3250>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 212, in get_token
    if toekn := await get_token_by_captcha(url):
                      │                    └ 'https://static-verify.sec.xiaomi.com/v2/html/check.html?t=1&k=3dc42a135a8d45118034d1ab68213073&e=Fl89mN%2F9rkKdRAqcPzuO828ZY...
                      └ <function get_token_by_captcha at 0x7f8a9e31c0>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 90, in get_token_by_captcha
    geetest_data = await get_validate(gt, challenge)
                         │            │   └ 'acb092df3f8c335690f7c220aa798acc'
                         │            └ '8351ae0ef2e0b2afdbafc3c4a2d22e6e'
                         └ <function get_validate at 0x7f8a9e2b90>

> File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/captcha.py", line 25, in get_validate
    response = await post(
                     └ <function post at 0x7f8bdb5480>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/request.py", line 61, in post
    return await client.post(url,
                 │      │    └ ''
                 │      └ <function AsyncClient.post at 0x7f8bdb4b80>
                 └ <httpx.AsyncClient object at 0x7f8aa00880>

  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
                 │    └ <function AsyncClient.request at 0x7f8bdb45e0>
                 └ <httpx.AsyncClient object at 0x7f8aa00880>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x7f8bb9acb0>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x7f8bb9acb0>
                 │    │    └ <Request('POST', '/')>
                 │    └ <function AsyncClient.send at 0x7f8bdb4790>
                 └ <httpx.AsyncClient object at 0x7f8aa00880>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x7f8bdb4820>
                     └ <httpx.AsyncClient object at 0x7f8aa00880>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x7f8bdb48b0>
                     └ <httpx.AsyncClient object at 0x7f8aa00880>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('POST', '/')>
                     │    └ <function AsyncClient._send_single_request at 0x7f8bdb4940>
                     └ <httpx.AsyncClient object at 0x7f8aa00880>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('POST', '/')>
                     │         └ <function AsyncHTTPTransport.handle_async_request at 0x7f8bda9d80>
                     └ <httpx.AsyncHTTPTransport object at 0x7f8a741c90>
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
         └ <function map_httpcore_exceptions at 0x7f8b8180d0>
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
    │    │   │     │    │      └ <traceback object at 0x7f8a731e80>
    │    │   │     │    └ UnsupportedProtocol("Request URL is missing an 'http://' or 'https://' protocol.")
    │    │   │     └ <class 'httpcore.UnsupportedProtocol'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object map_httpcore_exceptions at 0x7f8a734510>
    └ <contextlib._GeneratorContextManager object at 0x7f8a7420e0>
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
          │          └ "Request URL is missing an 'http://' or 'https://' protocol."
          └ <class 'httpx.UnsupportedProtocol'>

httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
utils.get_token_by_captcha:110 - 遇到人机验证码，无法获取TOKEN
captcha.get_validate:37 - 获取人机验证结果异常
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
                 │    │     │                    └ <Request [b'POST']>
                 │    │     └ <function AsyncConnectionPool.handle_async_request at 0x7f8bd96830>
                 │    └ <httpcore.AsyncConnectionPool object at 0x7f8a7420b0>
                 └ <httpx.AsyncHTTPTransport object at 0x7f8a7421d0>
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 215, in handle_async_request
    raise UnsupportedProtocol(
          └ <class 'httpcore.UnsupportedProtocol'>

httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 42, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x7f8e19bd90>
    │       └ <function run at 0x7f8de81480>
    └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object main at 0x7f8a9e84a0>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f8d3a5a20>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f8d3a5990>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f8d3a7490>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f8d5b6e60>
    └ <Handle <TaskStepMethWrapper object at 0x7f8a743eb0>()>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f8a743eb0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f8a743eb0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f8a743eb0>()>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 22, in main
    token = await get_token(cookies["cUserId"])
                  │         └ {'cUserId': 'Py6aZuNPaN0k_z_3MpjM2KekY60', 'miui_vip_ph': '7AVA8KsBJ97G2/p8NMCvOA==', 'miui_vip_serviceToken': 'IA2BKMwRB8IbW...
                  └ <function get_token at 0x7f8a9e3250>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 212, in get_token
    if toekn := await get_token_by_captcha(url):
       │              │                    └ 'https://static-verify.sec.xiaomi.com/v2/html/check.html?t=1&k=3dc42a135a8d45118034d1ab68213073&e=Fl89mN%2F9rkKdRAqcPzuO828ZY...
       │              └ <function get_token_by_captcha at 0x7f8a9e31c0>
       └ False

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 90, in get_token_by_captcha
    geetest_data = await get_validate(gt, challenge)
                         │            │   └ 'acb092df3f8c335690f7c220aa798acc'
                         │            └ '8351ae0ef2e0b2afdbafc3c4a2d22e6e'
                         └ <function get_validate at 0x7f8a9e2b90>

> File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/captcha.py", line 25, in get_validate
    response = await post(
                     └ <function post at 0x7f8bdb5480>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/request.py", line 61, in post
    return await client.post(url,
                 │      │    └ ''
                 │      └ <function AsyncClient.post at 0x7f8bdb4b80>
                 └ <httpx.AsyncClient object at 0x7f8a65bc10>

  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
                 │    └ <function AsyncClient.request at 0x7f8bdb45e0>
                 └ <httpx.AsyncClient object at 0x7f8a65bc10>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x7f8bb9acb0>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x7f8bb9acb0>
                 │    │    └ <Request('POST', '/')>
                 │    └ <function AsyncClient.send at 0x7f8bdb4790>
                 └ <httpx.AsyncClient object at 0x7f8a65bc10>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x7f8bdb4820>
                     └ <httpx.AsyncClient object at 0x7f8a65bc10>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x7f8bdb48b0>
                     └ <httpx.AsyncClient object at 0x7f8a65bc10>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('POST', '/')>
                     │    └ <function AsyncClient._send_single_request at 0x7f8bdb4940>
                     └ <httpx.AsyncClient object at 0x7f8a65bc10>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('POST', '/')>
                     │         └ <function AsyncHTTPTransport.handle_async_request at 0x7f8bda9d80>
                     └ <httpx.AsyncHTTPTransport object at 0x7f8a7421d0>
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
         └ <function map_httpcore_exceptions at 0x7f8b8180d0>
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
    │    │   │     │    │      └ <traceback object at 0x7f8a40e840>
    │    │   │     │    └ UnsupportedProtocol("Request URL is missing an 'http://' or 'https://' protocol.")
    │    │   │     └ <class 'httpcore.UnsupportedProtocol'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object map_httpcore_exceptions at 0x7f8a46bbc0>
    └ <contextlib._GeneratorContextManager object at 0x7f8a743be0>
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
          │          └ "Request URL is missing an 'http://' or 'https://' protocol."
          └ <class 'httpx.UnsupportedProtocol'>

httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
utils.get_token_by_captcha:110 - 遇到人机验证码，无法获取TOKEN
captcha.get_validate:37 - 获取人机验证结果异常
Traceback (most recent call last):

  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
    resp = await self._pool.handle_async_request(req)
                 │    │     │                    └ <Request [b'POST']>
                 │    │     └ <function AsyncConnectionPool.handle_async_request at 0x7f8bd96830>
                 │    └ <httpcore.AsyncConnectionPool object at 0x7f8a743100>
                 └ <httpx.AsyncHTTPTransport object at 0x7f8a47d990>
  File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 215, in handle_async_request
    raise UnsupportedProtocol(
          └ <class 'httpcore.UnsupportedProtocol'>

httpcore.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 42, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x7f8e19bd90>
    │       └ <function run at 0x7f8de81480>
    └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object main at 0x7f8a9e84a0>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f8d3a5a20>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f8d3a5990>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f8d3a7490>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f8d5b6e60>
    └ <Handle <TaskStepMethWrapper object at 0x7f8a47dab0>()>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f8a47dab0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f8a47dab0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f8a47dab0>()>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 22, in main
    token = await get_token(cookies["cUserId"])
                  │         └ {'cUserId': 'Py6aZuNPaN0k_z_3MpjM2KekY60', 'miui_vip_ph': '7AVA8KsBJ97G2/p8NMCvOA==', 'miui_vip_serviceToken': 'IA2BKMwRB8IbW...
                  └ <function get_token at 0x7f8a9e3250>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 212, in get_token
    if toekn := await get_token_by_captcha(url):
       │              │                    └ 'https://static-verify.sec.xiaomi.com/v2/html/check.html?t=1&k=3dc42a135a8d45118034d1ab68213073&e=Fl89mN%2F9rkKdRAqcPzuO828ZY...
       │              └ <function get_token_by_captcha at 0x7f8a9e31c0>
       └ False

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 90, in get_token_by_captcha
    geetest_data = await get_validate(gt, challenge)
                         │            │   └ 'acb092df3f8c335690f7c220aa798acc'
                         │            └ '8351ae0ef2e0b2afdbafc3c4a2d22e6e'
                         └ <function get_validate at 0x7f8a9e2b90>

> File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/captcha.py", line 25, in get_validate
    response = await post(
                     └ <function post at 0x7f8bdb5480>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/request.py", line 61, in post
    return await client.post(url,
                 │      │    └ ''
                 │      └ <function AsyncClient.post at 0x7f8bdb4b80>
                 └ <httpx.AsyncClient object at 0x7f8a7419c0>

  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
                 │    └ <function AsyncClient.request at 0x7f8bdb45e0>
                 └ <httpx.AsyncClient object at 0x7f8a7419c0>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
                 │    │    │             │                      └ <httpx._client.UseClientDefault object at 0x7f8bb9acb0>
                 │    │    │             └ <httpx._client.UseClientDefault object at 0x7f8bb9acb0>
                 │    │    └ <Request('POST', '/')>
                 │    └ <function AsyncClient.send at 0x7f8bdb4790>
                 └ <httpx.AsyncClient object at 0x7f8a7419c0>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
                     │    └ <function AsyncClient._send_handling_auth at 0x7f8bdb4820>
                     └ <httpx.AsyncClient object at 0x7f8a7419c0>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
                     │    └ <function AsyncClient._send_handling_redirects at 0x7f8bdb48b0>
                     └ <httpx.AsyncClient object at 0x7f8a7419c0>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
                     │    │                    └ <Request('POST', '/')>
                     │    └ <function AsyncClient._send_single_request at 0x7f8bdb4940>
                     └ <httpx.AsyncClient object at 0x7f8a7419c0>
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
                     │         │                    └ <Request('POST', '/')>
                     │         └ <function AsyncHTTPTransport.handle_async_request at 0x7f8bda9d80>
                     └ <httpx.AsyncHTTPTransport object at 0x7f8a47d990>
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 365, in handle_async_request
    with map_httpcore_exceptions():
         └ <function map_httpcore_exceptions at 0x7f8b8180d0>
  File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
    │    │   │     │    │      └ <traceback object at 0x7f8a484a80>
    │    │   │     │    └ UnsupportedProtocol("Request URL is missing an 'http://' or 'https://' protocol.")
    │    │   │     └ <class 'httpcore.UnsupportedProtocol'>
    │    │   └ <method 'throw' of 'generator' objects>
    │    └ <generator object map_httpcore_exceptions at 0x7f8a46bf40>
    └ <contextlib._GeneratorContextManager object at 0x7f8a741fc0>
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
          │          └ "Request URL is missing an 'http://' or 'https://' protocol."
          └ <class 'httpx.UnsupportedProtocol'>

httpx.UnsupportedProtocol: Request URL is missing an 'http://' or 'https://' protocol.
utils.get_token_by_captcha:110 - 遇到人机验证码，无法获取TOKEN
miuitask.main:28 - 开始执行抢先体验小米澎湃OS！任务
miuitask.main:35 - 未找到抢先体验小米澎湃OS！任务
miuitask.main:37 - 每日签到任务已完成
miuitask.main:37 - 浏览帖子超过10秒任务已完成
miuitask.main:37 - 点赞他人帖子任务已完成
request.notify_me:75 - 未配置推送或未正确配置推送

**Comment by Night-stars-1** [comment]
这不是bug， url需要你自己设置

**Comment by klcb2010** [comment]
> 这不是bug， url需要你自己设置

这  完全不会啊 求指导
