### ISSUE TITLE
请教如何抓取一个操作请求url及参数

### ISSUE THREAD

**Issue by ljynfo** [0-8-4/miui-auto-tasks#16]
如果需要自己加点东西，请问如何知道一个操作的请求url和参数？
装了Charles，安卓手机安装了证书，但是抓包还是显示unknown，请问大佬是怎么抓取请求的？能否分享一下

**Comment by 0-8-4** [comment]
帮你问了一下大佬，他的原话是
> 要root以后把证书移到system下
> https://www.cnblogs.com/Entr0py/p/9675061.html
