### ISSUE TITLE
[Feature] 是否有推荐的解决gt的平台?

### ISSUE THREAD

**Issue by 603185423** [0-8-4/miui-auto-tasks#161]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 MIUITask 并不包含该功能特性或者还不完善
- [X] Framework 这是 MIUITask 应包含的特性, 并非实现社区外功能
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

是否有推荐的解决gt的平台?

### Describe the Solution

找到个capSolver冲了点钱, 改代码试了一下发现这个平台好像不支持slide3类型的

![image](https://github.com/0-8-4/miui-auto-tasks/assets/50170900/66a066df-15dc-4223-8b4c-166fcf1a845b)

如果方便告知推荐的平台的话就多谢了

不方便的话直接close issue或者删掉issue都行(

**Comment by 603185423** [comment]
damagou

**Comment by wzgrx** [comment]
www.damagou.top 当前无法处理此请求。
HTTP ERROR 502
