### ISSUE TITLE
[Bug] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 8283: invalid start byte

### ISSUE THREAD

**Issue by klcb2010** [0-8-4/miui-auto-tasks#165]
### Verify Steps

v1.7.1

### Bug Found in Environment

Linux, Docker

### Bug Found in Python Version

3.1

### Describe the Bug

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 8283: invalid start byte

![截屏图片](https://github.com/0-8-4/miui-auto-tasks/assets/32628414/b165d3c2-97a1-4558-9755-0e88c24ac31b)

### MIUITask Log

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 8283: invalid start byte

**Comment by Night-stars-1** [comment]
截图部分不足以定位问题

**Comment by klcb2010** [comment]
> 截图部分不足以定位问题

`Traceback (most recent call last):

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 42, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x7f8d82bd90>
    │       └ <function run at 0x7f8d511480>
    └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object main at 0x7f8a06c510>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f8ca35a20>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f8ca35990>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f8ca37490>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f8cc46e60>
    └ <Handle <TaskStepMethWrapper object at 0x7f89dcb400>()>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f89dcb400>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f89dcb400>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f89dcb400>()>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 22, in main
    token = await get_token(cookies["cUserId"])
                  │         └ {'cUserId': 'Py6aZuNPaN0k_z_3MpjM2KekY60', 'miui_vip_ph': '7AVA8KsBJ97G2/p8NMCvOA==', 'miui_vip_serviceToken': 'IA2BKMwRB8IbW...
                  └ <function get_token at 0x7f8a067250>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 212, in get_token
    if toekn := await get_token_by_captcha(url):
                      │                    └ 'https://static-verify.sec.xiaomi.com/v2/html/check.html?t=1&k=3dc42a135a8d45118034d1ab68213073&e=VwWPiE0BgHVdxCcowmAKt7qERDQ...
                      └ <function get_token_by_captcha at 0x7f8a0671c0>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 90, in get_token_by_captcha
    geetest_data = await get_validate(gt, challenge)
                         │            │   └ '2e1a384f8901f7bbab5f2a6ed74d86e6'
                         │            └ '8351ae0ef2e0b2afdbafc3c4a2d22e6e'
                         └ <function get_validate at 0x7f8a066b90>

> File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/captcha.py", line 31, in get_validate
    geetest_data = response.json()
                   │        └ <function Response.json at 0x7f8ae2d990>
                   └ <Response [200 OK]>

  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 761, in json
    return jsonlib.loads(self.content, **kwargs)
           │       │     │    │          └ {}
           │       │     │    └ <property object at 0x7f8ae30680>
           │       │     └ <Response [200 OK]>
           │       └ <function loads at 0x7f8cb05480>
           └ <module 'json' from '/usr/local/lib/python3.10/json/__init__.py'>
  File "/usr/local/lib/python3.10/json/__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        │ │      │               └ b'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r...
        │ │      └ <function detect_encoding at 0x7f8cb05360>
        │ └ <method 'decode' of 'bytes' objects>
        └ b'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r...

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 8244: invalid start byte
utils.get_token_by_captcha:110 - 遇到人机验证码，无法获取TOKEN
captcha.get_validate:37 - 获取人机验证结果异常
Traceback (most recent call last):

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 42, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x7f8d82bd90>
    │       └ <function run at 0x7f8d511480>
    └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object main at 0x7f8a06c510>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f8ca35a20>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f8ca35990>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f8ca37490>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f8cc46e60>
    └ <Handle <TaskStepMethWrapper object at 0x7f899a26b0>()>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f899a26b0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f899a26b0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f899a26b0>()>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 22, in main
    token = await get_token(cookies["cUserId"])
                  │         └ {'cUserId': 'Py6aZuNPaN0k_z_3MpjM2KekY60', 'miui_vip_ph': '7AVA8KsBJ97G2/p8NMCvOA==', 'miui_vip_serviceToken': 'IA2BKMwRB8IbW...
                  └ <function get_token at 0x7f8a067250>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 212, in get_token
    if toekn := await get_token_by_captcha(url):
       │              │                    └ 'https://static-verify.sec.xiaomi.com/v2/html/check.html?t=1&k=3dc42a135a8d45118034d1ab68213073&e=VwWPiE0BgHVdxCcowmAKt7qERDQ...
       │              └ <function get_token_by_captcha at 0x7f8a0671c0>
       └ False

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 90, in get_token_by_captcha
    geetest_data = await get_validate(gt, challenge)
                         │            │   └ '2e1a384f8901f7bbab5f2a6ed74d86e6'
                         │            └ '8351ae0ef2e0b2afdbafc3c4a2d22e6e'
                         └ <function get_validate at 0x7f8a066b90>

> File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/captcha.py", line 31, in get_validate
    geetest_data = response.json()
                   │        └ <function Response.json at 0x7f8ae2d990>
                   └ <Response [200 OK]>

  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 761, in json
    return jsonlib.loads(self.content, **kwargs)
           │       │     │    │          └ {}
           │       │     │    └ <property object at 0x7f8ae30680>
           │       │     └ <Response [200 OK]>
           │       └ <function loads at 0x7f8cb05480>
           └ <module 'json' from '/usr/local/lib/python3.10/json/__init__.py'>
  File "/usr/local/lib/python3.10/json/__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        │ │      │               └ b'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r...
        │ │      └ <function detect_encoding at 0x7f8cb05360>
        │ └ <method 'decode' of 'bytes' objects>
        └ b'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r...

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 8244: invalid start byte
utils.get_token_by_captcha:110 - 遇到人机验证码，无法获取TOKEN
captcha.get_validate:37 - 获取人机验证结果异常
Traceback (most recent call last):

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 42, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x7f8d82bd90>
    │       └ <function run at 0x7f8d511480>
    └ <module 'asyncio' from '/usr/local/lib/python3.10/asyncio/__init__.py'>

  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
           │    │                  └ <coroutine object main at 0x7f8a06c510>
           │    └ <function BaseEventLoop.run_until_complete at 0x7f8ca35a20>
           └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f8ca35990>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f8ca37490>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f8cc46e60>
    └ <Handle <TaskStepMethWrapper object at 0x7f899b1930>()>
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7f899b1930>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7f899b1930>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7f899b1930>()>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 22, in main
    token = await get_token(cookies["cUserId"])
                  │         └ {'cUserId': 'Py6aZuNPaN0k_z_3MpjM2KekY60', 'miui_vip_ph': '7AVA8KsBJ97G2/p8NMCvOA==', 'miui_vip_serviceToken': 'IA2BKMwRB8IbW...
                  └ <function get_token at 0x7f8a067250>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 212, in get_token
    if toekn := await get_token_by_captcha(url):
       │              │                    └ 'https://static-verify.sec.xiaomi.com/v2/html/check.html?t=1&k=3dc42a135a8d45118034d1ab68213073&e=VwWPiE0BgHVdxCcowmAKt7qERDQ...
       │              └ <function get_token_by_captcha at 0x7f8a0671c0>
       └ False

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 90, in get_token_by_captcha
    geetest_data = await get_validate(gt, challenge)
                         │            │   └ '2e1a384f8901f7bbab5f2a6ed74d86e6'
                         │            └ '8351ae0ef2e0b2afdbafc3c4a2d22e6e'
                         └ <function get_validate at 0x7f8a066b90>

> File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/captcha.py", line 31, in get_validate
    geetest_data = response.json()
                   │        └ <function Response.json at 0x7f8ae2d990>
                   └ <Response [200 OK]>

  File "/usr/local/lib/python3.10/site-packages/httpx/_models.py", line 761, in json
    return jsonlib.loads(self.content, **kwargs)
           │       │     │    │          └ {}
           │       │     │    └ <property object at 0x7f8ae30680>
           │       │     └ <Response [200 OK]>
           │       └ <function loads at 0x7f8cb05480>
           └ <module 'json' from '/usr/local/lib/python3.10/json/__init__.py'>
  File "/usr/local/lib/python3.10/json/__init__.py", line 341, in loads
    s = s.decode(detect_encoding(s), 'surrogatepass')
        │ │      │               └ b'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r...
        │ │      └ <function detect_encoding at 0x7f8cb05360>
        │ └ <method 'decode' of 'bytes' objects>
        └ b'<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r...

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 8244: invalid start byte
utils.get_token_by_captcha:110 - 遇到人机验证码，无法获取TOKEN
miuitask.main:28 - 开始执行抢先体验小米澎湃OS！任务
miuitask.main:35 - 未找到抢先体验小米澎湃OS！任务
miuitask.main:37 - 每日签到任务已完成
miuitask.main:37 - 浏览帖子超过10秒任务已完成
miuitask.main:37 - 点赞他人帖子任务已完成
request.notify_me:75 - 未配置推送或未正确配置推送

## 执行结束... 2023-11-16 19:45:29  耗时 8 秒　　　　　

`

**Comment by Night-stars-1** [comment]
发log

**Comment by klcb2010** [comment]
> 发log

发现问题了 是极验证不会搭配导致  希望可以出个教程 @
