### ISSUE TITLE
[Bug] 做完任务不推送+日志文件输出有乱码

### ISSUE THREAD

**Issue by lxr760** [0-8-4/miui-auto-tasks#173]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.3

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.12

### Describe the Bug

本脚本在青龙里运行走的不是青龙的推送，要单独自己设置？

怎么提示没有配置。

另外，日志输出文件的格式也很奇怪，难以阅读。上一个版本是正常的

## 开始执行... 2023-11-18 14:02:00

[36msystem_info[0m.[36mprint_info[0m:[36m12[0m - [1mMIUI-AUTO-TASK v1.7.1.1[0m
[36msystem_info[0m.[36mprint_info[0m:[36m13[0m - [1m---------- 系统信息 -------------[0m
[36msystem_info[0m.[36msystem_info[0m:[36m23[0m - [1m操作系统平台: Linux-5.10.60-qnap-x86_64-with[0m
[36msystem_info[0m.[36msystem_info[0m:[36m24[0m - [1m操作系统版本: #1 SMP Tue Aug 15 01:14:42 CST 2023[0m
[36msystem_info[0m.[36msystem_info[0m:[36m25[0m - [1m操作系统名称: Linux[0m
[36msystem_info[0m.[36msystem_info[0m:[36m26[0m - [1m操作系统位元: ('64bit', 'ELF')[0m
[36msystem_info[0m.[36msystem_info[0m:[36m27[0m - [1m操作系统类型: x86_64[0m
[36msystem_info[0m.[36msystem_info[0m:[36m28[0m - [1m处理器信息: [0m
[36msystem_info[0m.[36msystem_info[0m:[36m29[0m - [1mPython 版本: 3.11.0 ('main', 'Nov 12 2022 07:10:51')[0m
[36msystem_info[0m.[36mprint_info[0m:[36m15[0m - [1m---------- 项目信息 -------------[0m
[36msystem_info[0m.[36mprint_info[0m:[36m16[0m - [1m这是一个免费且开源的项目，如果你是付费购买获得请务必退款[0m
[36msystem_info[0m.[36mprint_info[0m:[36m17[0m - [1m项目地址：https://github.com/0-8-4/miui-auto-tasks[0m
[36msystem_info[0m.[36mprint_info[0m:[36m18[0m - [1m欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人[0m
[36msystem_info[0m.[36mprint_info[0m:[36m19[0m - [1m---------- 脚本日志 -------------[0m
[36mlogin[0m.[36mlogin[0m:[36m78[0m - [32m[1m小米账号登录成功[0m
[36mutils[0m.[36mget_token[0m:[36m209[0m - [31m[1m遇到人机验证码, 尝试调用解决方案[0m
[36mutils[0m.[36mget_token_by_captcha[0m:[36m110[0m - [31m[1m遇到人机验证码，无法获取TOKEN[0m
[36mutils[0m.[36mget_token_by_captcha[0m:[36m110[0m - [31m[1m遇到人机验证码，无法获取TOKEN[0m
[36mutils[0m.[36mget_token_by_captcha[0m:[36m110[0m - [31m[1m遇到人机验证码，无法获取TOKEN[0m
[36mmiuitask[0m.[36mmain[0m:[36m28[0m - [1m开始执行抢先体验小米澎湃OS！任务[0m
[36mmiuitask[0m.[36mmain[0m:[36m35[0m - [31m[1m未找到抢先体验小米澎湃OS！任务[0m
[36mmiuitask[0m.[36mmain[0m:[36m28[0m - [1m开始执行每日签到任务[0m
[36msign[0m.[36msign[0m:[36m72[0m - [1m未获取到token, 跳过每日签到[0m
[36mmiuitask[0m.[36mmain[0m:[36m37[0m - [1m浏览帖子超过10秒任务已完成[0m
[36mmiuitask[0m.[36mmain[0m:[36m37[0m - [1m点赞他人帖子任务已完成[0m
[36mrequest[0m.[36mnotify_me[0m:[36m75[0m - [31m[1m未配置推送或未正确配置推送[0m

## 执行结束... 2023-11-18 14:02:04  耗时 4 秒

![image](https://github.com/0-8-4/miui-auto-tasks/assets/8476457/5e56f1e5-906d-4213-b6c2-3a45c49a7690)

**Comment by Night-stars-1** [comment]
1.先检查自己的青龙是不是最新版
2.请认真阅读日志信息
```
�[36mrequest�[0m.�[36mnotify_me�[0m:�[36m75�[0m - �[31m�[1m未配置推送或未正确配置推送�[0m
```
