### ISSUE TITLE
青龙v2.11.1运行报错[Bug] 

### ISSUE THREAD

**Issue by Golven-8964** [0-8-4/miui-auto-tasks#174]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

V1.6.0.1

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.7

## 开始执行... 2023-11-19 00:40:58

Traceback (most recent call last):
  File "miuitask.py", line 6, in <module>
    from utils.api.login import Login
ModuleNotFoundError: No module named 'utils.api'

## 开始执行... 2023-11-19 00:40:58

Traceback (most recent call last):
  File "miuitask.py", line 6, in <module>
    from utils.api.login import Login
ModuleNotFoundError: No module named 'utils.api'

### Screenshots

![屏幕截图 2023-11-19 015200](https://github.com/0-8-4/miui-auto-tasks/assets/71271253/d8c774b2-886f-47c6-b242-f58ec71a50ab)

**Comment by mymine** [comment]
没有安装依赖。
