### ISSUE TITLE
[Bug] 一直显示格式不正确

### ISSUE THREAD

**Issue by capricornuszhg** [0-8-4/miui-auto-tasks#175]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v16

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.9

### Describe the Bug

求助啊。有没有能加的微信啊，大哥们，青龙面板

### MIUITask Log

![image](https://github.com/0-8-4/miui-auto-tasks/assets/102714544/15840798-7223-4bc6-addd-e8702571ac0d)

### MIUITask Config

```shell
![image](https://github.com/0-8-4/miui-auto-tasks/assets/102714544/aa225373-a92a-4f9c-bd9f-89d2c08fa723)
```

**Comment by capricornuszhg** [comment]
![image](https://github.com/0-8-4/miui-auto-tasks/assets/102714544/f21a540c-dbde-4d7f-9785-e4bc1e126736)

**Comment by capricornuszhg** [comment]
有没有大佬救救我 肯定不会白白让大哥辛苦

**Comment by Night-stars-1** [comment]
uid是str类型，要加`""`
cookies是dict类型，要加`{}`
按照生成的格式填

**Comment by capricornuszhg** [comment]
> uid是str类型，要加`""` cookies是dict类型，要加`{}` 按照生成的格式填

这个问题解决了，现在是
![image](https://github.com/0-8-4/miui-auto-tasks/assets/102714544/11405c1e-7043-4e21-8515-fd5b7318c76b)
另外的风控，挂的云服务器，我在想怎么可以解决

**Comment by capricornuszhg** [comment]
> uid是str类型，要加`""` cookies是dict类型，要加`{}` 按照生成的格式填

您可以加我qq吗  596501569
