### ISSUE TITLE
[Bug] preference的geetest_url相关参数如何填写, wiki没有相关说明

### ISSUE THREAD

**Issue by FairyWorld** [0-8-4/miui-auto-tasks#178]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.2

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.12

### Describe the Bug

preference的geetest_url相关参数如何填写, wiki没有相关说明

### MIUITask Log

preference的geetest_url相关参数如何填写, wiki没有相关说明

**Comment by Night-stars-1** [comment]
故意不写的

**Comment by 0-8-4** [comment]
是 feature 不是bug （确信
