### ISSUE TITLE
[Bug] 在 requirement.txt 中加个 apscheduler 吧

### ISSUE THREAD

**Issue by UnspokenSpell** [0-8-4/miui-auto-tasks#181]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

1.7.2

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.10.13

### Describe the Bug

缺少依赖 apscheduler。

青龙版本 2.16.5

### MIUITask Log

Traceback (most recent call last):
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 6, in <module>
    from apscheduler.schedulers.asyncio import AsyncIOScheduler
ModuleNotFoundError: No module named 'apscheduler'

**Comment by UnspokenSpell** [comment]
小白遇到这个门槛说不定就被挡住了😅。

**Comment by 603185423** [comment]
挡住不是更好
