### ISSUE TITLE
[Bug] cookie有效期多久？昨天的cookie今天就失效了。昨天运行了一次，今天发现点赞任务消失了。

### ISSUE THREAD

**Issue by FairyWorld** [0-8-4/miui-auto-tasks#183]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.2

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.12

### Describe the Bug

cookie有效期多久？昨天的cookie今天就失效了。昨天运行了一次，今天发现点赞任务消失了。

### MIUITask Log

日志找不到了，今天cookie失效，并且我发现app的点赞任务入口没有了

**Comment by Night-stars-1** [comment]
cookies有效期一天，点赞被官方取消了，非脚本所为

**Comment by cy28438981** [comment]
你们签到是怎么过滑块的？

**Comment by cy28438981** [comment]
你们签到是怎么过滑块的

**Comment by sluckydream** [comment]
> 你们签到是怎么过滑块的？

b站有教程过极验3滑块

**Comment by cy28438981** [comment]
完全听不懂，我本身不懂技术，能不能求您帮忙搭建下小米社区过滑块？

wj420521 ***@***.***> 于2023年11月21日周二 14:21写道：
