### ISSUE TITLE
[Feature] 关于人机验证的一种方法（或许）

### ISSUE THREAD

**Issue by kazsy** [0-8-4/miui-auto-tasks#199]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 MIUITask 并不包含该功能特性或者还不完善
- [X] Framework 这是 MIUITask 应包含的特性, 并非实现社区外功能
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

人工过验证

### Describe the Solution

也许可以尝试把人机验证链接推送到微信人工来进行验证，但是验证过后如何返回数据我就不知道了

**Comment by Night-stars-1** [comment]
那你为什么不手动签到呢

**Comment by a312354805** [comment]
确实，既然都这样了 为什么不手动签到呢

**Comment by 603185423** [comment]
这样子还不如配置个推送, 每天收到签到失败的推送之后手动去社区签到

**Comment by kazsy** [comment]
因为不想打开那个软件啊，而且有可能后面就不用验证了啊

**Comment by 603185423** [comment]
> 因为不想打开那个软件啊，而且有可能后面就不用验证了啊

不要想当然，到底要不要验证自己试试或者翻翻issue

**Comment by Night-stars-1** [comment]
。。。有些东西不能摆在明面上，你在这地方问不会得到有效解答的

**Comment by sluckydream** [comment]
别整了 ,滑块过了,也不会返回token,签到分也少
,今天号还给封了,社区尽整些恶心人的东西

**Comment by Night-stars-1** [comment]
> 别整了 ,滑块过了,也不会返回token,签到分也少 ,今天号还给封了,社区尽整些恶心人的东西

我们这边是可以返回token的
![image](https://github.com/0-8-4/miui-auto-tasks/assets/99261160/9bed6690-f69a-4f60-ba53-79a2960e1450)

**Comment by sluckydream** [comment]
> > 别整了 ,滑块过了,也不会返回token,签到分也少 ,今天号还给封了,社区尽整些恶心人的东西
> 
> 我们这边是可以返回token的 ![image](https://user-images.githubusercontent.com/99261160/285169726-9bed6690-f69a-4f60-ba53-79a2960e1450.png)

你签到不是没调用？ 通过过滑块给的validate 然后获取新token,

**Comment by a312354805** [comment]
> > > 别整了 ,滑块过了,也不会返回token,签到分也少 ,今天号还给封了,社区尽整些恶心人的东西
> > 
> > 
> > 我们这边是可以返回token的 ![image](https://user-images.githubusercontent.com/99261160/285169726-9bed6690-f69a-4f60-ba53-79a2960e1450.png)
> 
> 你签到不是没调用？ 通过过滑块给的validate 然后获取新token,

你翻一下lssuse 回复最多的那条看看
---------- 脚本日志 -------------
Cookie有效，跳过登录
遇到人机验证码, 尝试调用解决方案
开始使用[2Captcha]解密验证码
获取解密参数成功
开始获取token
token获取成功,准备执行任务
开始执行抢先体验小米澎湃OS！任务
未找到抢先体验小米澎湃OS！任务
开始执行每日签到任务
每日签到结果: 成长值+1
开始执行浏览帖子超过10秒任务
浏览帖子超过10秒结果: 成长值+1
开始执行参与拔萝卜获得奖励任务
参与拔萝卜获得奖励结果: ok

**Comment by Night-stars-1** [comment]
> ......
> 你签到不是没调用？ 通过过滑块给的validate 然后获取新token,

![image](https://github.com/0-8-4/miui-auto-tasks/assets/99261160/b8bcc3e6-144d-47c2-9d53-0065d7a56b66)

**Comment by wj420521** [comment]
> > ......
> > 你签到不是没调用？ 通过过滑块给的validate 然后获取新token,
> 
> ![image](https://user-images.githubusercontent.com/99261160/285173170-b8bcc3e6-144d-47c2-9d53-0065d7a56b66.png)

![image](https://github.com/0-8-4/miui-auto-tasks/assets/47966232/b98203c6-4129-4797-88d3-d9317b6b730e)
原来获取token的加密参数这里改了。。

**Comment by 0-8-4** [comment]
> 那你为什么不手动签到呢

笑死了 大佬的这句话 配上楼下的滑稽表情

**Comment by sluckydream** [comment]
> > 那你为什么不手动签到呢
> 
> 笑死了 大佬的这句话 配上楼下的滑稽表情

获取token的加密d s 的参数data怎么弄出来的？jadx里面有个com.xiaomi.verificationsdk.internal.SensorHelper.L看起来有点像,但是Hook不到这个方法,还是调试的m.js文件？

**Comment by ZYMirror** [comment]
> > > 那你为什么不手动签到呢
> > 
> > 
> > 笑死了 大佬的这句话 配上楼下的滑稽表情
> 
> 获取token的加密d s 的参数data怎么弄出来的？jadx里面有个com.xiaomi.verificationsdk.internal.SensorHelper.L看起来有点像,但是Hook不到这个方法,还是调试的m.js文件？

兄弟你是不是酷安来的，酷安有个用js过滑块的，好多人用被封了

**Comment by Greyh4t** [comment]
> > > > 那你为什么不手动签到呢
> > > 
> > > 
> > > 笑死了 大佬的这句话 配上楼下的滑稽表情
> > 
> > 
> > 获取token的加密d s 的参数data怎么弄出来的？jadx里面有个com.xiaomi.verificationsdk.internal.SensorHelper.L看起来有点像,但是Hook不到这个方法,还是调试的m.js文件？
> 
> 兄弟你是不是酷安来的，酷安有个用js过滑块的，好多人用被封了

js的是哪个，没看到啊
