### ISSUE TITLE
[Bug] docker自动停止运行

### ISSUE THREAD

**Issue by momo325** [0-8-4/miui-auto-tasks#200]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.2

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.12

### Describe the Bug

自动停止并无限重启
![image](https://github.com/0-8-4/miui-auto-tasks/assets/68660594/75ce8780-fc2a-4250-9375-134b63d304e0)

### MIUITask Log

![image](https://github.com/0-8-4/miui-auto-tasks/assets/68660594/107289c2-ee1f-42e2-a796-6e6612793858)

**Comment by zakee039** [comment]
servserverchan推送信息
![image](https://github.com/0-8-4/miui-auto-tasks/assets/68660594/3c08903a-53b1-4f33-bb26-bba20b16f9d1)

**Comment by Night-stars-1** [comment]
docker等无外置自动运行的服务需要在config.yaml里设置运行时间
