### ISSUE TITLE
[Bug] docker不会自动设置时区

### ISSUE THREAD

**Issue by koolcandy** [0-8-4/miui-auto-tasks#204]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.702

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.12

### Describe the Bug

docker不会自动设置时区

### MIUITask Log

![截屏2023-11-24 12 37 52](https://github.com/0-8-4/miui-auto-tasks/assets/133551107/793c9908-79d5-44d3-9528-2cb405cf83ed)

### MIUITask Config

```shell
preference:
    geetest_url: 
    geetest_params: {}
    geetest_data:
    hour: '23'
    minute: '8'
```

**Comment by Night-stars-1** [comment]
```
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

**Comment by koolcandy** [comment]
> ```
> ENV TZ=Asia/Shanghai
> RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
> ```
> 

谢谢
