### ISSUE TITLE
[Bug] ttocr无法正常识别

### ISSUE THREAD

**Issue by 1wyy** [0-8-4/miui-auto-tasks#212]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.1

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.1

### Describe the Bug

...

**Comment by fmd12345** [comment]
想请问下ttocr应该怎么配置geetest_url和geetest_params和geetest_data？

**Comment by Night-stars-1** [comment]
本项目未提供任何有关ttocr的服务以及内容，本项目不对用户个人行为负任何责任。
这不是bug而且我们不会去处理
