### ISSUE TITLE
cryptography==41.0.5 和orjson==3.9.10 依赖装不上求大神请教

### ISSUE THREAD

**Issue by Golven-8964** [0-8-4/miui-auto-tasks#215]
### Verify Steps

- [ ] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

V1.6.0.1

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.7

### Describe the Bug

青龙v2.11.3版本
系统:玩客云Armbian 20.12 Buster
架构armv7l
Python 3.7.3
 pip 23.3.1 

### MIUITask Log

Collecting cryptography==41.0.5 (from -r requirements.txt (line 2))
  Using cached cryptography-41.0.5.tar.gz (630 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error
  
  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [87 lines of output]
      Collecting setuptools>=61.0.0
        Using cached setuptools-68.0.0-py3-none-any.whl.metadata (6.4 kB)
      Collecting wheel
        Using cached wheel-0.42.0-py3-none-any.whl.metadata (2.2 kB)
      Collecting cffi>=1.12
        Using cached cffi-1.15.1.tar.gz (508 kB)
        Preparing metadata (setup.py): started
        Preparing metadata (setup.py): finished with status 'done'
      Collecting setuptools-rust>=0.11.4
        Using cached setuptools_rust-1.7.0-py3-none-any.whl.metadata (4.8 kB)
      Collecting pycparser (from cffi>=1.12)
        Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
      Collecting semantic-version<3,>=2.8.2 (from setuptools-rust>=0.11.4)
        Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
      Collecting typing-extensions>=3.7.4.3 (from setuptools-rust>=0.11.4)
        Using cached typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
      Collecting tomli>=1.2.1 (from setuptools-rust>=0.11.4)
        Using cached tomli-2.0.1-py3-none-any.whl (12 kB)
      Using cached setuptools-68.0.0-py3-none-any.whl (804 kB)
      Using cached wheel-0.42.0-py3-none-any.whl (65 kB)
      Using cached setuptools_rust-1.7.0-py3-none-any.whl (25 kB)
      Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
      Building wheels for collected packages: cffi
        Building wheel for cffi (setup.py): started
        Building wheel for cffi (setup.py): finished with status 'error'
        error: subprocess-exited-with-error
      
        × python setup.py bdist_wheel did not run successfully.
        │ exit code: 1
        ╰─> [50 lines of output]
            /usr/local/lib/python3.7/dist-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
            !!
      
                    ********************************************************************************
                    The license_file parameter is deprecated, use license_files instead.
      
                    This deprecation is overdue, please update your project and remove deprecated
                    calls to avoid build errors in the future.
      
                    See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                    ********************************************************************************
      
            !!
              parsed = self.parsers.get(option_name, lambda x: x)(value)
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-armv7l-cpython-37
            creating build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/verifier.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/vengine_gen.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/recompiler.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/pkgconfig.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/model.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/lock.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/ffiplatform.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/error.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/cparser.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/commontypes.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/api.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/__init__.py -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/_cffi_include.h -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/parse_c_type.h -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/_embedding.h -> build/lib.linux-armv7l-cpython-37/cffi
            copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-cpython-37/cffi
            running build_ext
            building '_cffi_backend' extension
            creating build/temp.linux-armv7l-cpython-37
            creating build/temp.linux-armv7l-cpython-37/c
            arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -flto -fuse-linker-plugin -ffat-lto-objects -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.7m -c c/_cffi_backend.c -o build/temp.linux-armv7l-cpython-37/c/_cffi_backend.o
            c/_cffi_backend.c:2:10: fatal error: Python.h: No such file or directory
             #include <Python.h>
                      ^~~~~~~~~~
            compilation terminated.
            error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
        Running setup.py clean for cffi
      Failed to build cffi
      ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

### Screenshots

![屏幕截图 2023-11-27 054049](https://github.com/0-8-4/miui-auto-tasks/assets/71271253/70f4a605-633b-4f2b-8fa6-e430207c5c71)

![屏幕截图 2023-11-27 054220](https://github.com/0-8-4/miui-auto-tasks/assets/71271253/9e15d16f-6ca6-4fc7-b8ee-96afb395f472)

**Comment by Night-stars-1** [comment]
Tracker 我已经在 Issue Tracker 中找过我要提出的问题
