### ISSUE TITLE
请问完全不会 Python 需要怎么执行？

### ISSUE THREAD

**Issue by zwjtano** [0-8-4/miui-auto-tasks#22]

**Comment by Xunflash** [comment]
你可以百度试试

**Comment by 0-8-4** [comment]
*No description provided.*

**Comment by zwjtano** [comment]
> 你可以百度试试

可以大致说下吗，谢谢

**Comment by 17603443442** [comment]
> > 你可以百度试试
> 
> 可以大致说下吗，谢谢

具体情况具体分析了，还得看错误代码是啥了， 最好是自己拿着错误代码去百度。

**Comment by ghost** [comment]
Windows 平台可以下载最新版本 [Release](https://github.com/0-8-4/miui-auto-tasks/releases/latest/download/miui-auto-tasks-v1.3.2-fix-windows-amd64.7z)  
根据 README.md 的 [使用说明](https://github.com/0-8-4/miui-auto-tasks#%E4%BD%BF%E7%94%A8%E8%AF%B4%E6%98%8E) 配置 config.env

**Comment by zwjtano** [comment]
搜索csdn解决了
