### ISSUE TITLE
遇到人机验证码怎么解决？

### ISSUE THREAD

**Issue by 1505194659** [0-8-4/miui-auto-tasks#223]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

1.6.0.1

### Bug Found in Environment

Linux, Docker

### Bug Found in Python Version

3.7

## 开始执行... 2023-12-02 09:12:14

[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m13[0m - [1mMIUI-AUTO-TASK v1.7.2[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m14[0m - [1m---------- 系统信息 -------------[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m25[0m - [1m操作系统平台: Linux-5.10.134-15.2.al8.x86_64-x86_64-with[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m26[0m - [1m操作系统版本: #1 SMP Thu Sep 14 03:42:13 UTC 2023[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m27[0m - [1m操作系统名称: Linux[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m28[0m - [1m操作系统位元: ('64bit', '')[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m29[0m - [1m操作系统类型: x86_64[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m30[0m - [1m处理器信息: [0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m31[0m - [1mPython 版本: 3.10.11 ('main', 'May 11 2023 23:39:48')[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m16[0m - [1m---------- 项目信息 -------------[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m17[0m - [1m这是一个免费且开源的项目，如果你是付费购买获得请务必退款[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m18[0m - [1m项目地址：https://github.com/0-8-4/miui-auto-tasks[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m19[0m - [1m欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m20[0m - [1m---------- 脚本日志 -------------[0m
[32m09:12:15[0m - [1mINFO [0m | [36mlogin[0m.[36mlogin[0m:[36m84[0m - [1mCookie有效，跳过登录[0m
[32m09:12:15[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token[0m:[36m227[0m - [31m[1m遇到人机验证码, 尝试调用解决方案[0m
[32m09:12:15[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token_by_captcha[0m:[36m124[0m - [31m[1m遇到人机验证码，无法获取TOKEN[0m
[32m09:12:16[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token[0m:[36m227[0m - [31m[1m遇到人机验证码, 尝试调用解决方案[0m
[32m09:12:16[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token_by_captcha[0m:[36m124[0m - [31m[1m遇到人机验证码，无法获取TOKEN[0m
[32m09:12:16[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token[0m:[36m234[0m - [31m[1m遇到未知错误，无法获取TOKEN[0m
[32m09:12:16[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m34[0m - [1m开始执行抢先体验小米澎湃OS！任务[0m
[32m09:12:16[0m - [31m[1mERROR[0m | [36mmiuitask[0m.[36mmain[0m:[36m41[0m - [31m[1m未找到抢先体验小米澎湃OS！任务[0m
[32m09:12:16[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m34[0m - [1m开始执行每日签到任务[0m
[32m09:12:16[0m - [1mINFO [0m | [36msign[0m.[36msign[0m:[36m79[0m - [1m未获取到token, 跳过每日签到[0m
[32m09:12:16[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m43[0m - [1m浏览帖子超过10秒任务已完成[0m
[32m09:12:16[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m34[0m - [1m开始执行参与拔萝卜获得奖励任务[0m
[32m09:12:17[0m - [32m[1mSUCCESS[0m | [36msign[0m.[36msign[0m:[36m91[0m - [32m[1m参与拔萝卜获得奖励结果: ok[0m
[32m09:12:17[0m - [31m[1mERROR[0m | [36mrequest[0m.[36mnotify_me[0m:[36m74[0m - [31m[1m未配置推送或未正确配置推送[0m

## 开始执行... 2023-12-02 09:12:14

[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m13[0m - [1mMIUI-AUTO-TASK v1.7.2[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m14[0m - [1m---------- 系统信息 -------------[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m25[0m - [1m操作系统平台: Linux-5.10.134-15.2.al8.x86_64-x86_64-with[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m26[0m - [1m操作系统版本: #1 SMP Thu Sep 14 03:42:13 UTC 2023[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m27[0m - [1m操作系统名称: Linux[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m28[0m - [1m操作系统位元: ('64bit', '')[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m29[0m - [1m操作系统类型: x86_64[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m30[0m - [1m处理器信息: [0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m31[0m - [1mPython 版本: 3.10.11 ('main', 'May 11 2023 23:39:48')[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m16[0m - [1m---------- 项目信息 -------------[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m17[0m - [1m这是一个免费且开源的项目，如果你是付费购买获得请务必退款[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m18[0m - [1m项目地址：https://github.com/0-8-4/miui-auto-tasks[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m19[0m - [1m欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m20[0m - [1m---------- 脚本日志 -------------[0m
[32m09:12:15[0m - [1mINFO [0m | [36mlogin[0m.[36mlogin[0m:[36m84[0m - [1mCookie有效，跳过登录[0m
[32m09:12:15[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token[0m:[36m227[0m - [31m[1m遇到人机验证码, 尝试调用解决方案[0m
[32m09:12:15[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token_by_captcha[0m:[36m124[0m - [31m[1m遇到人机验证码，无法获取TOKEN[0m
[32m09:12:16[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token[0m:[36m227[0m - [31m[1m遇到人机验证码, 尝试调用解决方案[0m
[32m09:12:16[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token_by_captcha[0m:[36m124[0m - [31m[1m遇到人机验证码，无法获取TOKEN[0m
[32m09:12:16[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token[0m:[36m234[0m - [31m[1m遇到未知错误，无法获取TOKEN[0m
[32m09:12:16[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m34[0m - [1m开始执行抢先体验小米澎湃OS！任务[0m
[32m09:12:16[0m - [31m[1mERROR[0m | [36mmiuitask[0m.[36mmain[0m:[36m41[0m - [31m[1m未找到抢先体验小米澎湃OS！任务[0m
[32m09:12:16[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m34[0m - [1m开始执行每日签到任务[0m
[32m09:12:16[0m - [1mINFO [0m | [36msign[0m.[36msign[0m:[36m79[0m - [1m未获取到token, 跳过每日签到[0m
[32m09:12:16[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m43[0m - [1m浏览帖子超过10秒任务已完成[0m
[32m09:12:16[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m34[0m - [1m开始执行参与拔萝卜获得奖励任务[0m
[32m09:12:17[0m - [32m[1mSUCCESS[0m | [36msign[0m.[36msign[0m:[36m91[0m - [32m[1m参与拔萝卜获得奖励结果: ok[0m
[32m09:12:17[0m - [31m[1mERROR[0m | [36mrequest[0m.[36mnotify_me[0m:[36m74[0m - [31m[1m未配置推送或未正确配置推送[0m

### MIUITask Config

```shell
## 开始执行... 2023-12-02 09:12:14

[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m13[0m - [1mMIUI-AUTO-TASK v1.7.2[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m14[0m - [1m---------- 系统信息 -------------[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m25[0m - [1m操作系统平台: Linux-5.10.134-15.2.al8.x86_64-x86_64-with[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m26[0m - [1m操作系统版本: #1 SMP Thu Sep 14 03:42:13 UTC 2023[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m27[0m - [1m操作系统名称: Linux[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m28[0m - [1m操作系统位元: ('64bit', '')[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m29[0m - [1m操作系统类型: x86_64[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m30[0m - [1m处理器信息: [0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m31[0m - [1mPython 版本: 3.10.11 ('main', 'May 11 2023 23:39:48')[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m16[0m - [1m---------- 项目信息 -------------[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m17[0m - [1m这是一个免费且开源的项目，如果你是付费购买获得请务必退款[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m18[0m - [1m项目地址：https://github.com/0-8-4/miui-auto-tasks[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m19[0m - [1m欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人[0m
[32m09:12:15[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m20[0m - [1m---------- 脚本日志 -------------[0m
[32m09:12:15[0m - [1mINFO [0m | [36mlogin[0m.[36mlogin[0m:[36m84[0m - [1mCookie有效，跳过登录[0m
[32m09:12:15[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token[0m:[36m227[0m - [31m[1m遇到人机验证码, 尝试调用解决方案[0m
[32m09:12:15[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token_by_captcha[0m:[36m124[0m - [31m[1m遇到人机验证码，无法获取TOKEN[0m
[32m09:12:16[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token[0m:[36m227[0m - [31m[1m遇到人机验证码, 尝试调用解决方案[0m
[32m09:12:16[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token_by_captcha[0m:[36m124[0m - [31m[1m遇到人机验证码，无法获取TOKEN[0m
[32m09:12:16[0m - [31m[1mERROR[0m | [36mutils[0m.[36mget_token[0m:[36m234[0m - [31m[1m遇到未知错误，无法获取TOKEN[0m
[32m09:12:16[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m34[0m - [1m开始执行抢先体验小米澎湃OS！任务[0m
[32m09:12:16[0m - [31m[1mERROR[0m | [36mmiuitask[0m.[36mmain[0m:[36m41[0m - [31m[1m未找到抢先体验小米澎湃OS！任务[0m
[32m09:12:16[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m34[0m - [1m开始执行每日签到任务[0m
[32m09:12:16[0m - [1mINFO [0m | [36msign[0m.[36msign[0m:[36m79[0m - [1m未获取到token, 跳过每日签到[0m
[32m09:12:16[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m43[0m - [1m浏览帖子超过10秒任务已完成[0m
[32m09:12:16[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m34[0m - [1m开始执行参与拔萝卜获得奖励任务[0m
[32m09:12:17[0m - [32m[1mSUCCESS[0m | [36msign[0m.[36msign[0m:[36m91[0m - [32m[1m参与拔萝卜获得奖励结果: ok[0m
[32m09:12:17[0m - [31m[1mERROR[0m | [36mrequest[0m.[36mnotify_me[0m:[36m74[0m - [31m[1m未配置推送或未正确配置推送[0m


## 执行结束... 2023-12-02 09:12:17  耗时 3 秒　　　　　
```

**Comment by klcb2010** [comment]
自己搭建大码平台 这不是bug
