### ISSUE TITLE
建议修改一下readme，1.7.3版本要把config放在data目录下

### ISSUE THREAD

**Issue by Nuero987** [0-8-4/miui-auto-tasks#231]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.3

### Bug Found in Environment

Windows

### Bug Found in Python Version

3.11

### Describe the Bug

readme里面还是
“快速上手：
配置好 config.yaml 文件，并与 miuitask.py 文件放在同一个目录下
使用终端 在 miuitask.py 所在目录下运行如下命令：
python3 miuitask.py”

### MIUITask Log

11:23:52 - INFO  | system_info.print_info:13 - MIUI-AUTO-TASK v1.7.3
11:23:52 - INFO  | system_info.print_info:14 - ---------- 系统信息 -------------
11:23:52 - INFO  | system_info.system_info:25 - 操作系统平台: Windows-10-10.0.19045-SP0
11:23:52 - INFO  | system_info.system_info:26 - 操作系统版本: 10.0.19045
11:23:52 - INFO  | system_info.system_info:27 - 操作系统名称: Windows
11:23:52 - INFO  | system_info.system_info:28 - 操作系统位元: ('64bit', 'WindowsPE')
11:23:52 - INFO  | system_info.system_info:29 - 操作系统类型: AMD64
11:23:52 - INFO  | system_info.system_info:30 - 处理器信息: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
11:23:52 - INFO  | system_info.system_info:31 - Python 版本: 3.11.3 ('tags/v3.11.3:f3909b8', 'Apr  4 2023 23:49:59')
11:23:52 - INFO  | system_info.print_info:16 - ---------- 项目信息 -------------
11:23:52 - INFO  | system_info.print_info:17 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
11:23:52 - INFO  | system_info.print_info:18 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
11:23:52 - INFO  | system_info.print_info:19 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
11:23:52 - INFO  | system_info.print_info:20 - ---------- 脚本日志 -------------
11:23:52 - DEBUG | login.login:87 - &&&START&&&{"qs":"%3Fcallback%3Dhttp%253A%252F%252Fapi.vip.miui.com%252Fsts%253Fsign%253D4II4ABwZkiJzkd2YSkyEZukI4Ak%25253D%2526followup%253Dhttps%25253A%25252F%25252Fapi.vip.miui.com%25252Fpage%25252Flogin%25253FdestUrl%25253Dhttps%2525253A%2525252F%2525252Fweb.vip.miui.com%2525252Fpage%2525252Finfo%2525252Fmio%2525252Fmio%2525252FinternalTest%2525253Fref%2525253Dhomepage%26sid%3Dmiui_vip","code":70016,"description":"登录验证失败","securityStatus":0,"_sign":"L+dSQY6sjSQ/CRjJs4p+U1vNYLY=","sid":"miui_vip","result":"error","captchaUrl":null,"callback":"http://api.vip.miui.com/sts?sign=4II4ABwZkiJzkd2YSkyEZukI4Ak%3D&followup=https%3A%2F%2Fapi.vip.miui.com%2Fpage%2Flogin%3FdestUrl%3Dhttps%253A%252F%252Fweb.vip.miui.com%252Fpage%252Finfo%252Fmio%252Fmio%252FinternalTest%253Fref%253Dhomepage","location":"","pwd":0,"child":0,"desc":"登录验证失败"}
11:23:52 - ERROR | login.login:102 - 小米账号登录失败：用户名或密码不正确
11:23:52 - ERROR | request.notify_me:74 - 未配置推送或未正确配置推送

**Comment by Night-stars-1** [comment]
#232

**Comment by ni-feng-le** [comment]
以前日志看一下哪里不对，还是没有签到成功，cookie是小米社区网页版的
****
MIUI-Auto-Task
## 开始执行... 2023-12-07 17:43:02

[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m13[0m - [1mMIUI-AUTO-TASK v1.7.3[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m14[0m - [1m---------- 系统信息 -------------[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m25[0m - [1m操作系统平台: Linux-3.10.0-1160.el7.x86_64-x86_64-with[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m26[0m - [1m操作系统版本: #1 SMP Mon Oct 19 16:18:59 UTC 2020[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m27[0m - [1m操作系统名称: Linux[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m28[0m - [1m操作系统位元: ('64bit', '')[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m29[0m - [1m操作系统类型: x86_64[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m30[0m - [1m处理器信息: [0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36msystem_info[0m:[36m31[0m - [1mPython 版本: 3.10.11 ('main', 'May 11 2023 23:39:48')[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m16[0m - [1m---------- 项目信息 -------------[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m17[0m - [1m这是一个免费且开源的项目，如果你是付费购买获得请务必退款[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m18[0m - [1m项目地址：https://github.com/0-8-4/miui-auto-tasks[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m19[0m - [1m欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人[0m
[32m17:43:03[0m - [1mINFO [0m | [36msystem_info[0m.[36mprint_info[0m:[36m20[0m - [1m---------- 脚本日志 -------------[0m
[32m17:43:04[0m - [1mINFO [0m | [36mlogin[0m.[36mlogin[0m:[36m84[0m - [1mCookie有效，跳过登录[0m
[32m17:43:04[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m33[0m - [1m开始执行抢先体验小米澎湃OS！任务[0m
[32m17:43:04[0m - [31m[1mERROR[0m | [36mmiuitask[0m.[36mmain[0m:[36m41[0m - [31m[1m未找到抢先体验小米澎湃OS！任务[0m
[32m17:43:04[0m - [1mINFO [0m | [36mmiuitask[0m.[36mmain[0m:[36m33[0m - [1m开始执行每日签到任务[0m
Traceback (most recent call last):
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 48, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 36, in main
    token = await get_token(cookies["cUserId"]) if task_obj == CheckIn else None
KeyError: 'cUserId'


## 执行结束... 2023-12-07 17:43:04  耗时 2 秒

**Comment by Night-stars-1** [comment]
> 以前日志看一下哪里不对，还是没有签到成功，cookie是小米社区网页版的

#228
