### ISSUE TITLE
遇到人机验证码

### ISSUE THREAD

**Issue by runishiwo** [0-8-4/miui-auto-tasks#235]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

V1.7.3

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.11

### Describe the Bug

遇到人机验证码,
我用linux本身浏览器登录小米社区，直接就登录上了，也没让验证什么的

### MIUITask Log

09:58:58 - INFO  | system_info.print_info:13 - MIUI-AUTO-TASK v1.7.3
09:58:58 - INFO  | system_info.print_info:14 - ---------- 系统信息 -------------
09:58:58 - INFO  | system_info.system_info:25 - 操作系统平台: Linux-6.1.0-13-amd64-x86_64-with
09:58:58 - INFO  | system_info.system_info:26 - 操作系统版本: #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29)
09:58:58 - INFO  | system_info.system_info:27 - 操作系统名称: Linux
09:58:58 - INFO  | system_info.system_info:28 - 操作系统位元: ('64bit', 'ELF')
09:58:58 - INFO  | system_info.system_info:29 - 操作系统类型: x86_64
09:58:58 - INFO  | system_info.system_info:30 - 处理器信息: 
09:58:58 - INFO  | system_info.system_info:31 - Python 版本: 3.10.13 ('main', 'Oct 19 2023 06:08:04')
09:58:58 - INFO  | system_info.print_info:16 - ---------- 项目信息 -------------
09:58:58 - INFO  | system_info.print_info:17 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
09:58:58 - INFO  | system_info.print_info:18 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
09:58:58 - INFO  | system_info.print_info:19 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
09:58:58 - INFO  | system_info.print_info:20 - ---------- 脚本日志 -------------
09:58:59 - SUCCESS | login.login:80 - 小米账号登录成功
09:58:59 - INFO  | miuitask.main:33 - 开始执行抢先体验小米澎湃OS！任务
09:58:59 - ERROR | miuitask.main:41 - 未找到抢先体验小米澎湃OS！任务
09:58:59 - INFO  | miuitask.main:33 - 开始执行每日签到任务
09:58:59 - ERROR | utils.get_token:227 - 遇到人机验证码, 尝试调用解决方案
09:59:00 - ERROR | utils.get_token_by_captcha:124 - 遇到人机验证码，无法获取TOKEN
09:59:00 - ERROR | utils.get_token:234 - 遇到未知错误，无法获取TOKEN
09:59:00 - INFO  | sign.sign:87 - 未获取到token, 跳过每日签到
09:59:00 - INFO  | miuitask.main:43 - 浏览帖子超过10秒任务已完成
09:59:00 - INFO  | miuitask.main:33 - 开始执行参与拔萝卜获得奖励任务
09:59:00 - INFO  | miuitask.main:39 - 任务参与拔萝卜获得奖励被禁用
09:59:00 - ERROR | request.notify_me:74 - 未配置推送或未正确配置推送

**Comment by Night-stars-1** [comment]
提问前先阅读社区规则
