### ISSUE TITLE
[Bug] cookie失效后去修改配置文件data/config.yaml的重要问题

### ISSUE THREAD

**Issue by YiChen2025** [0-8-4/miui-auto-tasks#237]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.1

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.11

### Describe the Bug

cookie失效后去修改配置文件data/config.yaml的重要问题
小米社区ck失效去更新ck，修改更新ck保存后去运行脚本看是否正常，却提示错误
目前解决方案：需删除整个脚本重新拉库填写账号解决

### MIUITask Log

[日志log.txt](https://github.com/0-8-4/miui-auto-tasks/files/13624397/log.txt)

### Screenshots

![Screenshot_2023-12-09-22-20-58-560_mark via](https://github.com/0-8-4/miui-auto-tasks/assets/80463727/02511c0f-f696-4156-bb0c-09df1be8453d)

**Comment by Night-stars-1** [comment]
更新脚本

**Comment by YiChen2025** [comment]
> 更新脚本

看图，反复拉库一直网络不行，挂梯子不挂梯子也一样
![Screenshot_2023-12-09-22-47-58-927_com android browser](https://github.com/0-8-4/miui-auto-tasks/assets/80463727/29fea823-d9b0-4bf1-9461-355729848c2b)
![Screenshot_2023-12-09-22-48-58-092_com android browser](https://github.com/0-8-4/miui-auto-tasks/assets/80463727/0b2a650f-f121-4982-81d9-78e4be508b63)

**Comment by Night-stars-1** [comment]
> > 更新脚本
> 
> 看图，反复拉库一直网络不行，挂梯子不挂梯子也一样 !

这是你自己的问题，不是bug
