### ISSUE TITLE
[Bug] 修改配置文件data/config.yaml问题

### ISSUE THREAD

**Issue by YiChen2025** [0-8-4/miui-auto-tasks#238]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.1

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.11

### Describe the Bug

当cookie失效后或者进行第二次修改配置文件data/config.yaml的重要问题
已拉库最新脚本也一样，拉库填写保存后执行脚本正常，然后再去修改保存配置文件，就会提示错误，无法进行二次修改保存
小米社区ck失效去更新ck，修改更新ck保存后去运行脚本看是否正常，却提示错误，如图所示，并未修复bug
目前解决方案：需删除整个脚本重新拉库执行环境脚本后填写账号解决

### MIUITask Log

[日志log.txt](https://github.com/0-8-4/miui-auto-tasks/files/13624921/log.txt)

### Screenshots

![Screenshot_2023-12-10-00-18-22-756_com android browser](https://github.com/0-8-4/miui-auto-tasks/assets/80463727/a1819b5b-7abc-4a50-8402-c5bd40e0d936)

**Comment by YiChen2025** [comment]
当拉库新脚本后，再去执行完环境配置，配置文件出来后进行首次修改填写账号信息，为首次修改保存，然后经过测试，再去进行修改配置文件保存后去执行脚本测试是否正常运行，将直接提示错误。

【08:30:02 - ERROR | config.load_config:165 - 读取数据文件失败，请检查数据文件 /ql/data/scripts/0-8-4_miui-auto-tasks_master/data/config.yaml 格式是否正确
![Screenshot_2023-12-10-00-18-22-756_com android browser](https://github.com/0-8-4/miui-auto-tasks/assets/80463727/d1b95d10-59ca-43b6-8e79-7de34063246c)
】

**Comment by YiChen2025** [comment]
> 当拉库新脚本后，再去执行完环境配置，配置文件出来后进行首次修改填写账号信息，为首次修改保存，然后经过测试，再去进行修改配置文件保存后去执行脚本测试是否正常运行，将直接提示错误。
> 
> 【08:30:02 - ERROR | config.load_config:165 - 读取数据文件失败，请检查数据文件 /ql/data/scripts/0-8-4_miui-auto-tasks_master/data/config.yaml 格式是否正确 ![Screenshot_2023-12-10-00-18-22-756_com android browser](https://private-user-images.githubusercontent.com/80463727/289286783-d1b95d10-59ca-43b6-8e79-7de34063246c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzkzOTIsIm5iZiI6MTcwMjEzOTA5MiwicGF0aCI6Ii84MDQ2MzcyNy8yODkyODY3ODMtZDFiOTVkMTAtNTljYS00M2I2LThlNzktN2RlMzQwNjMyNDZjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDE2MjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1NjQ1NGEzYmY2YTM5MzcwYjdjMTMyOTk1OWMxNDUyMWQxMjMzNmI3ZTBjNGI3MjE2MTlhMDU5NDU2NTM0ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F98v2V_NIAdgagFIGBDSyPkQ0yxasrSFcJvgtCwfceA) 】

格式都是正确的，已反复确认过仍然出现此问题无法进行二次修改操作

**Comment by Night-stars-1** [comment]
你拿个8:00的log，反馈00:00发生的问题，有意思吗？
你这个问题最新版已经修复，删除配置文件重新配置
