### ISSUE TITLE
能运行但显示出错

### ISSUE THREAD

**Issue by mojing122** [0-8-4/miui-auto-tasks#24]
13:30:18 | ----------系统信息-开始-------------
13:30:18 | 系统及版本信息: Windows-10-10.0.22449-SP0
13:30:18 | 系统版本号: 10.0.22449
13:30:18 | 系统名称: Windows
13:30:18 | 系统位数: ('64bit', 'WindowsPE')
13:30:18 | 计算机类型: AMD64
13:30:18 | 处理器类型: AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
13:30:18 | Python版本: 3.9.0 ('tags/v3.9.0:9cf6752', 'Oct  5 2020 15:34:40')
13:30:18 | 系统代理: {'http': 'http://127.0.0.1:7890', 'https': 'https://127.0.0.1:7890', 'ftp': 'ftp://127.0.0.1:7890'}
13:30:18 | ----------系统信息-结束-------------
13:30:18 | 项目地址：https://github.com/0-8-4/miui-auto-tasks
13:30:18 | 欢迎star，感谢東雲研究所中的大佬
13:30:18 | ----------检测配置文件-------------
13:30:18 | .env 已配置
13:30:18 | ----------------------------------
13:30:18 | 开始登录小米账号
13:30:37 | 账号登录完成
13:30:37 | 本脚本支持社区签到，因该功能存在风险默认禁用
13:30:37 | 如您愿意承担一切可能的后果，可编辑配置文件手动打开该功能
13:30:37 | 风社险功能提示：正在进行区签到
13:30:37 | 社区拔萝卜签到出错
13:30:37 | 开始活跃分任务出错
13:30:37 | 正在完成BUG反馈任务
13:30:37 | 发表内容出错
13:30:37 | 3秒后执行提建议任务
13:30:37 | 领取活跃分出错
13:30:40 | 正在完成提建议任务
13:30:40 | 发表内容出错
13:30:40 | 正在完成满意度调查任务
13:30:40 | 获取问卷ID出错，满意度投票失败
13:30:40 | 正在完成点赞任务
13:30:40 | 开始活跃分任务出错
13:30:40 | 点赞出错
13:30:40 | 取消点赞出错
13:30:41 | 点赞出错

大佬这个出错怎么解

**Comment by mojing122** [comment]
手机上用Termux跑成功了

**Comment by TardisXE** [comment]
请检查是否使用了网络代理程序

**Comment by mojing122** [comment]
哦哦没注意 有用了  感谢
