### ISSUE TITLE
大号被封了。

### ISSUE THREAD

**Issue by mymine** [0-8-4/miui-auto-tasks#242]
大号已经被封了。

**Comment by 0-8-4** [comment]
好家伙，官方要开始动手了么🥲

**Comment by koolcandy** [comment]
@0-8-4

**Comment by mymine** [comment]
> 好家伙，官方要开始动手了么🥲

不清楚，挂了两个账号，大号提示小米社区访问受限请过几天再访问。小号屁事没有。

**Comment by koolcandy** [comment]
@mymine 请求次数过多了？设置随机运行试一下

**Comment by mymine** [comment]
> @mymine 请求次数过多了？设置随机运行试一下

一天就搞一次。两个号码，大号限制了，小号没事

**Comment by Night-stars-1** [comment]
不太可能是因为这个，我用来开发的号都没事

**Comment by mymine** [comment]
> 不太可能是因为这个，我用来开发的号都没事

那就不清楚了。

**Comment by klcb2010** [comment]
@mymine 我也没收到这个提醒

**Comment by koolcandy** [comment]
@klcb2010 不会是ip横跳的问题吧

**Comment by Pandaver** [comment]
我这边境外服务器，12个号，挂了有半个月也没事

**Comment by 0-8-4** [comment]
@Pandaver 好家伙 12个号？

**Comment by mymine** [comment]
> 我这边境外服务器，12个号，挂了有半个月也没事

都登录小米社区APP试试。我又没说签到脚本报错。

**Comment by mymine** [comment]
妈的，大号被封了。不会再买小米了。

**Comment by koolcandy** [comment]
@mymine 是海外ip吗

**Comment by klcb2010** [comment]
@mymine 是不是IP地址变化了？

**Comment by mymine** [comment]
> @mymine 是不是IP地址变化了？

不清楚海外IP会被封号？没有给原因

**Comment by koolcandy** [comment]
@mymine 发邮件问问看，封号理由是什么

**Comment by mymine** [comment]
> @mymine 发邮件问问看，封号理由是什么

刚发了，等回复
