### ISSUE TITLE
极验收费万象可以接入吗？

### ISSUE THREAD

**Issue by mymine** [0-8-4/miui-auto-tasks#249]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 MIUITask 并不包含该功能特性或者还不完善
- [X] Framework 这是 MIUITask 应包含的特性, 并非实现社区外功能
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

none

### Describe the Solution

none

### Describe Alternatives

none

### Additional Context

none

**Comment by Night-stars-1** [comment]
根据社区规则(#228) 该issue锁定处理
