### ISSUE TITLE
1.3运行一下就闪退了

### ISSUE THREAD

**Issue by kennylee60** [0-8-4/miui-auto-tasks#25]
之前的版本不会，什么问题吗

**Comment by TardisXE** [comment]
请检查1.3版本所依赖的配置文件和其他脚本是否在同一个文件夹内

**Comment by kennylee60** [comment]
放在同一个文件夹的，用回1.22就不会

**Comment by 0-8-4** [comment]
请问是1.3还是1.3.1

**Comment by 0-8-4** [comment]
> 放在同一个文件夹的，用回1.22就不会

1.3和1.2不兼容。需要重新配置

**Comment by kennylee60** [comment]
> 请问是1.3还是1.3.1

1.3，这个1.3.1又是什么时候更新的

**Comment by 0-8-4** [comment]
1.3版本的使用需要参考readme重新配置

**Comment by kennylee60** [comment]
> 1.3版本的使用需要参考readme重新配置
不就是改env吗，miuitask.py这个不用改的吧
整个项目都改动了，所以需要重新配置。用回原文件 肯定是不行的

**Comment by 0-8-4** [comment]
> 
> > 1.3版本的使用需要参考readme重新配置
> 不就是改env吗，miuitask.py这个不用改的吧
整个项目都改动了，所以需要重新配置。用回原文件 肯定是不行的

**Comment by 0-8-4** [comment]
> > 1.3版本的使用需要参考readme重新配置

> 不就是改env吗，miuitask.py这个不用改的吧

整个项目都改动了，所以需要重新配置。用回原文件 肯定是不行的

**Comment by kennylee60** [comment]
> > > 1.3版本的使用需要参考readme重新配置
> 
> > 不就是改env吗，miuitask.py这个不用改的吧
> 
> 整个项目都改动了，所以需要重新配置。用回原文件 肯定是不行的

miuitask.py这个里面需要配置吗，我就配置了env，其他文件都是新文件

**Comment by 0-8-4** [comment]
> > > > 1.3版本的使用需要参考readme重新配置
> > 
> > > 不就是改env吗，miuitask.py这个不用改的吧
> > 
> > 整个项目都改动了，所以需要重新配置。用回原文件 肯定是不行的
> 
> miuitask.py这个里面需要配置吗，我就配置了env，其他文件都是新文件

我一开始可能误解你的意思，你是说。全部文件你都是重新下的么？

**Comment by kennylee60** [comment]
> > > 1.3版本的使用需要参考readme重新配置
> 
> > 不就是改env吗，miuitask.py这个不用改的吧
> 
> 整个项目都改动了，所以需要重新配置。用回原文件 肯定是不行的

USER_AGENT和原来的UA是同一个概念吗

**Comment by kennylee60** [comment]
> > > > > 1.3版本的使用需要参考readme重新配置
> > > 
> > > 
> > > > 不就是改env吗，miuitask.py这个不用改的吧
> > > 
> > > 
> > > 整个项目都改动了，所以需要重新配置。用回原文件 肯定是不行的
> > 
> > 
> > miuitask.py这个里面需要配置吗，我就配置了env，其他文件都是新文件
> 
> 我一开始可能误解你的意思，你是说。全部文件你都是重新下的么？

对，重新下的，然后env里面改原来的配置

**Comment by 0-8-4** [comment]
> > > > 1.3版本的使用需要参考readme重新配置
> > 
> > > 不就是改env吗，miuitask.py这个不用改的吧
> > 
> > 整个项目都改动了，所以需要重新配置。用回原文件 肯定是不行的
> 
> USER_AGENT和原来的UA是同一个概念吗

是的，是同一个东西

**Comment by 0-8-4** [comment]
话说 你的依赖有没有安装，1.3版本引入了新的依赖

**Comment by 0-8-4** [comment]
[项目依赖](https://github.com/0-8-4/miui-auto-tasks/blob/master/README.md#项目依赖)

**Comment by kennylee60** [comment]
> 话说 你的依赖有没有安装，1.3版本引入了新的依赖



> 话说 你的依赖有没有安装，1.3版本引入了新的依赖

pip install -r requirements.txt吗，装了

**Comment by 0-8-4** [comment]
> > 话说 你的依赖有没有安装，1.3版本引入了新的依赖
> 
> 
> 
> > 话说 你的依赖有没有安装，1.3版本引入了新的依赖
> 
> pip install -r requirements.txt吗，装了

好，知道了

**Comment by 0-8-4** [comment]
@O1Si

**Comment by kennylee60** [comment]
> > > 话说 你的依赖有没有安装，1.3版本引入了新的依赖
> > 
> > 
> > > 话说 你的依赖有没有安装，1.3版本引入了新的依赖
> > 
> > 
> > pip install -r requirements.txt吗，装了
> 
> 好，知道了

继续用着1.2.2了，这个就没问题

**Comment by 0-8-4** [comment]
你是双击运行py文件的么？

还能麻烦你，把配置文件里面的设置日志选项打开。然后把日志复制上来这里，可以么

**Comment by kennylee60** [comment]
> 你是双击运行py文件的么？
> 
> 还能麻烦你，把配置文件里面的设置日志选项打开。然后把日志复制上来这里，可以么

晚上试又可以了，不知道发生什么事

**Comment by 0-8-4** [comment]
用多几天后，没问题请自行关闭
