### ISSUE TITLE
[Bug] 未能正确识别账户和任务

### ISSUE THREAD

**Issue by Agnes4m** [0-8-4/miui-auto-tasks#252]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

git clone最新版本

### Bug Found in Environment

Windows

### Bug Found in Python Version

3.1

### Describe the Bug

登录成功，但是任务提示被禁用，并且没法显示成长值等其他参数，最终无法完成自动化操作。（并不是指的推送功能，而是自动化任务本身）

### MIUITask Log

[日志文件.log](https://github.com/0-8-4/miui-auto-tasks/files/13769600/default.log)

### MIUITask Config

```shell
只修改了uid和password（以自行修改包括ck隐藏信息）
:
    geetest_url: ''
    geetest_params: {}
    geetest_data: {}
accounts:
-   uid: '18888888888'
    password: 6329B9B3F6F59BFDCF7EA4B76167AA9
    cookies:
        cUserId: 4gc9pZ74dDVojS2wBqxq672zQ
        miui_vip_ph: JE892pduwclelo2dVm/A==
        miui_vip_serviceToken: 2BKMwRB8IbWsAlqNmMoElUbvCxI92IKEKjXYJtLl6ZaViq+LylYF3rvGVW8N3+eI3TsqShaiyIg7o8y0WXlnx8Mk+6Q79Sb8Ev57IcM2NwJq9D+2NnzXDjrKcOqiZG3Ez5fnSCSiNRBkGAugjqPcbLvWE7GajIjr3+E3VRZLtIIgKjps95FaIaeYSWBDOPTkZHaYZs6YXK1iEsCxLwiSPP+RfIF/6nXdEBj1xttZLBb0WJxGIIF0KUTRZ1dA2vZButCYskr1VpMBV+178bL4+7ytx4wDfKpnIhSZg8=
        miui_vip_slh: TQocly7cna99DMWi5uIH5DF8=
    user_agent: Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko)
        Version/4.0 Chrome/116.0.0.0 Safari/537.36
    CheckIn: false
    BrowseUserPage: false
    BrowsePost: false
    ThumbUp: false
    BrowseSpecialPage: false
    BoardFollow: false
    CarrotPull: false
ONEPUSH:
    notifier: ''
    params:
        title: ''
        markdown: false
        token: ''
        userid: ''
```

### Screenshots

![image](https://github.com/0-8-4/miui-auto-tasks/assets/70925546/e6667055-e3ed-439b-a06a-d8801ca29a5a)

**Comment by Night-stars-1** [comment]
https://github.com/0-8-4/miui-auto-tasks/wiki
认真阅读wiki
