### ISSUE TITLE
遇到人机验证码，无法获取TOKEN

### ISSUE THREAD

**Issue by fbc299** [0-8-4/miui-auto-tasks#258]
### Verify Steps

- [ ] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [ ] Need 当前 MIUITask 并不包含该功能特性或者还不完善
- [ ] Framework 这是 MIUITask 应包含的特性, 并非实现社区外功能
- [ ] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

遇到人机验证码，无法获取TOKEN 怎么解决啊？

### Describe the Solution

遇到人机验证码，无法获取TOKEN

**Comment by Night-stars-1** [comment]
#228

**Comment by Night-stars-1** [comment]
不要在公共场合讨论风控内容，想一想为什么会有风控措施
