### ISSUE TITLE
[Bug] 获取TOKEN异常

### ISSUE THREAD

**Issue by zeyudada** [0-8-4/miui-auto-tasks#259]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.4-hotfix4和master都试了

### Bug Found in Environment

Windows

### Bug Found in Python Version

3.11

### Describe the Bug

正确提交challenge和validate后依然报错

### MIUITask Log

19:04:47 - INFO  | system_info.print_info:13 - MIUI-AUTO-TASK v1.7.4
19:04:47 - INFO  | system_info.print_info:14 - ---------- 系统信息 -------------
19:04:47 - INFO  | system_info.system_info:25 - 操作系统平台: Windows-10-10.0.19045-SP0
19:04:47 - INFO  | system_info.system_info:26 - 操作系统版本: 10.0.19045
19:04:47 - INFO  | system_info.system_info:27 - 操作系统名称: Windows
19:04:47 - INFO  | system_info.system_info:28 - 操作系统位元: ('64bit', 'WindowsPE')
19:04:47 - INFO  | system_info.system_info:29 - 操作系统类型: AMD64
19:04:47 - INFO  | system_info.system_info:30 - 处理器信息: Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
19:04:47 - INFO  | system_info.system_info:31 - Python 版本: 3.11.5 ('tags/v3.11.5:cce6ba9', 'Aug 24 2023 14:38:34')
19:04:47 - INFO  | system_info.print_info:16 - ---------- 项目信息 -------------
19:04:47 - INFO  | system_info.print_info:17 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
19:04:47 - INFO  | system_info.print_info:18 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
19:04:47 - INFO  | system_info.print_info:19 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
19:04:47 - INFO  | system_info.print_info:20 - ---------- 脚本日志 -------------
19:04:47 - DEBUG | sign.check_daily_tasks:47 - {"time":0,"message":"success","entity":[{"head":{"img":"https://cdn.cnbj1.fds.api.mi-img.com/vipmlmodel/community_grow_up_level_icon/compression_image/2/levelIconMedium_2s.png?GalaxyAccessKeyId\u003d5151729087601\u0026Expires\u003d9223372036854775807\u0026Signature\u003dLV74sk3qTYqfeNnC4PFPiG4BmLQ%3D","showType":1,"title":"2段 初级成员","jumpText":"","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/growth?skipLocal\u003dtrue","desc":"社区成长等级"},"cakeType":1},{"head":{"img":"https://cdn.cnbj1.fds.api.mi-img.com/vipmlmodel/icons/badge/1/社区勋章_60s.png?GalaxyAccessKeyId\u003dAKU25VNGWI6E4RUEAW\u0026Expires\u003d9223372036854775807\u0026Signature\u003dUId7rM4TsrONiivzGigL4KJYPi0\u003d","showType":1,"title":"全新升级","jumpText":"","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/badge?skipLocal\u003dtrue","desc":"社区勋章"},"cakeType":1},{"head":{"title":"每日任务","jumpText":"查看成长值规则","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/growthRules"},"data":[{"showType":1,"title":"每日签到","jumpText":"","jumpUrl":"","desc":"签到奖励随机，以实际获得为准"},{"showType":1,"title":"浏览帖子超过10秒","jumpText":"去浏览","jumpUrl":"mio://vipaccount.miui.com/main?tab\u003dmio\u0026sub_tab\u003drecommend","desc":"每次成长值+1，每日上限1分"}],"cakeType":2},{"head":{"title":"新手任务","jumpUrl":""},"data":[{"showType":0,"title":"首次完善个人资料","jumpText":"已完成","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/personalInfo","desc":"成长值+10，仅限首次"},{"showType":1,"title":"首次完成实名认证","jumpText":"去完成","jumpUrl":"https://certify.mipay.com/","desc":"成长值+10，仅限首次"}],"cakeType":2},{"head":{"title":"其他任务","jumpText":"更多任务","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/newshop/gold"},"data":[{"showType":1,"title":"参与拔萝卜获得奖励","jumpText":"去看看","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/arrive","desc":"以活动页面为准"}],"cakeType":2}],"status":200}
19:04:47 - INFO  | login.login:75 - Cookie有效，跳过登录
19:04:48 - DEBUG | sign.check_daily_tasks:47 - {"time":0,"message":"success","entity":[{"head":{"img":"https://cdn.cnbj1.fds.api.mi-img.com/vipmlmodel/community_grow_up_level_icon/compression_image/2/levelIconMedium_2s.png?GalaxyAccessKeyId\u003d5151729087601\u0026Expires\u003d9223372036854775807\u0026Signature\u003dLV74sk3qTYqfeNnC4PFPiG4BmLQ%3D","showType":1,"title":"2段 初级成员","jumpText":"","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/growth?skipLocal\u003dtrue","desc":"社区成长等级"},"cakeType":1},{"head":{"img":"https://cdn.cnbj1.fds.api.mi-img.com/vipmlmodel/icons/badge/1/社区勋章_60s.png?GalaxyAccessKeyId\u003dAKU25VNGWI6E4RUEAW\u0026Expires\u003d9223372036854775807\u0026Signature\u003dUId7rM4TsrONiivzGigL4KJYPi0\u003d","showType":1,"title":"全新升级","jumpText":"","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/badge?skipLocal\u003dtrue","desc":"社区勋章"},"cakeType":1},{"head":{"title":"每日任务","jumpText":"查看成长值规则","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/growthRules"},"data":[{"showType":1,"title":"每日签到","jumpText":"","jumpUrl":"","desc":"签到奖励随机，以实际获得为准"},{"showType":1,"title":"浏览帖子超过10秒","jumpText":"去浏览","jumpUrl":"mio://vipaccount.miui.com/main?tab\u003dmio\u0026sub_tab\u003drecommend","desc":"每次成长值+1，每日上限1分"}],"cakeType":2},{"head":{"title":"新手任务","jumpUrl":""},"data":[{"showType":0,"title":"首次完善个人资料","jumpText":"已完成","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/personalInfo","desc":"成长值+10，仅限首次"},{"showType":1,"title":"首次完成实名认证","jumpText":"去完成","jumpUrl":"https://certify.mipay.com/","desc":"成长值+10，仅限首次"}],"cakeType":2},{"head":{"title":"其他任务","jumpText":"更多任务","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/newshop/gold"},"data":[{"showType":1,"title":"参与拔萝卜获得奖励","jumpText":"去看看","jumpUrl":"https://web.vip.miui.com/page/info/mio/mio/arrive","desc":"以活动页面为准"}],"cakeType":2}],"status":200}
19:04:48 - INFO  | miuitask.main:37 - 开始执行每日签到任务
19:04:48 - DEBUG | utils.get_token:225 - {"msg":"","code":0,"data":{"result":false,"id":"5fb5e3461e73419ea7e98e59191c9b83","url":"https://static-verify.sec.xiaomi.com/v2/html/check.html?t=1&k=3dc42a135a8d45118034d1ab68213073&e=rl3NWsL28lB28VjWKBCAzdKbfwFjN0bZey27wMLmoYQ3FZy8Lw%2BUSrmo8%2Fdoi2NMJgWjKQsaGqs6PvUU7YWKF1Ef52WpHrsDH5VkXiZa%2Fx5X0yscHyGcB4FUOh4RywSk29%2BV8pmTpS2f8kFI6wAbjkwnM3UJbr%2Bd40NeTRUH0kHG9x6CzXwt8N%2FXMWLJM14KvpUjGepAg25oQlPsktT03cw7LBPStHFC%2BayOjRzxAjqkSHKQkfzKrxm0LDKKJOmZI1EEVIGn84yFIAf%2F8FHpn1E%2Fh%2FhT7WuZT0HYxoPeDGlrmHADrgESiEzR2a7p1AgwgIW2AP4RD20aFVT7Oe3kJZV%2BbJmAQpaiuJ7hXAr4Ty0%3D&locale=zh_cn&eventId=5fb5e3461e73419ea7e98e59191c9b83&c=8351ae0ef2e0b2afdbafc3c4a2d22e6e&l=3ce0ba3dc870bad65ef6e1344f646242","token":""}}
19:04:48 - ERROR | utils.get_token:231 - 遇到人机验证码, 尝试调用解决方案
19:04:53 - DEBUG | captcha.get_validate:38 - {
  "code": 0,
  "data": {
    "challenge": "3ce0ba3dc870bad65ef6e1344f646242eh",
    "seccode": "86a0fc5a0f0d00785880d288003829cb|jordan",
    "validate": "86a0fc5a0f0d00785880d288003829cb"
  },
  "message": "\u8bc6\u522b\u6210\u529f"
}

19:04:54 - DEBUG | utils.get_token_by_captcha:121 - {"msg":"","code":0,"data":{"result":false,"id":"5fb5e3461e73419ea7e98e59191c9b83"}}
19:04:54 - ERROR | utils.get_token_by_captcha:127 - 遇到人机验证码，无法获取TOKEN
19:04:54 - DEBUG | utils.get_token_by_captcha:128 - {'result': False, 'id': '5fb5e3461e73419ea7e98e59191c9b83'}
19:04:54 - DEBUG | utils.get_token:225 - {"msg":"","code":0,"data":{"result":false,"id":"0b6a372ca5754bf191c84904742b174d","url":"https://static-verify.sec.xiaomi.com/v2/html/check.html?t=1&k=3dc42a135a8d45118034d1ab68213073&e=0dRJwxj76mt13FkgLfCIb4dObLfklqf42%2BwK9G%2BgLx3YxoajLqFG2fJd9ae9XWcNT1J%2Bcjl%2BioZsDSy9SuOnhsuoAPIbgVmz72gnzHpoIC8%2BylkJ26ddvpchSuzzq5wioaSZPytBs3vhDDtSnTgaTIMkWaupioyFZNFHsmMsmr7xHIhJvrHHLv6QRVW8uVuP0uSsjM0ds0OGjjZqllXQq4hKOir5tbpjM2W9i%2BQTkZxv45jzOjbhKIrgH6m4LqipHJVFErHIVpCLFKcv88dJ7uBd8WrLkQgTX27PY9FQ7Noy9LlvP5gzrpjYnw703E8zb8hksWofq0zdb73T3sMEqcjQf9coFSkU5sXweSK0c2E%3D&locale=zh_cn&eventId=0b6a372ca5754bf191c84904742b174d&c=8351ae0ef2e0b2afdbafc3c4a2d22e6e&l=c5022c50ee42cef2cecc6f8fef3e5de6","token":""}}
19:04:54 - ERROR | utils.get_token:231 - 遇到人机验证码, 尝试调用解决方案
19:04:59 - DEBUG | captcha.get_validate:38 - {
  "code": 0,
  "data": {
    "challenge": "c5022c50ee42cef2cecc6f8fef3e5de6bu",
    "seccode": "1c65fb52350e318b7ef1ddaa78d2b824|jordan",
    "validate": "1c65fb52350e318b7ef1ddaa78d2b824"
  },
  "message": "\u8bc6\u522b\u6210\u529f"
}

19:04:59 - DEBUG | utils.get_token_by_captcha:121 - {"msg":"","code":0,"data":{"result":false,"id":"0b6a372ca5754bf191c84904742b174d"}}
19:04:59 - ERROR | utils.get_token_by_captcha:127 - 遇到人机验证码，无法获取TOKEN
19:04:59 - DEBUG | utils.get_token_by_captcha:128 - {'result': False, 'id': '0b6a372ca5754bf191c84904742b174d'}
19:05:00 - DEBUG | utils.get_token:225 - {"msg":"","code":0,"data":{"result":false,"id":"f379db446820487393f1c65e8f9f10ca","url":"https://static-verify.sec.xiaomi.com/v2/html/check.html?t=1&k=3dc42a135a8d45118034d1ab68213073&e=ENx81L79%2FIDlVHb8fOXNaHie07cwrP01WawMSHaTSTcVt8LyEpiUlm6sBUhh9OugZVlQU8fX4UkEC2DvN28Cp50fXi%2FQRtGBF42EOJEO61hNV8eL6%2FOlzpLJLbVEMfIzIWqnMnVtwzSUfdGiv7k7vRYwbl7oRMatwBuhpSN6N7kgNDasG5DtAqVyxqXuo7W%2BG4n19nJ1TUp06qYhn7uvHntq%2Fxsfo9J0rhdkkI6xAHxuVVPQ7txPhGrK8y0aSsOdo16Mm65AUeEMt85rXwapbjEtAl4f%2BrtIPPwFQ%2BQu7BLLWOk%2Bymt5cLimZ3%2BbcQqN%2F9n5BIC4NqbccSkQWoLpKvqV2DPV46LTa3s3c8pHT3I%3D&locale=zh_cn&eventId=f379db446820487393f1c65e8f9f10ca&c=8351ae0ef2e0b2afdbafc3c4a2d22e6e&l=6a41cac618b8bda212e63e4232c02a41","token":""}}
19:05:00 - ERROR | utils.get_token:231 - 遇到人机验证码, 尝试调用解决方案
Ctrl^C 这里被我截停了，要不就得风控了

### MIUITask Config

```shell
preference:
    geetest_url: http://127.0.0.1:8000/ttocr
    geetest_params: {}
    geetest_data:
        token: IkwmQw_HYIW5lCdaG6TunEtzR25AdYGoZtxgviAK9gQ
        gt: '{gt}'
        challenge: '{challenge}'
accounts:
-   uid: '24*******8'
    password: ******
    cookies:
        miui_vip_serviceToken: IA2B******
        miui_vip_slh: 5ApV******
        miui_vip_ph: sTzx******
        cUserId: 6xN8******
    user_agent: Mozilla/5.0 (Linux; Android 14; 23013RK75C Build/UKQ1.230804.001;
        wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43
        Mobile Safari/537.36XiaoMi/HybridView/ app/vipaccount/dev.231217
    CheckIn: true
    BrowseUserPage: true
    BrowsePost: true
    ThumbUp: true
    BrowseSpecialPage: true
    BoardFollow: true
    CarrotPull: true
ONEPUSH:
    notifier: ''
    params:
        title: ''
        markdown: false
        token: ''
        userid: ''
```

**Comment by Night-stars-1** [comment]
#228
