### ISSUE TITLE
每日签到功能异常

### ISSUE THREAD

**Issue by ghost** [0-8-4/miui-auto-tasks#26]
无论在env配置文件中配置为N还是Y，总会运行签到功能。

https://github.com/0-8-4/miui-auto-tasks/blob/0facb2b3f684af92bb584fa326df9337a686a48e/.env#L12-L16
这里config['SIGN_IN']的值总不为None。
https://github.com/0-8-4/miui-auto-tasks/blob/0facb2b3f684af92bb584fa326df9337a686a48e/utils/utils.py#L38-L39
无论上面是否赋值为True，下面的判断条件都是真。
https://github.com/0-8-4/miui-auto-tasks/blob/0facb2b3f684af92bb584fa326df9337a686a48e/miuitask.py#L413-L417

另外，想问一下，如何获取指定用户的id？想自定义关注的用户。

**Comment by TardisXE** [comment]
感谢反馈问题，正在测试修复
