### ISSUE TITLE
docker配置文件没有preference:    hour: <int>     minute: <int>。只有preference:     geetest_url: ''     geetest_params: {}     geetest_data: {}

### ISSUE THREAD

**Issue by 1273294133** [0-8-4/miui-auto-tasks#264]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.4-hotfix2

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.12

### Describe the Bug

docker好像不能设置定时启动了。

### MIUITask Log

12:45:08 - INFO  | system_info.system_info:31 - Python 版本: 3.12.1 ('main', 'Dec  9 2023 00:44:52')
12:45:08 - INFO  | system_info.print_info:16 - ---------- 项目信息 -------------
12:45:08 - INFO  | system_info.print_info:17 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
12:45:08 - INFO  | system_info.print_info:18 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
12:45:08 - INFO  | system_info.print_info:19 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
12:45:08 - INFO  | system_info.print_info:20 - ---------- 脚本日志 -------------
12:45:09 - INFO  | login.login:75 - Cookie有效，跳过登录
12:45:09 - INFO  | miuitask.main:37 - 开始执行2024新春感恩回馈季任务
12:45:09 - ERROR | miuitask.main:42 - 未找到2024新春感恩回馈季任务
12:45:09 - INFO  | miuitask.main:37 - 开始执行每日签到任务
12:45:09 - ERROR | utils.get_token:229 - 遇到人机验证码, 尝试调用解决方案
12:45:10 - ERROR | utils.get_token_by_captcha:126 - 遇到人机验证码，无法获取TOKEN
12:45:10 - ERROR | utils.get_token:229 - 遇到人机验证码, 尝试调用解决方案
12:45:10 - ERROR | utils.get_token_by_captcha:126 - 遇到人机验证码，无法获取TOKEN
12:45:11 - ERROR | utils.get_token:229 - 遇到人机验证码, 尝试调用解决方案
12:45:11 - ERROR | utils.get_token_by_captcha:126 - 遇到人机验证码，无法获取TOKEN
12:45:11 - ERROR | utils.get_token:242 - 获取TOKEN异常
Traceback (most recent call last):
  File "/srv/utils/utils.py", line 234, in get_token
    raise ValueError("人机验证失败")
ValueError: 人机验证失败
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/srv/miuitask.py", line 59, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x7f87c65620>
    │       └ <function run at 0x7f871d1c60>
    └ <module 'asyncio' from '/usr/local/lib/python3.12/asyncio/__init__.py'>
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x7f855cd3f0>
           │      └ <function Runner.run at 0x7f8726f240>
           └ <asyncio.runners.Runner object at 0x7f8719dd90>
  File "/usr/local/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at /srv/miuitask.py:47> cb=[_run_until_complete_cb() at /usr/local/lib/pytho...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x7f8726cea0>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7f8719dd90>
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 671, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7f8726ce00>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 638, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7f8726ec00>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1971, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7f871b5080>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7f8412dcf0>()>
  File "/usr/local/lib/python3.12/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7f8412dcf0>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7f8412dcf0>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <_asyncio.TaskStepMethWrapper object at 0x7f8412dcf0>()>
  File "/srv/miuitask.py", line 47, in main
    token = await get_token(cookies["cUserId"]) if task_obj == CheckIn else None
                  │         │                      │           └ <class 'utils.api.sign.CheckIn'>
                  │         │                      └ <class 'utils.api.sign.CheckIn'>
                  │         └ {'miui_vip_serviceToken': 'IA2BKMwRB8IbWsAlqNmMoGXbYairkSkhyThr6+m4qoGx+BLs+RvQbIHB0zbIYGWfHZpywL/6l8N7WWt93UcZwv3D9OD1uFd6KS...
                  └ <function get_token at 0x7f8454e980>
> File "/srv/utils/utils.py", line 140, in get_token
    for attempt in Retrying(stop=stop_after_attempt(3)):
        │          │             └ <class 'tenacity.stop.stop_after_attempt'>
        │          └ <class 'tenacity.Retrying'>
        └ <tenacity.AttemptManager object at 0x7f84123020>
  File "/srv/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         │    │                └ <RetryCallState 547690352320: attempt #3; slept for 0.0; last result: failed (ValueError 人机验证失败)>
         │    └ <function BaseRetrying.iter at 0x7f87054220>
         └ <Retrying object at 0x7f84e8a990 (stop=<tenacity.stop.stop_after_attempt object at 0x7f85fc70b0>, wait=<tenacity.wait.wait_no...
  File "/srv/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
          │              │   └ <function Future.exception at 0x7f87b43880>
          │              └ <Future at 0x7f852ebbf0 state=finished raised ValueError>
          └ RetryError(<Future at 0x7f852ebbf0 state=finished raised ValueError>)
tenacity.RetryError: RetryError[<Future at 0x7f852ebbf0 state=finished raised ValueError>]
12:45:11 - INFO  | sign.sign:88 - 未获取到token, 跳过每日签到
12:45:11 - INFO  | miuitask.main:37 - 开始执行浏览帖子超过10秒任务
12:45:11 - INFO  | miuitask.main:39 - 浏览帖子超过10秒任务已完成
12:45:11 - INFO  | miuitask.main:37 - 开始执行参与拔萝卜获得奖励任务
12:45:11 - SUCCESS | sign.sign:100 - 参与拔萝卜获得奖励结果: ok
12:45:11 - INFO  | miuitask.main:52 - 高级成员 成长值: 650
12:45:11 - ERROR | request.notify_me:74 - 未配置推送或未正确配置推送

**Comment by q1uxu** [comment]
用docker启动后，就算之前手动配置了hour和minute，也会被覆盖掉

**Comment by Night-stars-1** [comment]
> 用docker启动后，就算之前手动配置了hour和minute，也会被覆盖掉

已经没有这个参数了

**Comment by q1uxu** [comment]
> > 用docker启动后，就算之前手动配置了hour和minute，也会被覆盖掉
> 
> 已经没有这个参数了

既然没有这个参数了，那你们更新下wiki啊。没了的参数wiki还留着干嘛，我看着文档配置的，结果跟我说没有这个参数了，我还以为是我配置有问题。
