### ISSUE TITLE
不能通过人机验证码，导致签到失败

### ISSUE THREAD

**Issue by LittelSpecial** [0-8-4/miui-auto-tasks#265]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 MIUITask 并不包含该功能特性或者还不完善
- [X] Framework 这是 MIUITask 应包含的特性, 并非实现社区外功能
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

checkin会卡住，签到失败

### Describe the Solution

通过api调用，或者自建服务器。

**Comment by koolcandy** [comment]
#288

**Comment by koolcandy** [comment]
#228

**Comment by Night-stars-1** [comment]
你给出的信息太少，我不知道发生了什么
另外您讨论的问题不符合社区规则(#228 ), 这里不做回答，issue关闭处理
有其他疑问请在其他地方讨论
