### ISSUE TITLE
[Bug] cookie有效性的判断失误还是？

### ISSUE THREAD

**Issue by klcb2010** [0-8-4/miui-auto-tasks#267]
如果是cookie失效，根本得不到challenge和validate，难道是Xiaomi在逗人玩？

　　
![截屏图片](https://github.com/0-8-4/miui-auto-tasks/assets/32628414/627f2c8e-2770-4cef-8ef6-0cab1fa4f619)

**Comment by BA7JCM** [comment]
@klcb2010 cookie的失效与否，只是关系到你账号的登录状态存在与否，至于challenge和validate的获取，只是建立在你cookie没失效的基础上，cookie失效了必然拿不到这两个数据，但这并不意味着没失效就一定能拿到这两个数据的值

**Comment by klcb2010** [comment]
> @klcb2010 cookie的失效与否，只是关系到你账号的登录状态存在与否，至于challenge和validate的获取，只是建立在你cookie没失效的基础上，cookie失效了必然拿不到这两个数据，但这并不意味着没失效就一定能拿到这两个数据的值

它是拿到了再提示失效 ，后面重新登录再拿一次 😂

**Comment by BA7JCM** [comment]
@klcb2010 只是恰好你cookie在那个时候失效了……

**Comment by klcb2010** [comment]
@BA7JCM 巧哭了 😃
