### ISSUE TITLE
[Bug] 青龙面板问题：账号登录成功,但无签到进程，直接结束。

### ISSUE THREAD

**Issue by shaoyangx** [0-8-4/miui-auto-tasks#272]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.5

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.12

### Describe the Bug

安装依赖，配置账号均未出现问题，但是实际运行却在提示账号登陆成功后直接跳转到推送功能。

### MIUITask Log

04:25:21 - INFO  | system_info.print_info:13 - MIUI-AUTO-TASK v1.7.5
04:25:21 - INFO  | system_info.print_info:14 - ---------- 系统信息 -------------
04:25:21 - INFO  | system_info.system_info:25 - 操作系统平台: Linux-6.1.0-0.deb11.11-amd64-x86_64-with
04:25:21 - INFO  | system_info.system_info:26 - 操作系统版本: #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4~bpo11+1 (2023-08-08)
04:25:21 - INFO  | system_info.system_info:27 - 操作系统名称: Linux
04:25:21 - INFO  | system_info.system_info:28 - 操作系统位元: ('64bit', '')
04:25:21 - INFO  | system_info.system_info:29 - 操作系统类型: x86_64
04:25:21 - INFO  | system_info.system_info:30 - 处理器信息: 
04:25:21 - INFO  | system_info.system_info:31 - Python 版本: 3.11.8 ('main', 'Mar 16 2024 04:56:37')
04:25:21 - INFO  | system_info.print_info:16 - ---------- 项目信息 -------------
04:25:21 - INFO  | system_info.print_info:17 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
04:25:21 - INFO  | system_info.print_info:18 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
04:25:21 - INFO  | system_info.print_info:19 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
04:25:21 - INFO  | system_info.print_info:20 - ---------- 脚本日志 -------------
04:25:21 - DEBUG | sign.check_daily_tasks:84 - {"code":401}
04:25:22 - DEBUG | login.login:78 - &&&START&&&{"qs":"**********","description":"成功","securityStatus":0,"nonce":**********,"userId":**********,"cUserId":"**********","result":"ok","psecurity":"**********","captchaUrl":null,"location":"“我不确定这段参数是否包含个人信息，暂做删除","pwd":1,"child":0,"desc":"成功"}
04:25:22 - SUCCESS | login.login:83 - 小米账号登录成功
04:25:22 - ERROR | request.notify_me:74 - 未配置推送或未正确配置推送

### MIUITask Config

```shell
preference:
    geetest_url: ''
    geetest_params: {}
    geetest_data: {}
accounts:
-   uid: '******'
    password: *******
    cookies:
        passToken: V1:*********
    login_user_agent: ''
    user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,like
        Gecko) Chrome/102.0.0.0 Safari/537.36
    device: ''
    device_model: ''
    CheckIn: true
    BrowseUserPage: false
    BrowsePost: false
    ThumbUp: false
    BrowseSpecialPage: false
    BoardFollow: false
    CarrotPull: false
ONEPUSH:
    notifier: ''
    params:
        title: ''
        markdown: false
        token: ''
        userid: ''
```

**Comment by Night-stars-1** [comment]
@shaoyangx 填写login_user_agent

**Comment by shaoyangx** [comment]
> @shaoyangx 填写login_user_agent

在wiki中我没看到这个配置项的说明，请问是填写和user_agent同样的参数吗？
以上省略

复制user_agent的参数到login_user_agent运行成功

**Comment by cyd** [comment]
+1，遇到一样的问题。我这边是复制旧的配置。直接贴到新的过来。没想到是这个agent改了个名字导致的。感谢。

**Comment by lyl15879922380** [comment]
> @shaoyangx 填写login_user_agent

妙手回春啊night老师
