### ISSUE TITLE
不配置推送脚本自动结束

### ISSUE THREAD

**Issue by biusp** [0-8-4/miui-auto-tasks#273]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

last

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.12

### Describe the Bug

不配置推送脚本自动结束

## 开始执行... 2024-04-18 23:43:27

23:43:27 - INFO  | system_info.print_info:13 - MIUI-AUTO-TASK v1.7.5
23:43:27 - INFO  | system_info.print_info:14 - ---------- 系统信息 -------------
23:43:27 - INFO  | system_info.system_info:25 - 操作系统平台: Linux-3.10.0-1160.99.1.el7.x86_64-x86_64-with-glibc2.31
23:43:27 - INFO  | system_info.system_info:26 - 操作系统版本: #1 SMP Wed Sep 13 14:19:20 UTC 2023
23:43:27 - INFO  | system_info.system_info:27 - 操作系统名称: Linux
23:43:27 - INFO  | system_info.system_info:28 - 操作系统位元: ('64bit', '')
23:43:27 - INFO  | system_info.system_info:29 - 操作系统类型: x86_64
23:43:27 - INFO  | system_info.system_info:30 - 处理器信息: 
23:43:27 - INFO  | system_info.system_info:31 - Python 版本: 3.11.9 ('main', 'Apr 10 2024 04:47:20')
23:43:27 - INFO  | system_info.print_info:16 - ---------- 项目信息 -------------
23:43:27 - INFO  | system_info.print_info:17 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
23:43:27 - INFO  | system_info.print_info:18 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
23:43:27 - INFO  | system_info.print_info:19 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
23:43:27 - INFO  | system_info.print_info:20 - ---------- 脚本日志 -------------
23:43:29 - SUCCESS | login.login:83 - 小米账号登录成功
23:43:29 - ERROR | request.notify_me:74 - 未配置推送或未正确配置推送

### Screenshots

![image](https://github.com/0-8-4/miui-auto-tasks/assets/80397695/f4a5fdc5-f9dc-43bd-ae0d-99f954bc4bda)

**Comment by biusp** [comment]
不是推送的问题,配置了推送依旧没有任何操作就结束了

**Comment by koolcandy** [comment]
是没有设置ua的问题
