### ISSUE TITLE
未找到浏览指定视频流超过5分钟任务

### ISSUE THREAD

**Issue by fabaoin** [0-8-4/miui-auto-tasks#276]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

DOCKER拉取的最新版本

### Bug Found in Environment

Linux, Docker

### Bug Found in Python Version

3.12

### Describe the Bug

开始执行浏览指定视频流超过5分钟任务
未找到浏览指定视频流超过5分钟任务

现在每天签到只能增加一个成长值。

### MIUITask Log

09:27:02 - INFO  | miuitask.main:40 - 开始执行参与米粉足迹点亮任务
09:27:02 - ERROR | miuitask.main:47 - 未找到参与米粉足迹点亮任务
09:27:02 - INFO  | miuitask.main:40 - 开始执行每日签到任务
09:27:02 - INFO  | miuitask.main:42 - 每日签到任务已完成
09:27:02 - INFO  | miuitask.main:40 - 开始执行浏览帖子超过10秒任务
09:27:02 - INFO  | miuitask.main:42 - 浏览帖子超过10秒任务已完成
09:27:02 - INFO  | miuitask.main:40 - 开始执行浏览指定视频流超过5分钟任务
09:27:02 - ERROR | miuitask.main:47 - 未找到浏览指定视频流超过5分钟任务
09:27:02 - INFO  | miuitask.main:40 - 开始执行参与拔萝卜获得奖励任务
09:27:03 - DEBUG | sign.sign:139 - {"status":200,"code":200,"message":"ok","entity":{"header":{"userId":2911058903,"vipType":-1,"moneyCount":4},"popup":0,"message":"今天已经很累了，明天再来吧~","awardCoinCount":0}}
09:27:03 - SUCCESS | sign.sign:146 - 参与拔萝卜获得奖励结果: ok

另外这些参数的说明没有找到
preference:
    geetest_url: ''
    geetest_params: {}
    geetest_data: {}

**Comment by punglegod** [comment]
你好，请问你的签到是怎么解决验证码问题的呢，如果能为我解惑，不胜感激。

**Comment by koolcandy** [comment]
> ### Verify Steps 验证步骤
> * [x]  Tracker 我已经在 [Issue Tracker](%E2%80%A6%E2%80%A6/) 中找过我要提出的问题
> * [x]  Latest 我已经使用最新版本测试过，问题依旧存在
> * [x]  Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
> * [x]  Meaningful 我提交的不是无意义的 催促更新或修复 请求
> 
> ### MIUITask Version MIUI任务版本
> DOCKER拉取的最新版本
> 
> ### Bug Found in Environment
> 在环境中发现错误
> Linux, Docker Linux、码头工人
> 
> ### Bug Found in Python Version
> Python 版本中发现错误
> 3.12
> 
> ### Describe the Bug 描述错误
> 开始执行浏览指定视频流超过5分钟任务 未找到浏览指定视频流超过5分钟任务
> 
> 现在每天签到只能增加一个成长值。
> 
> ### MIUITask Log MIUI任务日志
> 09:27:02 - INFO | miuitask.main:40 - 开始执行参与米粉足迹点亮任务 09:27:02 - ERROR | miuitask.main:47 - 未找到参与米粉足迹点亮任务 09:27:02 - INFO | miuitask.main:40 - 开始执行每日签到任务 09:27:02 - INFO | miuitask.main:42 - 每日签到任务已完成 09:27:02 - INFO | miuitask.main:40 - 开始执行浏览帖子超过10秒任务 09:27:02 - INFO | miuitask.main:42 - 浏览帖子超过10秒任务已完成 09:27:02 - INFO | miuitask.main:40 - 开始执行浏览指定视频流超过5分钟任务 09:27:02 - ERROR | miuitask.main:47 - 未找到浏览指定视频流超过5分钟任务 09:27:02 - INFO | miuitask.main:40 - 开始执行参与拔萝卜获得奖励任务 09:27:03 - DEBUG | sign.sign:139 - {"status":200,"code":200,"message":"ok","entity":{"header":{"userId":2911058903,"vipType":-1,"moneyCount":4},"popup":0,"message":"今天已经很累了，明天再来吧~","awardCoinCount":0}}09:27:03 - 调试 | sign.sign:139 - {"status":200,"code":200,"message":"ok","entity":{"header":{"userId":2911058903,"vipType":-1, "moneyCount":4},"popup":0,"message":"今天已经累了，明天再来吧~","awardCoinCount":0}} 09:27:03 - SUCCESS | sign.sign:146 - 参与拔萝卜获得奖励结果: ok
> 
> 另外这些参数的说明没有找到 preference: 偏爱： geetest_url: '' geetest_params: {} 极测试参数：{} geetest_data: {} 极测试数据：{}
> 
> ### MIUITask Config MIUI任务配置
> _No response 没有反应_
> 
> ### Screenshots 截图
> _No response 没有反应_

任务名字改了

**Comment by koolcandy** [comment]
> 你好，请问你的签到是怎么解决验证码问题的呢，如果能为我解惑，不胜感激。

#135

**Comment by BA7JCM** [comment]
> 你好，请问你的签到是怎么解决验证码问题的呢，如果能为我解惑，不胜感激。

这玩意不便于在公开场合讨论，具体见 #228 ，但你可以从仓库里找到加群链接进到群里，群里大伙们慢慢讨论

**Comment by fabaoin** [comment]
我没解决啊，那是我手动签的[哭笑]
