### ISSUE TITLE
遇到验证码，不能签到只能做任务

### ISSUE THREAD

**Issue by CJAY1997** [0-8-4/miui-auto-tasks#278]
### Verify Steps

- [ ] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [x] Latest 我已经使用最新版本测试过，问题依旧存在
- [ ] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.5

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.11

### Describe the Bug

验证码一直无法跳过，青龙面板正式版 v2.16.5 python 3.10.13

### MIUITask Log

11:44:51 - INFO  | system_info.print_info:13 - MIUI-AUTO-TASK v1.7.5
11:44:51 - INFO  | system_info.print_info:14 - ---------- 系统信息 -------------
11:44:51 - INFO  | system_info.system_info:25 - 操作系统平台: Linux-4.4.302+-x86_64-with
11:44:51 - INFO  | system_info.system_info:26 - 操作系统版本: #69057 SMP Fri Jan 12 17:02:28 CST 2024
11:44:51 - INFO  | system_info.system_info:27 - 操作系统名称: Linux
11:44:51 - INFO  | system_info.system_info:28 - 操作系统位元: ('64bit', 'ELF')
11:44:51 - INFO  | system_info.system_info:29 - 操作系统类型: x86_64
11:44:51 - INFO  | system_info.system_info:30 - 处理器信息: 
11:44:51 - INFO  | system_info.system_info:31 - Python 版本: 3.10.13 ('main', 'Oct 19 2023 06:08:04')
11:44:51 - INFO  | system_info.system_info:33 - 系统代理: {'ray_serilog__writeto__3__args_': '192.168.2.16:7893'}
11:44:51 - INFO  | system_info.print_info:16 - ---------- 项目信息 -------------
11:44:51 - INFO  | system_info.print_info:17 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
11:44:51 - INFO  | system_info.print_info:18 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
11:44:51 - INFO  | system_info.print_info:19 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
11:44:51 - INFO  | system_info.print_info:20 - ---------- 脚本日志 -------------
11:44:51 - INFO  | login.login:60 - Cookie有效，跳过登录
11:44:51 - INFO  | login.checkin_info:263 - 当前签到+1的概率：37.805%（每小时更新）
11:44:53 - INFO  | miuitask.swap.main:40 - 开始执行每日签到任务
11:44:53 - ERROR | utils.get_token:226 - 遇到人机验证码, 尝试调用解决方案
11:44:53 - ERROR | utils.get_token_by_captcha:123 - 遇到人机验证码，无法获取TOKEN
11:44:53 - ERROR | utils.get_token:226 - 遇到人机验证码, 尝试调用解决方案
11:44:54 - ERROR | utils.get_token_by_captcha:123 - 遇到人机验证码，无法获取TOKEN
11:44:55 - ERROR | utils.get_token:233 - 遇到未知错误，无法获取TOKEN
11:44:55 - INFO  | sign.sign:131 - 未获取到token, 跳过每日签到
11:44:55 - INFO  | miuitask.swap.main:40 - 开始执行浏览帖子超过10秒任务
11:44:55 - INFO  | miuitask.swap.main:42 - 浏览帖子超过10秒任务已完成
11:44:55 - INFO  | miuitask.swap.main:40 - 开始执行参与拔萝卜获得奖励任务
11:44:55 - SUCCESS | sign.sign:146 - 参与拔萝卜获得奖励结果: ok
11:44:56 - INFO  | miuitask.swap.main:61 - 高级成员 成长值: 560

### MIUITask Config

```shell
preference:
    geetest_url: ''
    geetest_params: {}
    geetest_data: {}
accounts:
-   uid: ''
    password: 
    cookies:
    login_user_agent: Mozilla/5.0 (Android 11; Mobile; rv:95.0) Gecko/95.0 Firefox/95.0
    user_agent: Mozilla/5.0 (Linux; U; Android 13; zh-cn; 2206122SC Build/TKQ1.220829.002)
        AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.118 Mobile
        Safari/537.36 XiaoMi/MiuiBrowser/17.9.111128 swan-mibrowser
    device: ''
    device_model: ''
    CheckIn: true
    BrowseUserPage: true
    BrowsePost: true
    BrowseVideoPost: false
    ThumbUp: true
    BrowseSpecialPage: true
    BoardFollow: true
    CarrotPull: true
ONEPUSH:
    notifier: ''
    params:
        title: ''
        markdown: false
        token: ''
        userid: ''
```

**Comment by BA7JCM** [comment]
@CJAY1997 https://github.com/0-8-4/miui-auto-tasks/issues/276#issuecomment-2079649639

**Comment by ayakasuki** [comment]
![image](https://github.com/0-8-4/miui-auto-tasks/assets/20859971/c3d8e2b1-fd77-434b-9d82-1e3969d816de)
可以类似这样 写一个接码api接口出来吗？因为极验其实是有几块钱几千次接码的购买方法 只不过不好公开

**Comment by feng0909** [comment]
![Snipaste_2024-06-18_09-08-38](https://github.com/0-8-4/miui-auto-tasks/assets/35063365/9247b619-e6b3-4ea5-b183-54f31af09fe6)
同样有这个问题

**Comment by BA7JCM** [comment]
> ![Snipaste_2024-06-18_09-08-38](https://private-user-images.githubusercontent.com/35063365/340497803-9247b619-e6b3-4ea5-b183-54f31af09fe6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2OTM2MDcsIm5iZiI6MTcxODY5MzMwNywicGF0aCI6Ii8zNTA2MzM2NS8zNDA0OTc4MDMtOTI0N2I2MTktZTZiMy00ZWE1LWIxODMtNTRmMzFhZjA5ZmU2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDA2NDgyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkM2FjNGMyZDA3MTAzNGY4MzU2ZWFhMGFlNjk4ZGE3NzM2ZDc0ZDBhNjMyMDY5ZWFlMTU4NTM2YjU2NTc3YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FHa8xtjjDwx6WRsqJyZJozp4EiFni3tRP-_4-M44muQ) 同样有这个问题

https://github.com/0-8-4/miui-auto-tasks/issues/278#issuecomment-2081338159
