### ISSUE TITLE
 小米账号登录成功后就直接结束了

### ISSUE THREAD

**Issue by runishiwo** [0-8-4/miui-auto-tasks#282]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

1.7.5

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.11

### Describe the Bug

12:08:24 - SUCCESS | login.login:83 - 小米账号登录成功
12:08:25 - ERROR | request.notify_me:74 - 未配置推送或未正确配置推送

### MIUITask Log

12:11:20 - INFO  | system_info.print_info:13 - MIUI-AUTO-TASK v1.7.5
12:11:20 - INFO  | system_info.print_info:14 - ---------- 系统信息 -------------
12:11:20 - INFO  | system_info.system_info:25 - 操作系统平台: Linux-3.10.0-1127.el7.x86_64-x86_64-with
12:11:20 - INFO  | system_info.system_info:26 - 操作系统版本: #1 SMP Tue Mar 31 23:36:51 UTC 2020
12:11:20 - INFO  | system_info.system_info:27 - 操作系统名称: Linux
12:11:20 - INFO  | system_info.system_info:28 - 操作系统位元: ('64bit', 'ELF')
12:11:20 - INFO  | system_info.system_info:29 - 操作系统类型: x86_64
12:11:20 - INFO  | system_info.system_info:30 - 处理器信息: 
12:11:20 - INFO  | system_info.system_info:31 - Python 版本: 3.10.13 ('main', 'Oct 19 2023 06:08:04')
12:11:20 - INFO  | system_info.print_info:16 - ---------- 项目信息 -------------
12:11:20 - INFO  | system_info.print_info:17 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
12:11:20 - INFO  | system_info.print_info:18 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
12:11:20 - INFO  | system_info.print_info:19 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
12:11:20 - INFO  | system_info.print_info:20 - ---------- 脚本日志 -------------
12:11:20 - DEBUG | sign.check_daily_tasks:84 - {"code":401}
12:11:21 - DEBUG | login.login:78 - &&&START&&&{"qs":"%3F_json%3Dtrue%26sid%3Dmiui_vip_a%26_locale%3Dzh_CN","ssecurity":"8cQYxXPcAgMjsy8pcxUuGA==","code":0,"passToken":"V1:DXmurwq2/R1BHTELu6obCZlyg16byZhMe60ibBFf6KsH7xEwFlU+qkYJ1lgI54Z4XxU6JPwmfDctm/AP0dc+BaPHIt9ddNVc1zzVKMhOi8HFFsGZRUvXzK0EbnDInJPvvj6TPgHoSkFnzKXPrCv+fBKvXuj6aiqLUYBkFaDosf/z4i6vBZRI7UIFtJQMFw16lU1ShSDb9cvBMJzzybWQhLADg3DP+aNPnYN3I0waz7QNHtqu+Yiu/wbze9nlVYSJfJahP/SvsceAkuSq3Gi9sIP3LUHTHQN7auxBivg1UvjgY10osKhNkv+yM/1K53ng","description":"成功","securityStatus":0,"nonce":309666439097259008,"userId":1332075896,"cUserId":"HiAFqlxEgbu86VXOVUMfDnkLJkY","result":"ok","psecurity":"j0GqgYb0Wq9RfbXuUaQTZg==","captchaUrl":null,"location":"https://api-alpha.vip.miui.com/sts?d=S13aukyf5y2jecCG&ticket=0&pwd=1&p_ts=1715573481000&fid=0&p_lm=1&auth=TOQiW70KtyGTBB7hnD7vApMpW94lnwqdyshizsn6x0Al4hJk9EbpMAeQmfbCdjyzmQt58ZltXLbiWdHnqSaMsAoISVJAnO2r%2B%2BHelcNDMFWW0uchP%2BfkEEv99jbfw9JpA6l2fOI%2Ff%2FLeHbrZmBMIYVP2IsuJsa9D0NeMeh6Zitg%3D&m=1&_group=DEFAULT&tsl=0&p_ca=0&p_ur=CN&p_idc=China&nonce=nBE65%2FLRReEBtEr7&_ssign=j8d785j9HqJWS9yJPrVgGvkMcLk%3D","pwd":1,"child":0,"desc":"成功"}
12:11:21 - SUCCESS | login.login:83 - 小米账号登录成功
12:11:22 - ERROR | request.notify_me:74 - 未配置推送或未正确配置推送

**Comment by BA7JCM** [comment]
@runishiwo https://github.com/0-8-4/miui-auto-tasks/issues/272#issuecomment-2050869645

**Comment by zhangxu1233** [comment]
12:11:22 - ERROR | request.notify_me:74 - 未配置推送或未正确配置推送

报错很清楚

**Comment by waseemcn** [comment]
1:40:26 - ERROR | login.checkin_info:265 - 获取用户信息失败
Traceback (most recent call last):

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 68, in <module>
    asyncio.run(main())
    │       │   └ <function main at 0x7fbb8b7a04a0>
    │       └ <function run at 0x7fbb8abbb4c0>
    └ <module 'asyncio' from '/usr/local/lib/python3.11/asyncio/__init__.py'>

  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           │      │   └ <coroutine object main at 0x7fbb8aa44460>
           │      └ <function Runner.run at 0x7fbb8a996e80>
           └ <asyncio.runners.Runner object at 0x7fbb8a998450>
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           │    │     │                  └ <Task pending name='Task-1' coro=<main() running at /ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py:35> cb=[_run_un...
           │    │     └ <function BaseEventLoop.run_until_complete at 0x7fbb8a994ae0>
           │    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
           └ <asyncio.runners.Runner object at 0x7fbb8a998450>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 641, in run_until_complete
    self.run_forever()
    │    └ <function BaseEventLoop.run_forever at 0x7fbb8a994a40>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 608, in run_forever
    self._run_once()
    │    └ <function BaseEventLoop._run_once at 0x7fbb8a996840>
    └ <_UnixSelectorEventLoop running=True closed=False debug=False>
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 1936, in _run_once
    handle._run()
    │      └ <function Handle._run at 0x7fbb8ab70cc0>
    └ <Handle <TaskStepMethWrapper object at 0x7fbb8783c190>()>
  File "/usr/local/lib/python3.11/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
    │    │            │    │           │    └ <member '_args' of 'Handle' objects>
    │    │            │    │           └ <Handle <TaskStepMethWrapper object at 0x7fbb8783c190>()>
    │    │            │    └ <member '_callback' of 'Handle' objects>
    │    │            └ <Handle <TaskStepMethWrapper object at 0x7fbb8783c190>()>
    │    └ <member '_context' of 'Handle' objects>
    └ <Handle <TaskStepMethWrapper object at 0x7fbb8783c190>()>

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 35, in main
    await login_obj.checkin_info()
          │         └ <function Login.checkin_info at 0x7fbb8779e3e0>
          └ <utils.api.login.Login object at 0x7fbb877a3850>

> File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/api/login.py", line 252, in checkin_info
    "miui_vip_a_ph": self.cookies["miui_vip_a_ph"],
