### ISSUE TITLE
[Bug] twocaptcha依赖用着用着会显示装了错误的版本然后自动重新安装就用不了了

### ISSUE THREAD

**Issue by wdmhydw** [0-8-4/miui-auto-tasks#284]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.1

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.9

### Describe the Bug

前几次自动运行一切正常，然后突然就会显示twocaptcha错误，必须要手动重新装才能用

### MIUITask Log

检测到已安装错误的 twocaptcha 包，正在尝试卸载并安装 2CAPTCHA-Python ...
Found existing installation: TwoCaptcha 0.0.1
Uninstalling TwoCaptcha-0.0.1:
  Successfully uninstalled TwoCaptcha-0.0.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Looking in indexes: https://pypi.doubanio.com/simple/
Requirement already satisfied: 2CAPTCHA-Python in /usr/local/lib/python3.10/site-packages (1.2.5)
Requirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (from 2CAPTCHA-Python) (2.31.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests->2CAPTCHA-Python) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/site-packages (from requests->2CAPTCHA-Python) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/site-packages (from requests->2CAPTCHA-Python) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/site-packages (from requests->2CAPTCHA-Python) (2023.7.22)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
2CAPTCHA-Python 安装成功！正在尝试重新加载正确的依赖包
Traceback (most recent call last):
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 15, in <module>
    from utils.api.login import Login
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/api/login.py", line 17, in <module>
    from .sign import BaseSign
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/api/sign.py", line 17, in <module>
    from ..utils import get_random_chars_as_string, is_incorrect_return
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 49, in <module>
    from twocaptcha import TwoCaptcha
ImportError: cannot import name 'TwoCaptcha' from 'twocaptcha' (unknown location)

### Screenshots

![image](https://github.com/0-8-4/miui-auto-tasks/assets/61841146/64783823-bf8c-4084-be2a-141eefc110d9)

**Comment by BA7JCM** [comment]
@wdmhydw 由于目前技术限制，我还没啥好办法在一次运行中就把已经加载进去的模块重新加载了，至于你说的运行了一下段时间就提示模块错误，我觉得你不是更应该排查一下你的环境里有啥程序如此执着于将错误的那个2CAPTCHA包给装回去吗，另外，这玩意还是在群里讨论好了，并不是公开发布的版本，再就是，https://github.com/0-8-4/miui-auto-tasks/issues/276#issuecomment-2079649639

**Comment by Night-stars-1** [comment]
我们没有发布过你使用的版本，自修改请不要在这里讨论
