### ISSUE TITLE
docker版本是否可以跟进更新，青龙版本更新依赖部分无法安装

### ISSUE THREAD

**Issue by foglamb** [0-8-4/miui-auto-tasks#285]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Need 当前 MIUITask 并不包含该功能特性或者还不完善
- [X] Framework 这是 MIUITask 应包含的特性, 并非实现社区外功能
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### Describe the Feature

我的py依赖有一个无法安装，docker版本正常使用，希望作者可以更新一下docker的版本为可签到版本，目前版本签到会显示token获取失败，导致无法签到

### Describe the Solution

我的py依赖有一个无法安装，docker版本正常使用，希望作者可以更新一下docker的版本为可签到版本，目前版本签到会显示token获取失败，导致无法签到

### Describe Alternatives

找一个其他库代替cryptography

### Additional Context

更新docker的task版本，感谢

**Comment by Night-stars-1** [comment]
你应该自行替换或者想办法安装cryptography，然后考虑向该仓库提交pr，而不是要求开发者重构代码
