### ISSUE TITLE
[Bug] 提示登陆成功后直接关闭

### ISSUE THREAD

**Issue by B4QAQ** [0-8-4/miui-auto-tasks#288]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.5

### Bug Found in Environment

Linux

### Bug Found in Python Version

3.11

### Describe the Bug

登陆后无法进行签到等任务

## 开始执行... 2024-08-08 19:24:37

19:24:42 - INFO  | system_info.print_info:13 - MIUI-AUTO-TASK v1.7.5
19:24:42 - INFO  | system_info.print_info:14 - ---------- 系统信息 -------------
19:24:42 - INFO  | system_info.system_info:25 - 操作系统平台: Linux-5.15.0-handsomekernel+-aarch64-with
19:24:42 - INFO  | system_info.system_info:26 - 操作系统版本: #9 SMP PREEMPT Wed Jun 8 01:16:20 CST 2022
19:24:42 - INFO  | system_info.system_info:27 - 操作系统名称: Linux
19:24:42 - INFO  | system_info.system_info:28 - 操作系统位元: ('64bit', '')
19:24:42 - INFO  | system_info.system_info:29 - 操作系统类型: aarch64
19:24:42 - INFO  | system_info.system_info:30 - 处理器信息: 
19:24:42 - INFO  | system_info.system_info:31 - Python 版本: 3.11.9 ('main', 'Jul 24 2024 05:28:51')
19:24:42 - INFO  | system_info.print_info:16 - ---------- 项目信息 -------------
19:24:42 - INFO  | system_info.print_info:17 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
19:24:42 - INFO  | system_info.print_info:18 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
19:24:42 - INFO  | system_info.print_info:19 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
19:24:42 - INFO  | system_info.print_info:20 - ---------- 脚本日志 -------------
19:24:44 - SUCCESS | login.login:83 - 小米账号登录成功

### MIUITask Config

```shell
preference:
    geetest_url: ''
    geetest_params: {}
    geetest_data: {}
accounts:
-   uid: '***'
    password: ***
    cookies:
        passToken: V1:***
    login_user_agent: ''
    user_agent: Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko)
        Version/4.0 Chrome/116.0.0.0 Safari/537.36
    device: ''
    device_model: ''
    CheckIn: true
    BrowseUserPage: true
    BrowsePost: true
    BrowseVideoPost: true
    ThumbUp: true
    BrowseSpecialPage: false
    BoardFollow: false
    CarrotPull: true
ONEPUSH:
    notifier: serverchanturbo
    params:
        title: 定时任务-小米社区-已执行
        sctkey: ***
```

**Comment by 1273294133** [comment]
俺也一样

**Comment by 1273294133** [comment]
看起来像是青龙一键脚本。没使用最新的v1.7.6-hotfix1

**Comment by BA7JCM** [comment]
@1273294133 一键脚本是现从github上拉取的

**Comment by BA7JCM** [comment]
![Screenshot_2024-08-09-11-36-00-141_com.github.android.jpg](https://github.com/user-attachments/assets/87930fdb-9cdd-42df-8517-917afa1602e8)

把这玩意填了

**Comment by duolingmi** [comment]
一样的情况啊

**Comment by coolayou** [comment]
果然 login_user_agent 一填就ok了
