### ISSUE TITLE
请求支持加内测分的脚本

### ISSUE THREAD

**Issue by ljynfo** [0-8-4/miui-auto-tasks#29]
![image](https://user-images.githubusercontent.com/42232422/132979563-ab2d7b65-befa-48d0-a3cf-9849a5fa2cad.png)

**Comment by TardisXE** [comment]
脚本是会进行这些增加内测分的操作的，每天执行一次即可。如无其他问题请自行关闭issues

**Comment by ljynfo** [comment]
登录app的内测分没加、评论5次的内测分没加、发帖只有一次

**Comment by TardisXE** [comment]
本脚本不会模拟 社区3.0 App 进行登录操作，另外目前正常脚本会执行3次发帖和回帖以及五次点赞，个人认为这些已经可以获取到足够的分数。本脚本的最初目的是方便完成社区内测KPI，在下个大版本中才有可能对内测分获取进行修改。

**Comment by ljynfo** [comment]
好的，非常感觉作者的无私奉献，期待大佬的新版本，谢谢
