### ISSUE TITLE
遇到人机验证码，无法获取TOKEN

### ISSUE THREAD

**Issue by iNewWay** [0-8-4/miui-auto-tasks#294]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.5

### Bug Found in Environment

Docker, Other

### Bug Found in Python Version

3.12

### Describe the Bug

00:02:03 - INFO  | miuitask.main:36 - 开始执行每日签到任务
00:02:03 - ERROR | utils.get_token:226 - 遇到人机验证码, 尝试调用解决方案
00:02:03 - ERROR | utils.get_token_by_captcha:123 - 遇到人机验证码，无法获取TOKEN
00:02:04 - ERROR | utils.get_token:226 - 遇到人机验证码, 尝试调用解决方案
00:02:04 - ERROR | utils.get_token_by_captcha:123 - 遇到人机验证码，无法获取TOKEN
00:02:04 - ERROR | utils.get_token:233 - 遇到未知错误，无法获取TOKEN
00:02:04 - INFO  | sign.sign:131 - 未获取到token, 跳过每日签到

### MIUITask Log

00:02:03 - INFO  | miuitask.main:36 - 开始执行每日签到任务
00:02:03 - ERROR | utils.get_token:226 - 遇到人机验证码, 尝试调用解决方案
00:02:03 - ERROR | utils.get_token_by_captcha:123 - 遇到人机验证码，无法获取TOKEN
00:02:04 - ERROR | utils.get_token:226 - 遇到人机验证码, 尝试调用解决方案
00:02:04 - ERROR | utils.get_token_by_captcha:123 - 遇到人机验证码，无法获取TOKEN
00:02:04 - ERROR | utils.get_token:233 - 遇到未知错误，无法获取TOKEN
00:02:04 - INFO  | sign.sign:131 - 未获取到token, 跳过每日签到

**Comment by Night-stars-1** [comment]
#228
