### ISSUE TITLE
人机验证码无法获取token

### ISSUE THREAD

**Issue by maodeyu180** [0-8-4/miui-auto-tasks#296]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.5

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.11

### Describe the Bug

人机验证码无法获取token
青龙面板2.17.10

### MIUITask Log

11:07:43 - INFO  | system_info.print_info:13 - MIUI-AUTO-TASK v1.7.5
11:07:43 - INFO  | system_info.print_info:14 - ---------- 系统信息 -------------
11:07:44 - INFO  | system_info.system_info:25 - 操作系统平台: Linux-4.4.35_ecoo_83020168-aarch64-with
11:07:44 - INFO  | system_info.system_info:26 - 操作系统版本: #1 SMP Thu Feb 1 19:19:56 UTC 2024
11:07:44 - INFO  | system_info.system_info:27 - 操作系统名称: Linux
11:07:44 - INFO  | system_info.system_info:28 - 操作系统位元: ('64bit', 'ELF')
11:07:44 - INFO  | system_info.system_info:29 - 操作系统类型: aarch64
11:07:44 - INFO  | system_info.system_info:30 - 处理器信息: 
11:07:44 - INFO  | system_info.system_info:31 - Python 版本: 3.11.9 ('main', 'Aug  2 2024 01:54:18')
11:07:44 - INFO  | system_info.print_info:16 - ---------- 项目信息 -------------
11:07:44 - INFO  | system_info.print_info:17 - 这是一个免费且开源的项目，如果你是付费购买获得请务必退款
11:07:44 - INFO  | system_info.print_info:18 - 项目地址：https://github.com/0-8-4/miui-auto-tasks
11:07:44 - INFO  | system_info.print_info:19 - 欢迎 star，感谢所有项目贡献者，已经提交issues的人，帮助项目发展的人
11:07:44 - INFO  | system_info.print_info:20 - ---------- 脚本日志 -------------
11:22:06 - SUCCESS | login.login:86 - 小米账号登录成功
11:22:06 - DEBUG | login.checkin_info:261 - {"time":0,"message":"success","entity":{"checkinInfoList":["请升级至小米社区4.99及以上版本参与签到","当前签到+1的概率：35.533%（每小时更新）"],"continueCheckInDays":0,"checkin7DaysDetail":[0,0,-1,-1,-1,-1,-1],"popLimit":3},"status":200}
11:22:06 - INFO  | login.checkin_info:263 - 当前签到+1的概率：35.533%（每小时更新）
11:22:07 - ERROR | miuitask.main:43 - 未找到抢先体验Beta版系统任务
11:22:07 - INFO  | miuitask.main:36 - 开始执行每日签到任务
11:22:07 - DEBUG | utils.get_token:220 - {"msg":"","code":0,"data":{"result":false,"id":"25369a7eea704e0781ee652de4410606","url":"https://static-verify.sec.xiaomi.com/v2/html/check.html?t=1&k=3dc42a135a8d45118034d1ab68213073&e=K0vsKzIUlvdpRA6uu4","token":""}}
11:22:07 - ERROR | utils.get_token:226 - 遇到人机验证码, 尝试调用解决方案
11:22:08 - DEBUG | utils.get_token_by_captcha:117 - {"msg":"","code":0,"data":{"result":false,"id":"25369a7eea704e0781ee652de4410606"}}
11:22:08 - ERROR | utils.get_token_by_captcha:123 - 遇到人机验证码，无法获取TOKEN
11:22:08 - DEBUG | utils.get_token:220 - {"msg":"","code":0,"data":{"result":false,"id":"bd0ee93be45b4abab70adfcb91e02d7e","url":"https://static-verify.sec.xiaomi.com/v2/html/check.html?t=1&k=3dc42a135a8d4511df441d7ce1e4b191","token":""}}
11:22:08 - ERROR | utils.get_token:226 - 遇到人机验证码, 尝试调用解决方案
11:22:08 - DEBUG | utils.get_token_by_captcha:117 - {"msg":"","code":0,"data":{"result":false,"id":"bd0ee93be45b4abab70adfcb91e02d7e"}}
11:22:08 - ERROR | utils.get_token_by_captcha:123 - 遇到人机验证码，无法获取TOKEN
11:22:08 - DEBUG | utils.get_token:220 - {"msg":"","code":0,"data":{"result":false,"id":"13a394c8bf104b9f96738db7c7335b10","url":"https://static-verify.sec.xiaomi.com/v2/html/check.html?t=1&k=3dc42a135a8d45118034d1ab68213073&","token":""}}
11:22:08 - ERROR | utils.get_token:226 - 遇到人机验证码, 尝试调用解决方案
11:22:09 - DEBUG | utils.get_token_by_captcha:117 - {"msg":"","code":0,"data":{"result":false,"id":"13a394c8bf104b9f96738db7c7335b10"}}
11:22:09 - ERROR | utils.get_token_by_captcha:123 - 遇到人机验证码，无法获取TOKEN
11:22:09 - ERROR | utils.get_token:239 - 获取TOKEN异常
Traceback (most recent call last):

  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 231, in get_token
    raise ValueError("人机验证失败")

ValueError: 人机验证失败

**Comment by BA7JCM** [comment]
@yudehai0204 没翻过已关闭issue导致的
