### ISSUE TITLE
[Bug] 运行后登录正常，消息推送正常，但是直接就结束了。

### ISSUE THREAD

**Issue by fayeharuna** [0-8-4/miui-auto-tasks#301]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.6-hotfix1

### Bug Found in Environment

Windows

### Bug Found in Python Version

3.11

### Describe the Bug

运行后登录正常，推送正常，但是任务没有完成就直接结束了。

### MIUITask Log

[日志文件.log](https://github.com/user-attachments/files/17783191/default.log)

### MIUITask Config

```shell
preference:
    geetest_url: ''
    geetest_params: {}
    geetest_data: {}
accounts:
-   uid: ''
    password: 
    cookies:
        passToken: 
    login_user_agent: ''
    user_agent: Mozilla/5.0 (Linux; Android 13) AppleWebKit/537.36 (KHTML, like Gecko)
        Version/4.0 Chrome/116.0.0.0 Safari/537.36
    device: ''
    device_model: ''
    CheckIn: true
    BrowseUserPage: true
    BrowsePost: true
    BrowseVideoPost: true
    ThumbUp: true
    BrowseSpecialPage: true
    BoardFollow: true
    CarrotPull: true
ONEPUSH:
    notifier: telegram
    params:
        title: null
        markdown: false
        token:
```

### Screenshots

![微信图片编辑_20241116110003](https://github.com/user-attachments/assets/2a1cc3bd-5d33-48a7-b4d8-7571f76c1b89)

**Comment by Night-stars-1** [comment]
填 login_user_agent
