### ISSUE TITLE
[Bug] （已解决）不能用青龙自带的面板去装2captcha依赖，运行脚本会显示装了错误的，会重新安装，实际上脚本重新装的也不能用

### ISSUE THREAD

**Issue by wdmhydw** [0-8-4/miui-auto-tasks#302]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.6.0.1

### Bug Found in Environment

Docker

### Bug Found in Python Version

3.11, 3.9

### Describe the Bug

运行脚本会显示装了错误的twocaptcha，会重新安装，实际上脚本重新装的也不能用
解决方法：
进入青龙的终端界面，先升级pip
pip install --upgrade pip
然后卸载旧版本2captcha
pip uninstall 2CAPTCHA-Python
再重新安装就可以使用了
pip install 2CAPTCHA-Python

### MIUITask Log

检测到已安装错误的 twocaptcha 包，正在尝试卸载并安装 2CAPTCHA-Python ...
Found existing installation: TwoCaptcha 0.0.1
Uninstalling TwoCaptcha-0.0.1:
  Successfully uninstalled TwoCaptcha-0.0.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Requirement already satisfied: 2CAPTCHA-Python in /usr/local/lib/python3.11/site-packages (1.5.0)
Requirement already satisfied: requests in /usr/local/lib/python3.11/site-packages (from 2CAPTCHA-Python) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/site-packages (from requests->2CAPTCHA-Python) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/site-packages (from requests->2CAPTCHA-Python) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/site-packages (from requests->2CAPTCHA-Python) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/site-packages (from requests->2CAPTCHA-Python) (2024.8.30)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
2CAPTCHA-Python 安装成功！正在尝试重新加载正确的依赖包
Traceback (most recent call last):
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 15, in <module>
    from utils.api.login import Login
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/api/login.py", line 17, in <module>
    from .sign import BaseSign
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/api/sign.py", line 17, in <module>
    from ..utils import get_random_chars_as_string, is_incorrect_return
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 49, in <module>
    from twocaptcha import TwoCaptcha
ImportError: cannot import name 'TwoCaptcha' from 'twocaptcha' (unknown location)

**Comment by Night-stars-1** [comment]
该项目没有使用2captcha依赖

**Comment by wdmhydw** [comment]
> 该项目没有使用2captcha依赖

过验证码的时候会用到

**Comment by Night-stars-1** [comment]
> > 该项目没有使用2captcha依赖
> 
> 过验证码的时候会用到

和这个项目没关系，本项目又没提供这类服务，也不会支持这类服务

**Comment by wdmhydw** [comment]
> > > 该项目没有使用2captcha依赖
> > 
> > 
> > 过验证码的时候会用到
> 
> 和这个项目没关系，本项目又没提供这类服务，也不会支持这类服务

好的打扰了
