### ISSUE TITLE
docker中自动运行 config.yaml的时间键值配置 找不到

### ISSUE THREAD

**Issue by zhangxu1233** [0-8-4/miui-auto-tasks#303]
### Verify Steps

- [X] Tracker 我已经在 [Issue Tracker](……/) 中找过我要提出的问题
- [X] Latest 我已经使用最新版本测试过，问题依旧存在
- [X] Code 这是 MIUITask 自身代码存在的问题，并非我所使用的 网络 或 设备 等特定问题
- [X] Meaningful 我提交的不是无意义的 催促更新或修复 请求

### MIUITask Version

v1.7.6

### Bug Found in Environment

Linux, Docker

### Bug Found in Python Version

3.12

### Describe the Bug

请问一下docker配置自动运行的config.yaml的时间键值在哪里配置？自动生成的此文件中没找到
![image](https://github.com/user-attachments/assets/f0faa746-85ac-41ed-8252-c84323638dd9)

### MIUITask Log

此问题与日志无关

**Comment by zhangxu1233** [comment]
已解决

**Comment by Volundio** [comment]
> 已解决

咋整，我也没搞懂
