### ISSUE TITLE
建议日后更新,只更新特定文件

### ISSUE THREAD

**Issue by bwmgd** [0-8-4/miui-auto-tasks#33]
比如只更新主文件,方便在服务器上自动化更新运行

**Comment by 0-8-4** [comment]
请问你的意思是想表达 

> 只更新 `配置文件之外的文件` 么

**Comment by kennylee60** [comment]
> 请问你的意思是想表达
> 
> > 只更新 `配置文件之外的文件` 么

用着1.3的是不是更新miuitask.py就可以了

**Comment by 0-8-4** [comment]
> > 请问你的意思是想表达
> > > 只更新 `配置文件之外的文件` 么
> 
> 用着1.3的是不是更新miuitask.py就可以了

理论上只要没有报错，就可以。
我们的配置文件是非必要不修改的
但是这边的建议是，每次更新的话，直接从release里面下载新的。然后复制配置文件过去。
但是 配置文件在 #32 已经被重命名了
而且 基于 #23 我们会再次修改配置文件的格式已经实现方式。目前还在讨论这个。

**Comment by kennylee60** [comment]
> > > 请问你的意思是想表达
> > > > 只更新 `配置文件之外的文件` 么
> > 
> > 
> > 用着1.3的是不是更新miuitask.py就可以了
> 
> 理论上只要没有报错，就可以。
> 我们的配置文件是非必要不修改的
> 但是这边的建议是，每次更新的话，直接从release里面下载新的。然后复制配置文件过去。
> 但是 配置文件在 #32 已经被重命名了
> 而且 基于 #23 我们会再次修改配置文件的格式已经实现方式。目前还在讨论这个。

现在release下载的还是.env，还没有合并吧

**Comment by 0-8-4** [comment]
> ``现在release下载的还是.env，还没有合并吧

是的，还没有合并
