### ISSUE TITLE
脚本任务未全部完成

### ISSUE THREAD

**Issue by laoshuaibip** [0-8-4/miui-auto-tasks#34]
评论5次的内测分好像只完成3次，还差2分，希望改一下，不然需要一天运行2次脚本能全部完成。活跃分里的发帖也没完成。

**Comment by TardisXE** [comment]
感谢反馈，目前已经定位到问题，最快今晚修复并合并更新。

**Comment by jw8013** [comment]
> 感谢反馈，目前已经定位到问题，最快今晚修复并合并更新。

评论5次，依然只有3次，日志里面也是3次回复成功
09:44:06 | 开始登录小米账号
09:44:07 | 账号登录完成
09:44:07 | 本脚本支持社区签到，因该功能存在风险默认禁用
09:44:07 | 如您愿意承担一切可能的后果，可编辑配置文件手动打开该功能
09:44:07 | 风险功能提示：正在进行社区签到
09:44:07 | 社区拔萝卜签到成功
09:44:08 | 开始活跃分任务成功
09:44:08 | 正在完成BUG反馈任务
09:44:08 | 发表内容成功，帖子ID：30789203，将在3秒后删除
09:44:08 | **回复成功**
09:44:12 | 删除内容成功：ok
09:44:12 | 删除内容成功：帖子已被删除
09:44:12 | 删除内容成功：帖子已被删除
09:44:12 | 删除内容成功：帖子已被删除
09:44:13 | 删除内容成功：帖子已被删除
09:44:13 | 3秒后执行提建议任务
09:44:13 | 领取活跃分成功
09:44:16 | 正在完成提建议任务
09:44:16 | 发表内容成功，帖子ID：30647081，将在3秒后删除
09:44:17 | **回复成功**
09:44:20 | 删除内容成功：ok
09:44:20 | 删除内容成功：帖子已被删除
09:44:20 | 删除内容成功：帖子已被删除
09:44:21 | 删除内容成功：帖子已被删除
09:44:21 | 删除内容成功：帖子已被删除
09:44:21 | 正在完成满意度调查任务
09:44:22 | 获取问卷ID成功：137
09:44:22 | 满意度投票成功
09:44:22 | 正在完成点赞任务
09:44:22 | 开始活跃分任务成功
09:44:23 | 点赞成功
09:44:23 | 取消点赞成功
09:44:24 | 点赞成功
09:44:24 | 取消点赞成功
09:44:25 | 点赞成功
09:44:25 | 取消点赞成功
09:44:26 | 点赞成功
09:44:26 | 取消点赞成功
09:44:27 | 点赞成功
09:44:27 | 取消点赞成功
09:44:28 | 领取活跃分成功
09:44:28 | 正在完成活跃分_关注任务
09:44:28 | 开始活跃分任务成功
09:44:28 | 取关用户成功
09:44:28 | 关注用户成功
09:44:28 | 5秒后领取活跃分_关注任务
09:44:34 | 领取活跃分成功
09:44:34 | 正在完成活跃分_加圈任务
09:44:34 | 开始活跃分任务成功
09:44:34 | 退出圈子成功
09:44:34 | 加入圈子成功
09:44:34 | 5秒后领取活跃分_加圈任务
09:44:40 | 领取活跃分成功
09:44:40 | 正在完成活跃分_发帖任务
09:44:40 | 开始活跃分任务成功
09:44:40 | 发表内容成功，帖子ID：30647086，将在3秒后删除
09:44:41 | **回复成功**
09:44:44 | 删除内容成功：ok
09:44:44 | 删除内容成功：帖子已被删除
09:44:45 | 删除内容成功：帖子已被删除
09:44:45 | 删除内容成功：帖子已被删除
09:44:45 | 删除内容成功：帖子已被删除
09:44:45 | 5秒后领取活跃分_发帖任务
09:44:50 | 领取活跃分成功

**Comment by TardisXE** [comment]
目前正常脚本会执行3次发帖和回帖以及五次点赞，个人认为这些已经可以获取到足够的分数。本脚本的最初目的是方便完成社区内测KPI而非内测分刷取工具，在下个大版本中才有可能对内测分获取进行修改。> > 感谢反馈，目前已经定位到问题，最快今晚修复并合并更新。
> 
> 
> 
> 评论5次，依然只有3次，日志里面也是3次回复成功
> 
> 09:44:06 | 开始登录小米账号
> 
> 09:44:07 | 账号登录完成
> 
> 09:44:07 | 本脚本支持社区签到，因该功能存在风险默认禁用
> 
> 09:44:07 | 如您愿意承担一切可能的后果，可编辑配置文件手动打开该功能
> 
> 09:44:07 | 风险功能提示：正在进行社区签到
> 
> 09:44:07 | 社区拔萝卜签到成功
> 
> 09:44:08 | 开始活跃分任务成功
> 
> 09:44:08 | 正在完成BUG反馈任务
> 
> 09:44:08 | 发表内容成功，帖子ID：30789203，将在3秒后删除
> 
> 09:44:08 | **回复成功**
> 
> 09:44:12 | 删除内容成功：ok
> 
> 09:44:12 | 删除内容成功：帖子已被删除
> 
> 09:44:12 | 删除内容成功：帖子已被删除
> 
> 09:44:12 | 删除内容成功：帖子已被删除
> 
> 09:44:13 | 删除内容成功：帖子已被删除
> 
> 09:44:13 | 3秒后执行提建议任务
> 
> 09:44:13 | 领取活跃分成功
> 
> 09:44:16 | 正在完成提建议任务
> 
> 09:44:16 | 发表内容成功，帖子ID：30647081，将在3秒后删除
> 
> 09:44:17 | **回复成功**
> 
> 09:44:20 | 删除内容成功：ok
> 
> 09:44:20 | 删除内容成功：帖子已被删除
> 
> 09:44:20 | 删除内容成功：帖子已被删除
> 
> 09:44:21 | 删除内容成功：帖子已被删除
> 
> 09:44:21 | 删除内容成功：帖子已被删除
> 
> 09:44:21 | 正在完成满意度调查任务
> 
> 09:44:22 | 获取问卷ID成功：137
> 
> 09:44:22 | 满意度投票成功
> 
> 09:44:22 | 正在完成点赞任务
> 
> 09:44:22 | 开始活跃分任务成功
> 
> 09:44:23 | 点赞成功
> 
> 09:44:23 | 取消点赞成功
> 
> 09:44:24 | 点赞成功
> 
> 09:44:24 | 取消点赞成功
> 
> 09:44:25 | 点赞成功
> 
> 09:44:25 | 取消点赞成功
> 
> 09:44:26 | 点赞成功
> 
> 09:44:26 | 取消点赞成功
> 
> 09:44:27 | 点赞成功
> 
> 09:44:27 | 取消点赞成功
> 
> 09:44:28 | 领取活跃分成功
> 
> 09:44:28 | 正在完成活跃分_关注任务
> 
> 09:44:28 | 开始活跃分任务成功
> 
> 09:44:28 | 取关用户成功
> 
> 09:44:28 | 关注用户成功
> 
> 09:44:28 | 5秒后领取活跃分_关注任务
> 
> 09:44:34 | 领取活跃分成功
> 
> 09:44:34 | 正在完成活跃分_加圈任务
> 
> 09:44:34 | 开始活跃分任务成功
> 
> 09:44:34 | 退出圈子成功
> 
> 09:44:34 | 加入圈子成功
> 
> 09:44:34 | 5秒后领取活跃分_加圈任务
> 
> 09:44:40 | 领取活跃分成功
> 
> 09:44:40 | 正在完成活跃分_发帖任务
> 
> 09:44:40 | 开始活跃分任务成功
> 
> 09:44:40 | 发表内容成功，帖子ID：30647086，将在3秒后删除
> 
> 09:44:41 | **回复成功**
> 
> 09:44:44 | 删除内容成功：ok
> 
> 09:44:44 | 删除内容成功：帖子已被删除
> 
> 09:44:45 | 删除内容成功：帖子已被删除
> 
> 09:44:45 | 删除内容成功：帖子已被删除
> 
> 09:44:45 | 删除内容成功：帖子已被删除
> 
> 09:44:45 | 5秒后领取活跃分_发帖任务
> 
> 09:44:50 | 领取活跃分成功

**Comment by laoshuaibip** [comment]
> > 感谢反馈，目前已经定位到问题，最快今晚修复并合并更新。
> 
> 评论5次，依然只有3次，日志里面也是3次回复成功
> 09:44:06 | 开始登录小米账号
> 09:44:07 | 账号登录完成
> 09:44:07 | 本脚本支持社区签到，因该功能存在风险默认禁用
> 09:44:07 | 如您愿意承担一切可能的后果，可编辑配置文件手动打开该功能
> 09:44:07 | 风险功能提示：正在进行社区签到
> 09:44:07 | 社区拔萝卜签到成功
> 09:44:08 | 开始活跃分任务成功
> 09:44:08 | 正在完成BUG反馈任务
> 09:44:08 | 发表内容成功，帖子ID：30789203，将在3秒后删除
> 09:44:08 | **回复成功**
> 09:44:12 | 删除内容成功：ok
> 09:44:12 | 删除内容成功：帖子已被删除
> 09:44:12 | 删除内容成功：帖子已被删除
> 09:44:12 | 删除内容成功：帖子已被删除
> 09:44:13 | 删除内容成功：帖子已被删除
> 09:44:13 | 3秒后执行提建议任务
> 09:44:13 | 领取活跃分成功
> 09:44:16 | 正在完成提建议任务
> 09:44:16 | 发表内容成功，帖子ID：30647081，将在3秒后删除
> 09:44:17 | **回复成功**
> 09:44:20 | 删除内容成功：ok
> 09:44:20 | 删除内容成功：帖子已被删除
> 09:44:20 | 删除内容成功：帖子已被删除
> 09:44:21 | 删除内容成功：帖子已被删除
> 09:44:21 | 删除内容成功：帖子已被删除
> 09:44:21 | 正在完成满意度调查任务
> 09:44:22 | 获取问卷ID成功：137
> 09:44:22 | 满意度投票成功
> 09:44:22 | 正在完成点赞任务
> 09:44:22 | 开始活跃分任务成功
> 09:44:23 | 点赞成功
> 09:44:23 | 取消点赞成功
> 09:44:24 | 点赞成功
> 09:44:24 | 取消点赞成功
> 09:44:25 | 点赞成功
> 09:44:25 | 取消点赞成功
> 09:44:26 | 点赞成功
> 09:44:26 | 取消点赞成功
> 09:44:27 | 点赞成功
> 09:44:27 | 取消点赞成功
> 09:44:28 | 领取活跃分成功
> 09:44:28 | 正在完成活跃分_关注任务
> 09:44:28 | 开始活跃分任务成功
> 09:44:28 | 取关用户成功
> 09:44:28 | 关注用户成功
> 09:44:28 | 5秒后领取活跃分_关注任务
> 09:44:34 | 领取活跃分成功
> 09:44:34 | 正在完成活跃分_加圈任务
> 09:44:34 | 开始活跃分任务成功
> 09:44:34 | 退出圈子成功
> 09:44:34 | 加入圈子成功
> 09:44:34 | 5秒后领取活跃分_加圈任务
> 09:44:40 | 领取活跃分成功
> 09:44:40 | 正在完成活跃分_发帖任务
> 09:44:40 | 开始活跃分任务成功
> 09:44:40 | 发表内容成功，帖子ID：30647086，将在3秒后删除
> 09:44:41 | **回复成功**
> 09:44:44 | 删除内容成功：ok
> 09:44:44 | 删除内容成功：帖子已被删除
> 09:44:45 | 删除内容成功：帖子已被删除
> 09:44:45 | 删除内容成功：帖子已被删除
> 09:44:45 | 删除内容成功：帖子已被删除
> 09:44:45 | 5秒后领取活跃分_发帖任务
> 09:44:50 | 领取活跃分成功

看其他的issues，作者好像不想改这里

**Comment by jw8013** [comment]
> > > 感谢反馈，目前已经定位到问题，最快今晚修复并合并更新。
> > 
> > 
> > 评论5次，依然只有3次，日志里面也是3次回复成功
> > 09:44:06 | 开始登录小米账号
> > 09:44:07 | 账号登录完成
> > 09:44:07 | 本脚本支持社区签到，因该功能存在风险默认禁用
> > 09:44:07 | 如您愿意承担一切可能的后果，可编辑配置文件手动打开该功能
> > 09:44:07 | 风险功能提示：正在进行社区签到
> > 09:44:07 | 社区拔萝卜签到成功
> > 09:44:08 | 开始活跃分任务成功
> > 09:44:08 | 正在完成BUG反馈任务
> > 09:44:08 | 发表内容成功，帖子ID：30789203，将在3秒后删除
> > 09:44:08 | **回复成功**
> > 09:44:12 | 删除内容成功：ok
> > 09:44:12 | 删除内容成功：帖子已被删除
> > 09:44:12 | 删除内容成功：帖子已被删除
> > 09:44:12 | 删除内容成功：帖子已被删除
> > 09:44:13 | 删除内容成功：帖子已被删除
> > 09:44:13 | 3秒后执行提建议任务
> > 09:44:13 | 领取活跃分成功
> > 09:44:16 | 正在完成提建议任务
> > 09:44:16 | 发表内容成功，帖子ID：30647081，将在3秒后删除
> > 09:44:17 | **回复成功**
> > 09:44:20 | 删除内容成功：ok
> > 09:44:20 | 删除内容成功：帖子已被删除
> > 09:44:20 | 删除内容成功：帖子已被删除
> > 09:44:21 | 删除内容成功：帖子已被删除
> > 09:44:21 | 删除内容成功：帖子已被删除
> > 09:44:21 | 正在完成满意度调查任务
> > 09:44:22 | 获取问卷ID成功：137
> > 09:44:22 | 满意度投票成功
> > 09:44:22 | 正在完成点赞任务
> > 09:44:22 | 开始活跃分任务成功
> > 09:44:23 | 点赞成功
> > 09:44:23 | 取消点赞成功
> > 09:44:24 | 点赞成功
> > 09:44:24 | 取消点赞成功
> > 09:44:25 | 点赞成功
> > 09:44:25 | 取消点赞成功
> > 09:44:26 | 点赞成功
> > 09:44:26 | 取消点赞成功
> > 09:44:27 | 点赞成功
> > 09:44:27 | 取消点赞成功
> > 09:44:28 | 领取活跃分成功
> > 09:44:28 | 正在完成活跃分_关注任务
> > 09:44:28 | 开始活跃分任务成功
> > 09:44:28 | 取关用户成功
> > 09:44:28 | 关注用户成功
> > 09:44:28 | 5秒后领取活跃分_关注任务
> > 09:44:34 | 领取活跃分成功
> > 09:44:34 | 正在完成活跃分_加圈任务
> > 09:44:34 | 开始活跃分任务成功
> > 09:44:34 | 退出圈子成功
> > 09:44:34 | 加入圈子成功
> > 09:44:34 | 5秒后领取活跃分_加圈任务
> > 09:44:40 | 领取活跃分成功
> > 09:44:40 | 正在完成活跃分_发帖任务
> > 09:44:40 | 开始活跃分任务成功
> > 09:44:40 | 发表内容成功，帖子ID：30647086，将在3秒后删除
> > 09:44:41 | **回复成功**
> > 09:44:44 | 删除内容成功：ok
> > 09:44:44 | 删除内容成功：帖子已被删除
> > 09:44:45 | 删除内容成功：帖子已被删除
> > 09:44:45 | 删除内容成功：帖子已被删除
> > 09:44:45 | 删除内容成功：帖子已被删除
> > 09:44:45 | 5秒后领取活跃分_发帖任务
> > 09:44:50 | 领取活跃分成功
> 
> 看其他的issues，作者好像不想改这里

额，好吧！

**Comment by jw8013** [comment]
> > > 感谢反馈，目前已经定位到问题，最快今晚修复并合并更新。
> > 
> > 
> > 评论5次，依然只有3次，日志里面也是3次回复成功
> > 09:44:06 | 开始登录小米账号
> > 09:44:07 | 账号登录完成
> > 09:44:07 | 本脚本支持社区签到，因该功能存在风险默认禁用
> > 09:44:07 | 如您愿意承担一切可能的后果，可编辑配置文件手动打开该功能
> > 09:44:07 | 风险功能提示：正在进行社区签到
> > 09:44:07 | 社区拔萝卜签到成功
> > 09:44:08 | 开始活跃分任务成功
> > 09:44:08 | 正在完成BUG反馈任务
> > 09:44:08 | 发表内容成功，帖子ID：30789203，将在3秒后删除
> > 09:44:08 | **回复成功**
> > 09:44:12 | 删除内容成功：ok
> > 09:44:12 | 删除内容成功：帖子已被删除
> > 09:44:12 | 删除内容成功：帖子已被删除
> > 09:44:12 | 删除内容成功：帖子已被删除
> > 09:44:13 | 删除内容成功：帖子已被删除
> > 09:44:13 | 3秒后执行提建议任务
> > 09:44:13 | 领取活跃分成功
> > 09:44:16 | 正在完成提建议任务
> > 09:44:16 | 发表内容成功，帖子ID：30647081，将在3秒后删除
> > 09:44:17 | **回复成功**
> > 09:44:20 | 删除内容成功：ok
> > 09:44:20 | 删除内容成功：帖子已被删除
> > 09:44:20 | 删除内容成功：帖子已被删除
> > 09:44:21 | 删除内容成功：帖子已被删除
> > 09:44:21 | 删除内容成功：帖子已被删除
> > 09:44:21 | 正在完成满意度调查任务
> > 09:44:22 | 获取问卷ID成功：137
> > 09:44:22 | 满意度投票成功
> > 09:44:22 | 正在完成点赞任务
> > 09:44:22 | 开始活跃分任务成功
> > 09:44:23 | 点赞成功
> > 09:44:23 | 取消点赞成功
> > 09:44:24 | 点赞成功
> > 09:44:24 | 取消点赞成功
> > 09:44:25 | 点赞成功
> > 09:44:25 | 取消点赞成功
> > 09:44:26 | 点赞成功
> > 09:44:26 | 取消点赞成功
> > 09:44:27 | 点赞成功
> > 09:44:27 | 取消点赞成功
> > 09:44:28 | 领取活跃分成功
> > 09:44:28 | 正在完成活跃分_关注任务
> > 09:44:28 | 开始活跃分任务成功
> > 09:44:28 | 取关用户成功
> > 09:44:28 | 关注用户成功
> > 09:44:28 | 5秒后领取活跃分_关注任务
> > 09:44:34 | 领取活跃分成功
> > 09:44:34 | 正在完成活跃分_加圈任务
> > 09:44:34 | 开始活跃分任务成功
> > 09:44:34 | 退出圈子成功
> > 09:44:34 | 加入圈子成功
> > 09:44:34 | 5秒后领取活跃分_加圈任务
> > 09:44:40 | 领取活跃分成功
> > 09:44:40 | 正在完成活跃分_发帖任务
> > 09:44:40 | 开始活跃分任务成功
> > 09:44:40 | 发表内容成功，帖子ID：30647086，将在3秒后删除
> > 09:44:41 | **回复成功**
> > 09:44:44 | 删除内容成功：ok
> > 09:44:44 | 删除内容成功：帖子已被删除
> > 09:44:45 | 删除内容成功：帖子已被删除
> > 09:44:45 | 删除内容成功：帖子已被删除
> > 09:44:45 | 删除内容成功：帖子已被删除
> > 09:44:45 | 5秒后领取活跃分_发帖任务
> > 09:44:50 | 领取活跃分成功
> 
> 看其他的issues，作者好像不想改这里

额，好吧
