### ISSUE TITLE
可否增加云函数的使用方法吗？

### ISSUE THREAD

**Issue by q3v5** [0-8-4/miui-auto-tasks#36]
感觉这个放到云函数非常合适，自己试了试不会弄，不知道大佬会不会考虑一下

**Comment by wonderhong** [comment]
支持

**Comment by ghost** [comment]
🎉 Tencent SCF Support Now
-  See [Wiki](https://github.com/0-8-4/miui-auto-tasks/wiki/Run-on-SCF)
