### ISSUE TITLE
腾讯云函数方式需要短信验证码，无法登录账户

### ISSUE THREAD

**Issue by CirnoSalt** [0-8-4/miui-auto-tasks#45]
12:41:37 | MIUITask_v1.3.3

12:41:37 | ----------系统信息-开始-------------

12:41:37 | 系统及版本信息: Linux-4.18.0-348.2.1.el8_5.x86_64-x86_64-with-centos-7.7.1908-Core

12:41:37 | 系统版本号: #1 SMP Tue Nov 16 14:42:35 UTC 2021

12:41:37 | 系统名称: Linux

12:41:37 | 系统位数: ('64bit', '')

12:41:37 | 计算机类型: x86_64

12:41:37 | 处理器类型: x86_64

12:41:37 | Python版本: 3.6.1 ('default', 'Jul 25 2018 11:41:55')

12:41:37 | ----------系统信息-结束-------------

12:41:37 | 项目地址：https://github.com/0-8-4/miui-auto-tasks

12:41:37 | 欢迎star，感谢東雲研究所中的大佬

12:41:37 | ----------检测配置文件-------------

12:41:37 | 正在使用 /var/user/config.env 作为配置文件

12:41:37 | config.env 已配置

Starting new HTTPS connection (1): account.xiaomi.com:443

https://account.xiaomi.com:443 "POST /pass/serviceLoginAuth2 HTTP/1.1" 200 None

12:41:37 | 当前账号需要短信验证码，请尝试修改UA或设备ID

在本地测试时可以正常登录，配置文件中没有看到关于"设备ID"相关的参数。

**Comment by ghost** [comment]
在 **index.py (miuitask.py)** 的 **525** 行添加参数：

`miui = MIUITask(mi_id, p_md5, l_ua, board_id, dev_id='device_id_here')`

https://github.com/0-8-4/miui-auto-tasks/blob/106dca362a654583b3cd868fdb5a3160dd970369/miuitask.py#L525

下个版本会在配置文件中加入 设备ID 字段

**Comment by CirnoSalt** [comment]
请问设备ID如何获取？试了下已登录目标账号机器上的IMEI以及devcheck获取的Device ID都会返回错误：
`{"errorCode":-1,"errorMessage":"user code exception caught","requestId":"e26f5281-4a7b-4571-8ba7-a30b697c8be1","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 526, in main_handler\n    start(miui, config.get('SIGN_IN'), config.get('ENHANCED_MODE'))\n  File \"/var/user/index.py\", line 458, in start\n    if miui_task.mi_login():\n  File \"/var/user/index.py\", line 380, in mi_login\n    'Cookie': 'deviceId=' + str(self.dev_id) + '; pass_ua=web; uLocale=zh_CN'\nAttributeError: 'MIUITask' object has no attribute 'dev_id'","statusCode":430}`

**Comment by ghost** [comment]
尝试填写 MIUI 的 **虚拟身份ID** （**OAID**）

设置 - 隐私保护 - 管理 - 特殊应用权限 - 虚拟身份管理

**Comment by CirnoSalt** [comment]
> 尝试填写 MIUI 的 **虚拟身份ID** （**OAID**）
> 
> 设置 - 隐私保护 - 管理 - 特殊应用权限 - 虚拟身份管理


尝试填入之后测试失败，依然返回：
`{"errorCode":-1,"errorMessage":"user code exception caught","requestId":"05233dd2-45f4-498c-bf14-a7d3b8a0210d","stackTrace":"Traceback (most recent call last):\n  File \"/var/user/index.py\", line 526, in main_handler\n    start(miui, config.get('SIGN_IN'), config.get('ENHANCED_MODE'))\n  File \"/var/user/index.py\", line 458, in start\n    if miui_task.mi_login():\n  File \"/var/user/index.py\", line 380, in mi_login\n    'Cookie': 'deviceId=' + str(self.dev_id) + '; pass_ua=web; uLocale=zh_CN'\nAttributeError: 'MIUITask' object has no attribute 'dev_id'","statusCode":430}`

**Comment by ghost** [comment]
疑似是由于腾讯云的 IP 段导致触发风控，可以尝试租用一台与云函数同区的按需实例进行一次成功的正常登录

**Comment by TardisXE** [comment]
小米账户有异地登录风控策略，甚至填写Device ID后也无效。建议找在云函数服务器当地的朋友用电脑登录一下account.xiaomi.com，大概率能解决问题。

**Comment by CirnoSalt** [comment]
好吧……看来还是得乖乖挂在本地了
