### ISSUE TITLE
麻烦作者可以尝试增加每日签到领金币

### ISSUE THREAD

**Issue by xxld1179** [0-8-4/miui-auto-tasks#5]
每日签到领金币，虽然没非常大的用处，但是顺便还是挺不错的，麻烦作者啦！
就是那个拔萝卜那个，在个人主页那边

**Comment by TardisXE** [comment]
#7 
该功能在v1.2.1中已添加，但根据社区规范我们默认禁用了，如果接受风险可以参考更新说明手动打开

**Comment by 0-8-4** [comment]
Finished in #7. Now, closed
