### ISSUE TITLE
请问后续能开发日志功能，或者推送吗？

### ISSUE THREAD

**Issue by QiHsMing** [0-8-4/miui-auto-tasks#50]
请问后续能开发日志功能，或者推送吗？

**Comment by 0-8-4** [comment]
请问 什么叫 日志功能 和 推送

**Comment by QiHsMing** [comment]
> 请问 什么叫 日志功能 和 推送

感谢回复！抱歉，我没有把问题说详细，我的想法是 
1）日志功能：能不能把输出结果写入到日志文件中；
2）推送功能：接入一些常用的推送接口把输出结果推送出去，比如dingtalk（钉钉）、企业微信应用消息（企业微信）、telegram（TG）、Bark（iOS）、server 酱（微信）、server 酱 TURBO（微信）。

**Comment by 0-8-4** [comment]
> > 请问 什么叫 日志功能 和 推送
> 
> 
> 
> 感谢回复！抱歉，我没有把问题说详细，我的想法是 
> 
> 1）日志功能：能不能把输出结果写入到日志文件中；
> 
> 2）推送功能：接入一些常用的推送接口把输出结果推送出去，比如dingtalk（钉钉）、企业微信应用消息（企业微信）、telegram（TG）、Bark（iOS）、server 酱（微信）、server 酱 TURBO（微信）。

你好。首先，日志功能输出到文件，这个应该是有的，你可以看一下

推送的话 可以考虑做 （我有时间的话

**Comment by QiHsMing** [comment]
> > > 请问 什么叫 日志功能 和 推送
> > 
> > 
> > 感谢回复！抱歉，我没有把问题说详细，我的想法是
> > 1）日志功能：能不能把输出结果写入到日志文件中；
> > 2）推送功能：接入一些常用的推送接口把输出结果推送出去，比如dingtalk（钉钉）、企业微信应用消息（企业微信）、telegram（TG）、Bark（iOS）、server 酱（微信）、server 酱 TURBO（微信）。
> 
> 你好。首先，日志功能输出到文件，这个应该是有的，你可以看一下
> 
> 推送的话 可以考虑做 （我有时间的话



> > > 请问 什么叫 日志功能 和 推送
> > 
> > 
> > 感谢回复！抱歉，我没有把问题说详细，我的想法是
> > 1）日志功能：能不能把输出结果写入到日志文件中；
> > 2）推送功能：接入一些常用的推送接口把输出结果推送出去，比如dingtalk（钉钉）、企业微信应用消息（企业微信）、telegram（TG）、Bark（iOS）、server 酱（微信）、server 酱 TURBO（微信）。
> 
> 你好。首先，日志功能输出到文件，这个应该是有的，你可以看一下
> 
> 推送的话 可以考虑做 （我有时间的话


好的谢谢！ 我找到了配置文件里，设置日志选项了。
