### ISSUE TITLE
「公告」该项目已暂停维护

### ISSUE THREAD

**Issue by 0-8-4** [0-8-4/miui-auto-tasks#53]
该项目由于MIUI  官方的内测分规则变动，现已暂时维护。由于增加了答题功能，并且帖子删除之后会倒扣分。
项目维护者在这里建议各位停用这脚本。

感谢大家在这半年多来的支持和支持，谢谢所有star和fork的人。我们下个项目再会（如果有的话）

**Comment by 0-8-4** [comment]
#52

**Comment by wonderhong** [comment]
现在社区4.0加了新的成长值规则，大佬还有没有考虑重启项目呀

**Comment by TardisXE** [comment]
> 现在社区4.0加了新的成长值规则，大佬还有没有考虑重启项目呀

#54

**Comment by wonderhong** [comment]
> > 现在社区4.0加了新的成长值规则，大佬还有没有考虑重启项目呀
> 
> #54

感谢大佬维护👍
