### ISSUE TITLE
最新版本没有发布到docker hub 

### ISSUE THREAD

**Issue by appdev** [0-8-4/miui-auto-tasks#58]
适配 4.0 的新版能推送到 docke hub 吗？

**Comment by 0-8-4** [comment]
docker pull [o1si/miui-auto-tasks:latest](https://hub.docker.com/layers/o1si/miui-auto-tasks/1.5.1/images/sha256-7641f99fe3fed43e75b86933a936b0374364e7e2559084f6bd232ee05917e161?context=explore)

已上传，试完没问题麻烦关闭这个issue，谢谢

**Comment by appdev** [comment]
感谢
