### ISSUE TITLE
程序报错，麻烦作者看一下

### ISSUE THREAD

**Issue by okatu-loli** [0-8-4/miui-auto-tasks#6]
PS C:\Users\Fan_G\Downloads\Compressed\miui-auto-tasks-1.1.0\miui-auto-tasks-1.1.0> python .\miuitask.py
Traceback (most recent call last):
  File "C:\Users\Fan_G\Downloads\Compressed\miui-auto-tasks-1.1.0\miui-auto-tasks-1.1.0\miuitask.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by 0-8-4** [comment]
> PS C:\Users\Fan_G\Downloads\Compressed\miui-auto-tasks-1.1.0\miui-auto-tasks-1.1.0> python .\miuitask.py
> Traceback (most recent call last):
> File "C:\Users\Fan_G\Downloads\Compressed\miui-auto-tasks-1.1.0\miui-auto-tasks-1.1.0\miuitask.py", line 2, in 
> import requests
> ModuleNotFoundError: No module named 'requests'

麻烦查看这一点的 第二条 [https://github.com/0-8-4/miui-auto-tasks#%E5%AE%89%E8%A3%85%E4%BE%9D%E8%B5%96](安装依赖)

**Comment by okatu-loli** [comment]
啊这，原来没安装依赖 打扰了

**Comment by 0-8-4** [comment]
> 啊这，原来没安装依赖 打扰了

OK没问题之后，记得close
