### ISSUE TITLE
「公告」旧版配置文件将停止支持

### ISSUE THREAD

**Issue by 0-8-4** [0-8-4/miui-auto-tasks#63]
新版配置文件也已经发布了将近一年了，随着小米社区幺蛾子整的越来越多。~~谁知道以后会不会整一个去转发一条微博，然后再回调到小米社区以完成任务这样的幺蛾子~~。旧版的配置文件的校验性代码也越来越长  ~~（虽然也就20行）~~。其易用性和便利性都是 YAML 比不上的，并且也不支持多账户配置。

**我们将在下一个版本的更新中移除旧版配置文件的相关支持**，至于下一个版本是什么时候，那就不得而知了。所以还没有转新版配置文件的人，还是有很多时间可以转的🤔。

**Comment by By-The** [comment]
可以重新适配一下腾讯云函数吗？

**Comment by TardisXE** [comment]
旧格式文件支持已于v1.6.0版本终止
