### ISSUE TITLE
运行docker容器，功能未生效可能是什么原因么？

### ISSUE THREAD

**Issue by coldwarm7** [0-8-4/miui-auto-tasks#66]
mac上通过chrome登录小米社区获取的user-agent，docker镜像跑在linux虚拟机上，挂载了配置文件，改了一下配置文件宿主机的路径/root/miui_task/config.yaml:/srv/config.yaml。

**Comment by 0-8-4** [comment]
这边烦请贴出完整的`log日志`以及`config文件`作为排查排查，记得隐去关键信息

**Comment by coldwarm7** [comment]
这个是配置文件，log日志在哪里查呢，镜像没有bash，登不上去
accounts:
  - uid: xx
    password: xxx
    user-agent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36'
    carrot-pull: false
    check-in: false
    browse-specialpage: false

**Comment by 0-8-4** [comment]
根据这个config 请问是不是之前在wiki 里面复制的config。

**Comment by 0-8-4** [comment]
这个问题 和 #67  重复，使用新的配置文件可以解决。
