### ISSUE TITLE
wiki的config.yaml模板缺少version字段

### ISSUE THREAD

**Issue by AzideCupric** [0-8-4/miui-auto-tasks#67]
如果按照[wiki](https://github.com/0-8-4/miui-auto-tasks/wiki#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6)里给的config.yaml模板填写配置信息的话是不存在version这项配置的
我在挂载到docker之后发现过不了config_version这部分的检查（会在四点运行的时候报错
https://github.com/0-8-4/miui-auto-tasks/blob/dbf51d0cc23afa3d11fb8eacd488d0bb129cdc65/utils/utils.py#L11
https://github.com/0-8-4/miui-auto-tasks/blob/dbf51d0cc23afa3d11fb8eacd488d0bb129cdc65/utils/utils.py#L70-L79

**Comment by 0-8-4** [comment]
收到，wiki还没来得及更新，可以直接在主分支下载最新的config文件。

**Comment by 0-8-4** [comment]
感谢提醒，wiki已经更新

**Comment by AzideCupric** [comment]
好的，更新了就好
