### ISSUE TITLE
【提问】大佬有没有适配青龙的计划呢

### ISSUE THREAD

**Issue by fmz200** [0-8-4/miui-auto-tasks#68]
目前的项目结构也是可以弄到青龙里面跑的，但是小白不太会操作，所以想咨询有没有适配青龙的计划😁

**Comment by TardisXE** [comment]
青龙面板-订阅管理-新建订阅，将`ql repo https://github.com/0-8-4/miui-auto-tasks.git miuitask utils|init utils|config master py|yaml `拷贝到名称中，手动设置定时规则如`interval 每 1 天`，然后运行订阅
青龙面板-依赖管理-新建依赖，分别新建名称为`requests`和`python-dotenv`及`pyyaml`的依赖，类型均为`python3`
在青龙面板-脚本管理中，找到miuitask文件夹下的config.yaml文件，编辑账户信息及功能项目后尝试手动运行，日志中无报错即可

**Comment by liuxi378** [comment]
> 青龙-订阅-新建-新建，将，`ql repo https://github.com/0-8-4/miui-auto-tasks.git miuitask utils|init utils|config master py|yaml `将名称中中，手动到名称，手动定时规则`interval 每 1 天`，然后规则如，然后然后规则 ，然后然后青龙青龙青龙青龙面板面板面板依赖依赖依赖管理管理管理管理新建新建新建新建新建新建新建新建新建新建`requests`新建`python-dotenv`新建 新建管理中，找到miuitask文件夹下的config.yaml文件，编辑账号信息及功能项目后试手动运行，日志中无报错即可`pyyaml``python3`

请问是在定时任务里面运行吗？我找了没找到任务，是需要添加定时任务吗？在订阅里面点击运行只是重新拉取文件

**Comment by fmz200** [comment]
> > 青龙-订阅-新建-新建，将，`ql repo https://github.com/0-8-4/miui-auto-tasks.git miuitask utils|init utils|config master py|yaml `将名称中中，手动到名称，手动定时规则`interval 每 1 天`，然后规则如，然后然后规则 ，然后然后青龙青龙青龙青龙面板面板面板依赖依赖依赖管理管理管理管理新建新建新建新建新建新建新建新建新建新建`requests`新建`python-dotenv`新建 新建管理中，找到miuitask文件夹下的config.yaml文件，编辑账号信息及功能项目后试手动运行，日志中无报错即可`` pyyaml``python3 ``
> 
> 请问是在定时任务里面运行吗？我找了没找到任务，是需要添加定时任务吗？在订阅里面点击运行只是重新拉取文件

大佬说的这些是在`订阅管理`里面设置的，配置好以后运行就把定时任务拉取下来了
![image](https://user-images.githubusercontent.com/57740735/207482788-e2838538-7f81-47ed-ac0c-6683fa6241f7.png)

安装好依赖，然后再到`定时任务`里面找到定时任务，运行就可以了
![image](https://user-images.githubusercontent.com/57740735/207482812-1cc56be7-a78f-4e88-a3cb-3b59653243d8.png)

**Comment by d4renk** [comment]
@0-8-4 可以把青龙订阅方法写到readme里
