### ISSUE TITLE
使用docker运行.py文件报错

### ISSUE THREAD

**Issue by yzfycz** [0-8-4/miui-auto-tasks#69]
使用docker运行时，出现报错，代码如下。
Traceback (most recent call last):                                              
  File "/srv/miuitask.py", line 10, in <module>                                 
    from utils.utils import system_info, get_config, w_log, s_log, check_config,
 format_config, random_sleep, \                                                 
ModuleNotFoundError: No module named 'utils'                                    
通过pip安装了utils模块也报错。

**Comment by 0-8-4** [comment]
请详细描述一下过程，用docker 运行，一般不会出现这个问题的啊

**Comment by yzfycz** [comment]
1
docker pull o1si/miui-auto-tasks:latest
2
docker run -d \
-v /opt/miui/config.yaml:/srv/config.yaml \
-v /opt/miui:/srv \
--name miui \
o1si/miui-auto-tasks:latest
3
用docker exec 执行* * * * * python /srv/miuitask.py，提示无文件。
然后我在git克隆了一个最新的.py文件放进去在执行就显示上面的错误。

**Comment by 0-8-4** [comment]
`-v /opt/miui:/srv ` 这一行 

docker image 在构建的时候是已经把程序放进去了的，可以参见 Dockerfile。

你 docker pull 下来的 image里面已经都是有程序文件的了，但是你把你宿主机上的文件夹又挂载了进去，所以才发现找不到文件。

**Comment by 0-8-4** [comment]
详见 https://github.com/0-8-4/miui-auto-tasks/wiki#docker

**Comment by yzfycz** [comment]
OK，解决了，谢谢解答
