### ISSUE TITLE
青龙订阅后添加任务失败

### ISSUE THREAD

**Issue by liuxi378** [0-8-4/miui-auto-tasks#71]
![微信截图_20221211000055](https://user-images.githubusercontent.com/60069157/206863997-972c8f92-579c-4240-9ce3-837125024a7b.png)
还请详细说下，谢谢了，刚接触这个玩意，还是想靠这个整个小米13（手动滑稽）

**Comment by TardisXE** [comment]
这个错误原因更像是青龙面板自身，运行订阅后青龙的脚本管理中是否多出来了0-8-4_miui-auto-tasks_master？

**Comment by liuxi378** [comment]
![Screenshot_2022-12-11-09-46-10-484_com android chrome](https://user-images.githubusercontent.com/60069157/206882719-49dcdda7-23c1-4029-8466-ef01d3b0d0cd.jpg)
有文件，但是我没找到在哪里能运行起来的地方

**Comment by TardisXE** [comment]
先在上述脚本管理中编辑修改config.yaml配置文件，再查看青龙面板的定时任务中是否存在`miuitask.py`，如果没有可手动新建，命令为`task 0-8-4_miui-auto-tasks_master/miuitask.py `，定时规则`0 9 * * *`

**Comment by TardisXE** [comment]
另外目前在脚本拉取完成后建议禁用订阅，以防止配置文件被更新覆盖，后续版本我可能会尝试对青龙面板进行进一步适配调整

**Comment by 0-8-4** [comment]
link to #68
