### ISSUE TITLE
社区签到失败提示"status"

### ISSUE THREAD

**Issue by ilhmtfmlt2** [0-8-4/miui-auto-tasks#74]
从今天开始的，或者今天开始注意到的，没有之前的日志，但大概是最近几天
![2F39BD7A-8EE8-4494-AE8A-E228B067AC77](https://user-images.githubusercontent.com/83404297/216033950-cd84ab0b-c981-41e8-8837-36267c213cad.png)

**Comment by ilhmtfmlt2** [comment]
![Uploading AF19454D-3B68-4529-9FD7-43D917A1AA62.png…]()
从新下载了一遍更换了一个账号依旧如此

**Comment by ilhmtfmlt2** [comment]
![Uploading 6496140B-31F1-4B0A-8890-D484228FEF0D.png…]()

**Comment by OwnerCM** [comment]
同样的问题，是不是签到接口改了

**Comment by ilhmtfmlt2** [comment]
> 同样的问题，是不是签到接口改了

不知道，等作者吧

**Comment by 0-8-4** [comment]
我们在看了，粗略看了一下，应该是接口返回体结构改了，导致取值失败从而抛出异常，不过还没测试。 @TardisLX

**Comment by ilhmtfmlt2** [comment]
新年的那几天签到给的经验特别多，一天好几十

**Comment by TardisXE** [comment]
社区接口加了一个V2版并且对原有接口进行了部分修改，目前已修改适配原有接口，后续版本更换使用V2接口。

**Comment by OwnerCM** [comment]
> 社区接口加了一个V2版并且对原有接口进行了部分修改，目前已修改适配原有接口，后续版本更换使用V2接口。

这个版本好像最后的成长值获取失败了，好像是userinfo接口没有point返回了

**Comment by TardisXE** [comment]
> > 社区接口加了一个V2版并且对原有接口进行了部分修改，目前已修改适配原有接口，后续版本更换使用V2接口。
> 
> 
> 
> 这个版本好像最后的成长值获取失败了，好像是userinfo接口没有point返回了

是，下个版本会修改，顺带看看增加等级提示之类的
