### ISSUE TITLE
浏览帖子与浏览个人主页显示 用户未登录

### ISSUE THREAD

**Issue by LYhhl** [0-8-4/miui-auto-tasks#77]
<img width="333" alt="image" src="https://user-images.githubusercontent.com/123797478/216767446-e9c8e494-8df9-4bac-8f83-ac4aa212499c.png">

**Comment by TardisXE** [comment]
我这边无法复现，请问使用的版本是否为最新的1.5.2.3？

**Comment by LYhhl** [comment]
> 我这边无法复现，请问使用的版本是否为最新的1.5.2.3？

是的，用青龙拉取的最新版

**Comment by TardisXE** [comment]
项目已更新，请尝试使用v1.6.0

**Comment by YiChen2025** [comment]
怎么解决

**Comment by YiChen2025** [comment]
![QQ截图20231202121350](https://github.com/0-8-4/miui-auto-tasks/assets/80463727/1a1979b4-62f2-480b-b8a3-2465bc994a8a)
![QQ截图20231202121439](https://github.com/0-8-4/miui-auto-tasks/assets/80463727/848607c5-af5e-4903-9327-9e9f337514b2)

**Comment by wu17481748** [comment]
> 我这边无法复现，请问使用的版本是否为最新的1.5.2.3？

最新docker版本无法签到
![Screenshot_2023-12-15-12-28-13-252_com microsoft emmx](https://github.com/0-8-4/miui-auto-tasks/assets/106220792/ee1fa65d-152e-4d50-93ac-a5ab02555c36)

login.login:72 - Cookie有效，跳过登录
04:00:06 - INFO  | miuitask.main:33 - 开始执行抢先体验小米澎湃OS！任务
04:00:06 - ERROR | miuitask.main:41 - 未找到抢先体验小米澎湃OS！任务
04:00:06 - INFO  | miuitask.main:33 - 开始执行每日签到任务
04:00:08 - ERROR | utils.get_token:234 - 遇到未知错误，无法获取TOKEN
04:00:08 - INFO  | sign.sign:87 - 未获取到token, 跳过每日签到
04:00:08 - INFO  | miuitask.main:33 - 开始执行浏览帖子超过10秒任务
04:00:11 - SUCCESS | sign.sign:97 - 浏览帖子超过10秒结果: 成长值+1
04:00:11 - INFO  | miuitask.main:33 - 开始执行参与拔萝卜获得奖励任务
04:00:11 - INFO  | miuitask.main:39 - 任务参与拔萝卜获得奖励被禁用
04:00:11 - ERROR | request.notify_me:74 - 未配置推送或

**Comment by koolcandy** [comment]
@wu17481748 自行解决人机验证

**Comment by wu17481748** [comment]
> @wu17481748 自行解决人机验证

请问，有什么么好办法吗？

**Comment by koolcandy** [comment]
@wu17481748 抱歉，我们不能在开源社区讨论这些东西，小米的法务部不是吃白饭的，欢迎入群讨论

**Comment by Night-stars-1** [comment]
#228 根据社区规则该issue关闭处理
