### ISSUE TITLE
当前账号需要短信验证码，请尝试修改UA或设备ID

### ISSUE THREAD

**Issue by moshi888** [0-8-4/miui-auto-tasks#79]
遇到这个问题要怎么处理？已经修改了好几遍ua

**Comment by moshi888** [comment]
有没有交流群之类的？

**Comment by 0-8-4** [comment]
> 有没有交流群之类的？

emmmm，交流群现在暂时没有，这个项目参与的人还不是很多，不过我们会考虑的。

**Comment by moshi888** [comment]
那遇到要验证码更换设备ID和ua，我换了还是不行，怎么办？

**Comment by 0-8-4** [comment]
> 遇到这个问题要怎么处理？已经修改了好几遍ua

这个UA 修改的原则是，可能需要先用你的浏览器登陆一次社区，然后把你浏览器的UA填进去，如果还是不行那就建议暂缓使用脚本吧。本质上是小米社区的一种风控。

**Comment by moshi888** [comment]
我更改了ua都不行，那就是风控吗？ 不用去获取ck吗 直接小米社区登录就可以，还是要浏览一个帖子
 Mobile Safari/537.36 XiaoMi/MiuiBrowser/16.9.15 Ua后面这些要吗？

**Comment by moshi888** [comment]
但是提醒我要登录验证码，当前账号需要验证码

**Comment by TardisXE** [comment]
> 但是提醒我要登录验证码，当前账号需要验证码

脚本是否是在帐户常用地登录的？如果不是的话使用运行脚本的设备登录[小米账户管理页](https://account.xiaomi.com)，大概率可以解决风控

**Comment by moshi888** [comment]
脚本是挂在青龙上面使用的，用的是腾讯云，不确定是不是异地？像你说的，要怎么使用？比如说腾讯云要怎么使用登录设备管理界面？

**Comment by 0-8-4** [comment]
> 脚本是挂在青龙上面使用的，用的是腾讯云，不确定是不是异地？像你说的，要怎么使用？比如说腾讯云要怎么使用登录设备管理界面？

那很有可能就是这个问题，因为我现在人正好在曼谷，我本地终端使用脚本也是提示和你一样的错误。应该是小米风控了，因为不在我的常驻地，登录。

**Comment by moshi888** [comment]
那有办法解决吗？我有事了，设备登录管理界面，把ua复制上去也不行

**Comment by moshi888** [comment]
运行脚本的设备可以大概率解除风控，我是用青龙的，我有设置了我手机登录的浏览器ua还是解除不了风控，那就没办法了吗？

**Comment by moshi888** [comment]
> > 脚本是挂在青龙上面使用的，用的是腾讯云，不确定是不是异地？像你说的，要怎么使用？比如说腾讯云要怎么使用登录设备管理界面？
> 
> 那很有可能就是这个问题，因为我现在人正好在曼谷，我本地终端使用脚本也是提示和你一样的错误。应该是小米风控了，因为不在我的常驻地，登录。

像这种要怎么解决？

**Comment by TardisXE** [comment]
> > > 脚本是挂在青龙上面使用的，用的是腾讯云，不确定是不是异地？像你说的，要怎么使用？比如说腾讯云要怎么使用登录设备管理界面？
> > 
> > 那很有可能就是这个问题，因为我现在人正好在曼谷，我本地终端使用脚本也是提示和你一样的错误。应该是小米风控了，因为不在我的常驻地，登录。
> 
> 像这种要怎么解决？

这样的话可以尝试在腾讯云上购买一个同地域的按量付费Windows云服务器然后使用浏览器登录小米社区，确认脚本运行正常后将云服务器资源销毁即可

**Comment by moshi888** [comment]
> > > > 脚本是挂在青龙上面使用的，用的是腾讯云，不确定是不是异地？像你说的，要怎么使用？比如说腾讯云要怎么使用登录设备管理界面？
> > > 
> > > 那很有可能就是这个问题，因为我现在人正好在曼谷，我本地终端使用脚本也是提示和你一样的错误。应该是小米风控了，因为不在我的常驻地，登录。
> > 
> > 像这种要怎么解决？
> 
> 这样的话可以尝试在腾讯云上购买一个同地域的按量付费Windows云服务器然后使用浏览器登录小米社区，确认脚本运行正常后将云服务器资源销毁即可

好的，我试一下服务器是广东的，那么云服务器也购买相同地域广东的即可是吧？

**Comment by 0-8-4** [comment]
> > > > 脚本是挂在青龙上面使用的，用的是腾讯云，不确定是不是异地？像你说的，要怎么使用？比如说腾讯云要怎么使用登录设备管理界面？
> > > 
> > > 
> > > 那很有可能就是这个问题，因为我现在人正好在曼谷，我本地终端使用脚本也是提示和你一样的错误。应该是小米风控了，因为不在我的常驻地，登录。
> > 
> > 
> > 像这种要怎么解决？
> 
> 这样的话可以尝试在腾讯云上购买一个同地域的按量付费Windows云服务器然后使用浏览器登录小米社区，确认脚本运行正常后将云服务器资源销毁即可

是的，他说的是对的。一般来说，云服务器和你的常住地在同一个城市，基本就不会弹验证码了。弹验证码这种东西基本用浏览器浏览登陆多几次就会消失了，每次登陆都要开一个新的无痕浏览窗口。

我刚刚登陆了两次之后，我现在在曼谷已经可以运行脚本了。 @moshi888

**Comment by 0-8-4** [comment]
> > > > > 脚本是挂在青龙上面使用的，用的是腾讯云，不确定是不是异地？像你说的，要怎么使用？比如说腾讯云要怎么使用登录设备管理界面？
> > > > 
> > > > 
> > > > 那很有可能就是这个问题，因为我现在人正好在曼谷，我本地终端使用脚本也是提示和你一样的错误。应该是小米风控了，因为不在我的常驻地，登录。
> > > 
> > > 
> > > 像这种要怎么解决？
> > 
> > 
> > 这样的话可以尝试在腾讯云上购买一个同地域的按量付费Windows云服务器然后使用浏览器登录小米社区，确认脚本运行正常后将云服务器资源销毁即可
> 
> 好的，我试一下服务器是广东的，那么云服务器也购买相同地域广东的即可是吧？

看看 广东哪里的，最好买同一个城市的。

**Comment by moshi888** [comment]
购买了服务器，公网不一样，但是地域是一样的，这样能有效果吗？试了好几回都没效果

**Comment by 0-8-4** [comment]
> 购买了服务器，公网不一样，但是地域是一样的，这样能有效果吗？试了好几回都没效果

是用的无痕浏览登陆的么？
登陆的时候有没有弹验证码？手机验证码或者滑块，或者看图识物。
操作完一次登陆进去之后，有没有关闭无痕浏览窗口，然后开个新的，然后重复以上操作，直到你用新的无痕浏览登陆不会弹验证码为止。

正常来说你的服务器 IP和你手机的常驻地在同一个城市，是没有问题的，这个是经过实测的。毕竟移动数据的网络IP肯定是会在同一个城市里面飘的。但是你手机IP再怎么飘，UA总不能跟着飘吧。

登陆完之后，要把你登陆的那个浏览器的UA 拷贝进去。直接去[这种UA识别网站](https://www.whatsmyua.info)，把UA 整个复制到配置文件里面，全部都复制。比如我的就是 `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.3 Safari/605.1.15` 长不重要，重要的是和登陆的浏览器的UA是一样的。

**Comment by moshi888** [comment]
我有空再试一下，不行的话我就研究一下怎么在当前的服务器的IP下去处理一个新的网络或浏览器？这样子就可以解决了，谢谢

**Comment by LYhhl** [comment]
> 我有空再试一下，不行的话我就研究一下怎么在当前的服务器的IP下去处理一个新的网络或浏览器？这样子就可以解决了，谢谢

先查出你运行脚本服务器的公网IP地址。然后在本地电脑用爱加速软件加速到你服务器IP的地址后网页登陆小米账号和小米社区，加速的地址必须省市都相同就可以了
