### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by okatu-loli** [0-8-4/miui-auto-tasks#8]
![image](https://user-images.githubusercontent.com/53247097/130328735-5e3ae441-cbf4-415e-8ab3-18211e170423.png)
请问这成功了吗？

**Comment by 0-8-4** [comment]
是的，你可以用手机进极为先进的小米社区3.0 app 查看
[首页左上角 -> 头像 -> 内测 -> 点击你参与的内测/公测项目]

**Comment by okatu-loli** [comment]
ok，谢谢回复
