### ISSUE TITLE
脚本不带推送通知功能是吧？

### ISSUE THREAD

**Issue by moshi888** [0-8-4/miui-auto-tasks#81]
如果要用server酱，或者其他通知的方法没有接口，只能自己编写吧，从哪个文件夹下手？

**Comment by 0-8-4** [comment]
脚本不带推送的功能，但其实一直加上去的想法，#70 也有提到。不过想来想去，没办法整的比较普适性。不过现在既然已经有两个人提出了，我们也就可以把这件事情提上日程，现在可以开始讨论。

我个人原来是这样想的，原来我是自己搭建了一个QQ机器人，我是自己给自己的机器人设计了接口的，没有用公开的解决方案，这件事情就一直搁置了。后来#70 提出的时候我个人是打算直接把代码写出来，贴在#70 里面的，后来因为要赶论文就一直没动手，然后就把这件事给鸽了。

现在有两个人提出来需要，需要加在代码里面的话，我又不是很像动到原来的配置文件，毕竟这个不是说加一个开关上去就可以的，配置server酱或者其他也是需要账户或者密钥的配置的。但是重开一个文件那两个文件之间的逻辑又需要仔细思考，直接hardcode，写在代码里面又不是很对劲。

如果你是有开发能力的话，你也可以想一下怎么做的普适性一点。然后提个PR

**Comment by moshi888** [comment]
辛苦了，确实不好写，但是没有推送，感觉确实不是很方便，期待下个版本更新，谢谢 关于推送这方面不是很懂逻辑
