### ISSUE TITLE
新版本的问题

### ISSUE THREAD

**Issue by moshi888** [0-8-4/miui-auto-tasks#84]
Traceback (most recent call last):
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/miuitask.py", line 11, in <module>
    from utils.utils import system_info, get_config, w_log, s_log, check_config, format_config, random_sleep, \
  File "/ql/data/scripts/0-8-4_miui-auto-tasks_master/utils/utils.py", line 9, in <module>
    from onepush import notify
ModuleNotFoundError: No module named 'onepush'

运行的时候报这个错误，要去哪里添加添加什么东西呢？各位大佬们，请教一下，还不是很懂，谢谢
![IMG_20230214_175729.jpg](https://user-images.githubusercontent.com/89541649/218701765-43e437f7-b4c9-4af5-95c4-139aa6d2659c.jpg)

**Comment by Night-stars-1** [comment]
新建依赖
如下图
![Screenshot_2023-02-14-18-08-16-156_com android chrome](https://user-images.githubusercontent.com/99261160/218704555-ec7c0b61-8f68-4949-8ea1-7c319c4abb25.png)

**Comment by moshi888** [comment]
添加完依赖以后，config这个文件夹怎么添加推送呢？我找了一圈，没看到添加什么代码，我主要是想添加一个pushplus的推送，这个应该怎么写？在这个config的文件夹下

**Comment by moshi888** [comment]
ONEPUSH:
  notifier: pushplus
  params:
    title: 
    token: XXXXXXXXXXXXXXXXXXXXXXXX
    markdown: false
用自带的这个填写好像不行，填写进去以后脚本就无法正常运行

**Comment by moshi888** [comment]
想去添加推送，在config这个文件夹下，添加如下代码，以后还是报错了，帮我看一下这步要怎么处理？各位大佬，谢谢
ONEPUSH:
  notifier: pushplus
  params:
    title: 
    token: XXXXXXXXXXXXXXXXXXXXXXXX
    markdown: false
![IMG_20230214_182646.jpg](https://user-images.githubusercontent.com/89541649/218709049-a7d85544-fdd9-4907-8482-d0e1e282d090.jpg)

**Comment by Night-stars-1** [comment]
> 想去添加推送，在config这个文件夹下，添加如下代码，以后还是报错了，帮我看一下这步要怎么处理？各位大佬，谢谢 ONEPUSH: notifier: pushplus params: title: token: XXXXXXXXXXXXXXXXXXXXXXXX markdown: false ![IMG_20230214_182646.jpg](https://user-images.githubusercontent.com/89541649/218709049-a7d85544-fdd9-4907-8482-d0e1e282d090.jpg)

截图配置文件看一下，敏感消息打码处理

**Comment by moshi888** [comment]
![IMG_20230214_184110.jpg](https://user-images.githubusercontent.com/89541649/218712352-4a371b10-1783-46ac-b959-0a5103e0d09e.jpg)
帮忙看一下是哪里的问题？导致推送信息用不了，会运行失败

**Comment by Night-stars-1** [comment]
> 帮忙看一下是哪里的问题？导致推送信息用不了，会运行失败

ONEPUSH应该顶格写，参考配置如图
![Screenshot_2023-02-14-18-51-16-740_bin mt plus](https://user-images.githubusercontent.com/99261160/218714496-c4f7397b-43b2-4917-a77b-f03593df23ea.png)
并且你配置的是tg推送，你都没有好好看简介

**Comment by moshi888** [comment]
好的好的，解决了我那个梯具是因为那时候弄了一下，就是想找到问题的故障，我自己是用pusplus解决了，谢谢

**Comment by Night-stars-1** [comment]
> 好的好的，解决了我那个梯具是因为那时候弄了一下，就是想找到问题的故障，我自己是用pusplus解决了，谢谢

另外你的userid:后面没有加空格，这会报错。
