### ISSUE TITLE
青龙更新不成功。其他的拉库可以。应该不是网络问题

### ISSUE THREAD

**Issue by mmeiwenlong** [0-8-4/miui-auto-tasks#87]
![QQ截图20230217204947](https://user-images.githubusercontent.com/44661424/219657641-ae6be13f-441d-45a0-886f-b1bf8fc8e82a.png)

**Comment by mmeiwenlong** [comment]
![QQ截图20230217205538](https://user-images.githubusercontent.com/44661424/219658685-9bbafdd1-86a0-45b4-bd10-9f00c4847bbb.png)
拉到了没文件的

**Comment by Night-stars-1** [comment]
> ![QQ截图20230217205538](https://user-images.githubusercontent.com/44661424/219658685-9bbafdd1-86a0-45b4-bd10-9f00c4847bbb.png) 拉到了没文件的

自行上传脚本
