### ISSUE TITLE
能够正常登录，但无法进行点赞等操作

### ISSUE THREAD

**Issue by hongjr03** [0-8-4/miui-auto-tasks#9]
16:19:23 | 开始登录小米账号
16:19:24 | 账号登录完成
16:19:24 | 本脚本支持社区签到，因该功能存在风险默认禁用
16:19:24 | 如您愿意承担一切可能的后果，可编辑脚本手动打开该功能
16:19:24 | 开始活跃分任务出错
16:19:24 | 正在完成BUG反馈任务
16:19:24 | 发表内容出错
16:19:24 | 3秒后执行提建议任务
16:19:24 | 领取活跃分出错
16:19:27 | 正在完成提建议任务
16:19:27 | 发表内容出错
16:19:27 | 正在完成满意度调查任务
16:19:27 | 获取问卷ID出错，满意度投票失败
16:19:27 | 正在完成点赞任务
16:19:27 | 开始活跃分任务出错
16:19:27 | 点赞出错
16:19:27 | 取消点赞出错
16:19:27 | 点赞出错
16:19:28 | 取消点赞出错
16:19:28 | 点赞出错
16:19:28 | 取消点赞出错
16:19:28 | 点赞出错
16:19:28 | 取消点赞出错
16:19:29 | 点赞出错
16:19:29 | 取消点赞出错
16:19:29 | 领取活跃分出错
16:19:29 | 正在完成活跃分_关注任务
16:19:29 | 开始活跃分任务出错
16:19:29 | 取关用户出错
16:19:29 | 关注用户出错
16:19:29 | 5秒后领取活跃分_关注任务
16:19:34 | 领取活跃分出错
16:19:34 | 正在完成活跃分_加圈任务
16:19:34 | 开始活跃分任务出错
16:19:34 | 退出圈子出错
16:19:34 | 加入圈子出错
16:19:34 | 5秒后领取活跃分_加圈任务
16:19:39 | 领取活跃分出错
16:19:39 | 正在完成活跃分_发帖任务
16:19:40 | 开始活跃分任务出错
16:19:40 | 发表内容出错
16:19:40 | 5秒后领取活跃分_发帖任务
16:19:45 | 领取活跃分出错

**Comment by TardisXE** [comment]
请问使用的操作系统以及Python版本是？

**Comment by hongjr03** [comment]
Windows 11 22000.160
Python 3.9.6

**Comment by TardisXE** [comment]
在该环境下我未能复现错误，请问能否提供删去了小米ID和密码md5密文后的脚本文件？

**Comment by hongjr03** [comment]
https://pan.deepfal.cn/s/XVxUo

**Comment by 0-8-4** [comment]
我记得你好像之前提过issues的。请问之前有成功过么？会有这个问题么？

**Comment by TardisXE** [comment]
脚本应该没有问题，试试排查下网络能否正常访问api.vip.miui.com？

**Comment by hongjr03** [comment]
@0-8-4 是的，但上次提issue是询问能否挂内测分，今天才试了一下
@TardisLX 404报错

**Comment by 0-8-4** [comment]
> @0-8-4 是的，但上次提issue是询问能否挂内测分，今天才试了一下
> @TardisLX 404报错

你是说 你直接浏览器访问都404么？

**Comment by hongjr03** [comment]
是的

![image](https://user-images.githubusercontent.com/64763790/130351622-a32973b0-b235-4f79-8a99-1d23b5841619.png)

**Comment by hongjr03** [comment]
请问我可以要一下两位大佬的联系方式吗？我把整个文件发给你们看看

**Comment by TardisLX** [comment]
Q 82785294> 请问我可以要一下两位大佬的联系方式吗？我把整个文件发给你们看看

**Comment by TardisXE** [comment]
请问是否使用了网络代理程序？我这边测试使用全局网络代理后成功复现了问题> 请问我可以要一下两位大佬的联系方式吗？我把整个文件发给你们看看

**Comment by hongjr03** [comment]
是的，我也发现了。关闭了代理后问题解决了。[api](http://api.vip.miui.com/)依然是404状态。我需要关闭这个issue吗？

**Comment by TardisXE** [comment]
浏览器直接访问出现404状态码是正常的，这仅仅是社区的API接口地址> 是的，我也发现了。关闭了代理后问题解决了。http://api.vip.miui.com/依然是404状态。我需要关闭这个issue吗？

**Comment by hongjr03** [comment]
今天麻烦两位了❤
