### ISSUE TITLE
无法启动

### ISSUE THREAD

**Issue by Calyvers** [0-8-4/miui-auto-tasks#90]
启动报错
`File "/storage/emulated/0/Download/miui-auto-tasks-1.5.3.1/miuitask.py", line 11, in <module>
    from utils.utils import system_info, get_config, w_log, s_log, check_config, format_config, random_sleep, \
  File "/storage/emulated/0/Download/miui-auto-tasks-1.5.3.1/utils/utils.py", line 9, in <module>
    from onepush import notify
ModuleNotFoundError: No module named 'onepush'`

**Comment by 0-8-4** [comment]
使用requirements 重新安装依赖
