### ISSUE TITLE
浏览帖子错误退出圈子错误，好像小米社区那边又更新了啥时候更新一下呢？

### ISSUE THREAD

**Issue by moshi888** [0-8-4/miui-auto-tasks#96]

**Comment by moshi888** [comment]
00:00:04 | 登录社区App成功
00:00:04 | 风险功能提示：正在进行社区拔萝卜
00:00:07 | 社区拔萝卜结果：获得1金币！
00:00:07 | 当前金币数：739
00:00:07 | 风险功能提示：正在进行成长值签到
00:00:16 | 社区成长值签到结果：成长值+9
00:00:16 | 风险功能提示：正在完成浏览专题页10s任务
00:00:27 | 浏览专题页完成，但有错误：加分失败
00:00:27 | 正在完成浏览帖子10s任务，第一次
00:00:37 | 浏览帖子完成，成长值+2
00:00:37 | 正在完成浏览帖子10s任务，第二次
00:00:49 | 浏览帖子完成，但有错误：加分失败
00:00:49 | 正在完成浏览帖子10s任务，第三次
00:01:00 | 浏览帖子完成，但有错误：加分失败
这个浏览贴纸失败，这个是要更新了吗？还是怎么样处理？

**Comment by Night-stars-1** [comment]
我这边正常运行

**Comment by lukemin** [comment]
我也出错了
## 开始执行... 2023-05-11 09:46:00

09:46:00 | MIUI-AUTO-TASK v1.5.3
09:46:00 | ---------- 系统信息 -------------
09:46:00 | 操作系统平台: Linux-3.10.108-x86_64-with
09:46:00 | 操作系统版本: #42962 SMP Fri Mar 24 00:29:04 CST 2023
09:46:00 | 操作系统名称: Linux
09:46:00 | 操作系统位元: ('64bit', '')
09:46:00 | 操作系统类型: x86_64
09:46:00 | 处理器信息: 
09:46:00 | Python 版本: 3.10.11 ('main', 'May  3 2023 09:39:10')
09:46:00 | ---------- 项目信息 -------------
09:46:00 | 项目地址：https://github.com/0-8-4/miui-auto-tasks
09:46:00 | 欢迎 star，感谢東雲研究所中的大佬
09:46:00 | ---------- 配置检测 -------------
09:46:00 | 正在加载 /ql/data/scripts/0-8-4_miui-auto-tasks_master/config.yaml 配置文件
09:46:00 | 配置文件已成功加载，文件版本 v1.5.3
09:46:00 | ---------- EXECUTING -------------
09:46:01 | 账号登录完成
09:46:01 | 本脚本支持社区拔萝卜及成长值签到，因该功能存在风险默认禁用
09:46:01 | 如您愿意承担一切可能的后果，可编辑配置文件手动打开该功能
09:46:01 | 登录社区App成功
09:46:01 | 风险功能提示：正在进行社区拔萝卜
09:46:06 | 社区拔萝卜结果：获得1金币！
09:46:06 | 当前金币数：57
09:46:06 | 风险功能提示：正在进行成长值签到
09:46:15 | 社区成长值签到结果：成长值+1
09:46:15 | 正在完成浏览帖子10s任务，第一次
09:46:26 | 浏览帖子完成，成长值+1
09:46:26 | 正在完成浏览帖子10s任务，第二次
09:46:36 | 浏览帖子完成，但有错误：加分失败
09:46:36 | 正在完成浏览帖子10s任务，第三次
09:46:48 | 浏览帖子完成，但有错误：加分失败
09:46:48 | 正在完成点赞任务
09:46:48 | 签名原文：postId=36625780&timestamp=1683769608285
09:46:48 | 签名结果：8f9d4d6b6cf36b061fc9aeca6d98474c
09:46:48 | 点赞成功
09:46:57 | 取消点赞成功
09:47:02 | 签名原文：postId=36625780&timestamp=1683769622624
09:47:02 | 签名结果：6db1000ac29733c2aea9d0c9198cd69d
09:47:02 | 点赞成功
09:47:03 | 取消点赞成功
09:47:12 | 签名原文：postId=36625780&timestamp=1683769632975
09:47:12 | 签名结果：9fa6a113bc25048c1f5b877fe2362a52
09:47:13 | 点赞成功
09:47:20 | 取消点赞成功
09:47:29 | 退出小米圈子出错
09:47:29 | 'status'
09:47:32 | 加入小米圈子出错
09:47:32 | 'status'
09:47:33 | 浏览个人主页完成，成长值+1
09:47:37 | 成功获取成长值,当前成长值：491


## 执行结束... 2023-05-11 09:47:42  耗时 102 秒
